#!/usr/bin/env bash
#
# Cloud Agent environment install: durable, idempotent setup of the myUNO dev
# environment. Runs once to build the environment snapshot (and again on config
# changes). Everything here must be safe to re-run.
#
#   1. Install PostgreSQL (the platform's only hard system dependency).
#   2. Create a local .env with generated dev secrets (never committed).
#   3. Install Node dependencies.
#   4. Provision the database: migrate + seed registries + demo data.
#
# Per-boot process startup lives in start.sh, not here.
set -euo pipefail

cd "$(dirname "$0")/.."

PG_VERSION=16

echo "[install] Ensuring PostgreSQL is installed..."
if ! command -v psql >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

echo "[install] Starting PostgreSQL cluster..."
sudo pg_ctlcluster "$PG_VERSION" main start 2>/dev/null || true
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q 2>/dev/null; then break; fi
  sleep 1
done

echo "[install] Ensuring database role and databases exist..."
sudo -u postgres psql -tc "ALTER USER postgres PASSWORD 'postgres';" >/dev/null 2>&1 || true
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='myuno'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE DATABASE myuno;"
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='myuno_test'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE DATABASE myuno_test;"

echo "[install] Ensuring .env exists (dev secrets are generated, never committed)..."
if [ ! -f .env ]; then
  SESSION_SECRET="$(openssl rand -base64 32)"
  ENCRYPTION_KEY="$(openssl rand -hex 32)"
  CRON_SECRET="$(openssl rand -hex 24)"
  ICAL_FEED_SECRET="$(openssl rand -hex 32)"
  cat > .env <<EOF
# Local development environment (generated by .cursor/install.sh).
# Never commit this file — it holds per-environment secrets.
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/myuno
DATABASE_URL_TEST=postgresql://postgres:postgres@localhost:5432/myuno_test

SESSION_SECRET=${SESSION_SECRET}
NEXTAUTH_SECRET=${SESSION_SECRET}
NEXTAUTH_URL=http://localhost:3000

# NODE_ENV is intentionally unset: Next.js sets it per command. Pinning it to
# development here would break 'npm run build'.
CONTENT_REVIEW_GATE_ENABLED=false

ENCRYPTION_KEY=${ENCRYPTION_KEY}
CRON_SECRET=${CRON_SECRET}
PAYMENT_PROVIDER=mock
ICAL_FEED_SECRET=${ICAL_FEED_SECRET}
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF
fi

echo "[install] Installing Node dependencies..."
npm ci

# Load the local .env so the provisioning scripts see DATABASE_URL etc.
set -a
# shellcheck disable=SC1091
. ./.env
set +a

echo "[install] Provisioning application database (migrate + seed registries)..."
node scripts/provision-database.mjs

echo "[install] Seeding demo data for development..."
npm run db:seed

echo "[install] Applying migrations to the test database..."
DATABASE_URL="$DATABASE_URL_TEST" npx prisma migrate deploy

echo "[install] Generating Prisma client..."
npx prisma generate

echo "[install] Done."
