export const AGENT_LABELS = {
  'agent.contracts': 'Contracts and completion',
  'agent.sqm': 'm²',
  'agent.home': "Agent HomeSpace",
  'agent.contacts': "Contacts",
  'agent.opportunities': "Opportunities",
  'agent.activities': "Follow-ups",
  'agent.inventory': "Inventory",
  'agent.offers': "Client offers",
  'agent.knowledge': "Knowledge & FAQ",
  'agent.commissions': "Commissions",
  'agent.team': "Agency team",
  'agent.workspace': "Agency workspace",
  'agent.intro': "Your clients, inventory, answers and next actions in one place.",
  'agent.privacy': "Client channels and notes stay in your workspace. Share an opportunity with MyUNO when you need coordination.",
  'agent.empty': "Nothing here yet. Start with your next client or opportunity.",
  'agent.name': "Client name",
  'agent.email': "Email",
  'agent.phone': "Phone (+country code)",
  'agent.telegram': "Telegram username",
  'agent.privateNotes': "Private notes",
  'agent.newContact': "Add contact",
  'agent.newOpportunity': "Create opportunity",
  'agent.contact': "Contact",
  'agent.title': "Title",
  'agent.type': "Type",
  'agent.rental': "Rental",
  'agent.purchase': "Purchase",
  'agent.sale': "Sale",
  'agent.new': "New",
  'agent.qualified': "Qualified",
  'agent.discovery': "Needs & selection",
  'agent.proposal': "Proposal",
  'agent.negotiation': "Negotiation",
  'agent.nurture': "Later",
  'agent.won': "Completed",
  'agent.lost': "Lost",
  'agent.stage': "Stage",
  'agent.move': "Update stage",
  'agent.lostReason': "Reason if lost",
  'agent.newTask': "Schedule follow-up",
  'agent.subject': "Next action",
  'agent.dueAt': "Due date",
  'agent.complete': "Complete",
  'agent.completed': "Completed",
  'agent.open': "Open",
  'agent.cancelled': "Cancelled",
  'agent.handover': "Ask MyUNO to coordinate",
  'agent.request': "What should MyUNO handle?",
  'agent.consent': "I have the client's permission to share their name and contact channels with MyUNO for this opportunity.",
  'agent.receipt': "Introduction receipt",
  'agent.queued': "Awaiting coordinator",
  'agent.acknowledged': "Coordinator assigned",
  'agent.declined': "Declined",
  'agent.coordinator': "Your coordinator",
  'agent.quote': "Prepare client quote",
  'agent.amount': "Property price / rental amount, THB",
  'agent.fee': "Client fees, THB",
  'agent.deposit': "Deposit (separate), THB",
  'agent.terms': "Terms, dates and inclusions",
  'agent.expiresAt': "Valid until",
  'agent.offering': "Property offering",
  'agent.quotePolicy': "Drafts need MyUNO review before sharing. A quote does not reserve inventory or form a contract.",
  'agent.draft': "Draft",
  'agent.submitted': "In MyUNO review",
  'agent.approved': "Approved",
  'agent.revoked': "Revoked",
  'agent.submit': "Request quote review",
  'agent.revoke': "Revoke offer",
  'agent.share': "Create share link",
  'agent.copy': "Copy link",
  'agent.copied': "Link copied",
  'agent.whatsapp': "Open WhatsApp",
  'agent.telegramShare': "Open Telegram",
  'agent.shareNote': "Choose the client and press send in your messenger. Opening a messenger does not confirm delivery.",
  'agent.search': "Search approved answers",
  'agent.searchAction': "Search",
  'agent.knowledgeEmpty': "No approved answer found in this language. Ask your MyUNO coordinator through an opportunity handover.",
  'agent.source': "Source",
  'agent.reviewed': "Published",
  'agent.commissionNote': "Payment target: same day once due, no later than 3 days. Your approved agreement defines the due milestone and day basis. No commission is estimated without approved terms.",
  'agent.pending': "Pending",
  'agent.due': "Due",
  'agent.paid': "Paid",
  'agent.disputed': "Under review",
  'agent.targetAt': "Target date",
  'agent.deadlineAt': "Deadline",
  'agent.manager': "Agency manager",
  'agent.agent': "Agent",
  'agent.saved': "Saved",
  'agent.error': "Could not complete this action. Check the fields or ask your coordinator.",
  'agent.saving': "Saving…",
  'agent.notMember': "Your agent workspace is not activated yet. Register your account and contact MyUNO to set up your agency.",
  'agent.register': "Register an account",
  'agent.help': "Contact MyUNO",
  'agent.adminTitle': "Agent partners & coordination",
  'agent.provision': "Activate agency",
  'agent.agencyName': "Agency name",
  'agent.memberEmail': "Registered agent email",
  'agent.addMember': "Add agency member",
  'agent.role': "Role",
  'agent.revokeMember': "Revoke access",
  'agent.suspend': "Suspend workspace",
  'agent.activate': "Activate workspace",
  'agent.approveQuote': "Approve client quote",
  'agent.approvalNote': "Verify prices, fees, dates and terms against authorized commercial conditions before approving.",
  'agent.handoverQueue': "Shared opportunities",
  'agent.reviewQueue': "Quote review queue",
  'agent.knowledgeDraft': "Draft knowledge article",
  'agent.body': "Answer",
  'agent.sourceUrl': "Source URL",
  'agent.locale': "Language",
  'agent.publish': "Publish reviewed answer",
  'agent.withdraw': "Withdraw answer",
  'agent.withdrawn': "Withdrawn",
  'agent.clientQuote': "Client quotation",
  'agent.total': "Price plus client fees, THB",
  'agent.validUntil': "Valid until",
  'agent.availabilityNote': "Availability and contractual terms will be confirmed by MyUNO before commitment.",
  'agent.partnersTitle': "Work with MyUNO",
  'agent.partnersBody': "Focus on your client. Use our inventory, prepare client offers and ask MyUNO to coordinate administration and contracts. Access is activated for approved agencies.",
  'agent.goPortal': "Open Agent HomeSpace",
  'agent.myunoAdmin': "MyUNO coordination",
  'agent.seeAll': "View all",
  'agent.limited': "Showing up to 100 recent records in each section.",
  'agent.quoteExpiry': "Quote expired",
  'agent.inventoryNote': "Sales and long-term rental listings shown here pass current authority checks. Availability is confirmed during coordination.",
  'agent.status': "Status",
  'agent.recordedAt': "Recorded",
};
