import { Metadata } from 'next';
import Link from 'next/link';
import { getLabels } from '@/lib/i18n';
import { LeadFormSection } from '@/app/(public)/lead-form-section';
import { track } from '@/modules/analytics';
import { prisma } from '@/lib/prisma';

export const dynamic = 'force-dynamic';

export async function generateMetadata(): Promise<Metadata> {
  const labels = await getLabels({
    'audience.mc.title': 'For Management Companies',
    'audience.mc.subtitle': 'Demanded ops. Single platform. More income.',
  });
  return {
    title: `${labels['audience.mc.title']} | myUNO`,
    description: labels['audience.mc.subtitle'],
    alternates: { canonical: '/management-companies' },
  };
}

export default async function ManagementCompaniesPage() {
  // Track analytics event
  await track(prisma, 'page_audience_viewed', {
    audience: 'mc',
  }).catch(() => null);

  const labels = await getLabels({
    'audience.mc.title': 'For Management Companies',
    'audience.mc.subtitle': 'Demanded ops. Single platform. More income.',
    'audience.mc.cta': 'Learn more',
    'audience.mc.how.title': 'How it works',
    'audience.mc.how.step1_title': 'Talk to us',
    'audience.mc.how.step1_body':
      'Leave your contact below — tell us which projects you manage and how you work today.',
    'audience.mc.how.step2_title': 'Plug your units into the platform',
    'audience.mc.how.step2_body':
      'Your managed units go live on myUNO with their own engagement terms — your fee structure is configured per unit, not hard-coded.',
    'audience.mc.how.step3_title': 'Demand arrives, rails included',
    'audience.mc.how.step3_body':
      'Occupancy generated by the platform reach, with booking, payment, compliance, and reporting rails you do not have to build.',
    'audience.mc.value.title': 'What you get',
    'audience.mc.value.point1':
      'Demand you cannot generate alone: platform-driven bookings flow to your managed units.',
    'audience.mc.value.point2':
      'Infrastructure without the build: TM30 filing, payment recording, statements, and a guest home space — ready.',
    'audience.mc.value.point3':
      'Your own portal: managed units, bookings, service orders, and your fee report in one view.',
    'audience.mc.trust.body':
      'Every stay on the platform is verified and compliant — your managed units inherit the same trust infrastructure.',
    'audience.mc.trust.link': 'How we build trust →',
  });

  const steps = ([1, 2, 3] as const).map((n) => ({
    title: labels[`audience.mc.how.step${n}_title`],
    body: labels[`audience.mc.how.step${n}_body`],
  }));
  const values = ([1, 2, 3] as const).map((n) => labels[`audience.mc.value.point${n}`]);

  return (
    <main className="min-h-screen bg-white">
      <section className="bg-gradient-to-br from-brand-andaman to-brand-andaman-dark text-surface-ivory py-64 px-24">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-heading-1 font-bold mb-24">{labels['audience.mc.title']}</h1>
          <p className="text-body text-surface-ivory/90 mb-32">
            {labels['audience.mc.subtitle']}
          </p>
          <Link
            href="#lead-form"
            className="inline-flex items-center justify-center bg-surface-ivory text-brand-andaman px-32 py-16 rounded-lg font-semibold hover:bg-opacity-90"
          >
            {labels['audience.mc.cta']} →
          </Link>
        </div>
      </section>

      <section className="max-w-4xl mx-auto py-64 px-24">
        <h2 className="text-heading-1 font-bold text-text-ink mb-40">
          {labels['audience.mc.how.title']}
        </h2>
        <ol className="space-y-32">
          {steps.map((step, i) => (
            <li key={step.title} className="flex gap-24">
              <span className="text-heading-2 font-bold text-brand-andaman">{i + 1}</span>
              <div>
                <h3 className="text-heading-3 font-bold text-text-ink mb-8">{step.title}</h3>
                <p className="text-body text-text-secondary">{step.body}</p>
              </div>
            </li>
          ))}
        </ol>
      </section>

      <section className="bg-surface-background py-64 px-24">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-heading-1 font-bold text-text-ink mb-40">
            {labels['audience.mc.value.title']}
          </h2>
          <ul className="space-y-24 text-body">
            {values.map((point) => (
              <li key={point} className="flex gap-20">
                <span className="text-brand-andaman font-bold">✓</span>
                <span className="text-text-secondary">{point}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className="max-w-4xl mx-auto py-64 px-24 text-center">
        <p className="text-body text-text-secondary mb-24">{labels['audience.mc.trust.body']}</p>
        <Link href="/trust" className="text-brand-andaman font-semibold hover:underline">
          {labels['audience.mc.trust.link']}
        </Link>
      </section>

      <div id="lead-form">
        <LeadFormSection audience="mc" />
      </div>
    </main>
  );
}
