import { Metadata } from 'next';
import { getLabels } from '@/lib/i18n';
import { AudienceLanding } from '@/components/premium/AudienceLanding';
import { LeadFormSection } from '@/app/(public)/lead-form-section';
import { track } from '@/modules/analytics';
import { prisma } from '@/lib/prisma';
import { publicPageAlternates } from '@/lib/seo';

export const dynamic = 'force-dynamic';

export async function generateMetadata(): Promise<Metadata> {
  const labels = await getLabels({
    'audience.mc.title': 'For Management Companies',
    'audience.mc.subtitle': 'Demanded ops. Single platform. More income.',
  });
  return {
    title: `${labels['audience.mc.title']} | myUNO`,
    description: labels['audience.mc.subtitle'],
    alternates: publicPageAlternates('/management-companies'),
  };
}

export default async function ManagementCompaniesPage() {
  // Track analytics event
  await track(prisma, 'page_audience_viewed', {
    audience: 'mc',
  }).catch(() => null);

  const labels = await getLabels({
    'audience.mc.title': 'For Management Companies',
    'audience.mc.subtitle': 'Demanded ops. Single platform. More income.',
    'audience.mc.cta': 'Learn more',
    'audience.mc.how.title': 'How it works',
    'audience.mc.how.step1_title': 'Talk to us',
    'audience.mc.how.step1_body':
      'Leave your contact below — tell us which projects you manage and how you work today.',
    'audience.mc.how.step2_title': 'Plug your units into the platform',
    'audience.mc.how.step2_body':
      'Your managed units go live on myUNO with their own engagement terms — your fee structure is configured per unit, not hard-coded.',
    'audience.mc.how.step3_title': 'Demand arrives, rails included',
    'audience.mc.how.step3_body':
      'Occupancy generated by the platform reach, with booking, payment, compliance, and reporting rails you do not have to build.',
    'audience.mc.value.title': 'What you get',
    'audience.mc.value.point1':
      'Demand you cannot generate alone: platform-driven bookings flow to your managed units.',
    'audience.mc.value.point2':
      'Infrastructure without the build: TM30 filing, payment recording, statements, and a guest home space — ready.',
    'audience.mc.value.point3':
      'Your own portal: managed units, bookings, service orders, and your fee report in one view.',
    'audience.mc.trust.body':
      'Every stay on the platform is verified and compliant — your managed units inherit the same trust infrastructure.',
    'audience.mc.trust.link': 'How we build trust →',
  });

  const steps = ([1, 2, 3] as const).map((n) => ({
    title: labels[`audience.mc.how.step${n}_title`],
    body: labels[`audience.mc.how.step${n}_body`],
  }));
  const values = ([1, 2, 3] as const).map((n) => labels[`audience.mc.value.point${n}`]);

  return (
    <AudienceLanding
      title={labels['audience.mc.title']}
      subtitle={labels['audience.mc.subtitle']}
      cta={{ href: '#lead-form', label: labels['audience.mc.cta'] }}
      stepsTitle={labels['audience.mc.how.title']}
      steps={steps}
      valuesTitle={labels['audience.mc.value.title']}
      values={values}
      trust={{ body: labels['audience.mc.trust.body'], href: '/trust', link: labels['audience.mc.trust.link'] }}
    >
      <div id="lead-form">
        <LeadFormSection audience="mc" />
      </div>
    </AudienceLanding>
  );
}
