/** Shared label keys for unit calendar / availability pages (ops + MC). */
export const UNIT_CALENDAR_LABEL_KEYS = {
  'staff.calendar.title': 'Availability & pricing',
  'staff.calendar.intro':
    'Block this unit for maintenance or an owner stay, or set a one-off rate for a date range.',
  'staff.calendar.loading': 'Loading…',
  'staff.calendar.error_generic': 'Something went wrong. Please try again.',
  'staff.calendar.saving': 'Saving…',
  'staff.calendar.blocks_title': 'Blocked dates',
  'staff.calendar.blocks_none': 'No blocked dates.',
  'staff.calendar.reason.maintenance': 'Maintenance',
  'staff.calendar.reason.owner_hold': 'Owner hold',
  'staff.calendar.reason.other': 'Other',
  'staff.calendar.start_date': 'Start date',
  'staff.calendar.end_date': 'End date',
  'staff.calendar.reason_field': 'Reason',
  'staff.calendar.note': 'Note (optional)',
  'staff.calendar.add_block': 'Block these dates',
  'staff.calendar.remove': 'Remove',
  'staff.calendar.pricing_title': 'Pricing overrides',
  'staff.calendar.pricing_none': 'No pricing overrides.',
  'staff.calendar.per_night': '/night',
  'staff.calendar.nightly_rate': 'Nightly rate (THB)',
  'staff.calendar.label': 'Label (optional)',
  'staff.calendar.add_rule': 'Add rate',
  'staff.calendar.integrations_title': 'Channel calendar sync',
  'staff.calendar.integrations_last_sync': 'Last sync',
  'staff.calendar.integrations_never': 'Never',
  'integrations.status.active': 'Active',
  'integrations.status.error': 'Error',
  'integrations.status.disabled': 'Disabled',
  'integrations.key.ical_airbnb': 'Airbnb iCal',
  'integrations.key.ical_booking': 'Booking.com iCal',
  'integrations.key.ical_agoda': 'Agoda iCal',
} as const;
