-- Stitch additive gaps G1/G2/G4 — founder-approved 2026-10-05. Expand-only: nothing existing touched.
-- G1 — human-readable booking reference ("UN-84920"). Generated by the application on create;
-- existing rows backfilled in a separate, reviewed step.
ALTER TABLE "booking" ADD COLUMN "reference" TEXT;
CREATE UNIQUE INDEX "booking_reference_key" ON "booking"("reference");

-- G2 — live dispatch for a service order, outside the guarded ServiceOrderStatus machine.
CREATE TABLE "service_order_dispatch" (
    "id"               TEXT NOT NULL,
    "created_at"       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"       TIMESTAMP(3) NOT NULL,
    "service_order_id" TEXT NOT NULL,
    "stage"            TEXT NOT NULL DEFAULT 'assigned',   -- assigned | en_route | in_service | done
    "staff_name"       TEXT,
    "staff_phone"      TEXT,                               -- PII: shown only to the orderer, never in analytics/URLs
    "eta_at"           TIMESTAMP(3),
    "last_lat"         DECIMAL(9,6),
    "last_lng"         DECIMAL(9,6),
    "last_position_at" TIMESTAMP(3),

    CONSTRAINT "service_order_dispatch_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "service_order_dispatch_stage_check"
      CHECK ("stage" IN ('assigned','en_route','in_service','done'))
);
CREATE UNIQUE INDEX "service_order_dispatch_service_order_id_key" ON "service_order_dispatch"("service_order_id");
ALTER TABLE "service_order_dispatch"
  ADD CONSTRAINT "service_order_dispatch_service_order_id_fkey"
  FOREIGN KEY ("service_order_id") REFERENCES "service_order"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- RLS decision: server-only access through the service role (same as homepage_placement).
ALTER TABLE "service_order_dispatch" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "service_order_dispatch" FROM PUBLIC, anon, authenticated;
COMMENT ON TABLE "service_order_dispatch" IS
  'Live dispatch details (staff, ETA, position) for a service order; never carries price, status authority or payment facts.';

-- G4 (optional) — inspection zone results; photos stay in operational_task_media.
ALTER TABLE "operational_task" ADD COLUMN "checklist" JSONB;
