import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getCurrentUser } from '@/app/actions/getCurrentUser';
import { getAuthorizedOperationalUnitIds, getDepartmentProjectIds, getMCProjectScopes } from '@/app/libs/projectScope';
import { prisma } from '@/lib/prisma';
import { getLabels } from '@/lib/i18n';
import { getMCManagedUnits } from '@/modules/projects';
import { getOperatingSpaceMembership, getOperatingSpaceUnitIds, hasOperatingSpaceCapability, listOperationalTasks } from '@/modules/ops';
import OperationalTaskQueueClient from '@/components/ops/OperationalTaskQueueClient';
import OperationalTaskCreateForm from '@/components/ops/OperationalTaskCreateForm';

export const dynamic = 'force-dynamic';

export default async function OperationalTasksPage({
  searchParams,
}: { searchParams?: { unitId?: string; mc?: string; spaceId?: string } }) {
  const user = await getCurrentUser();
  if (!user) redirect('/login?next=/ops/tasks');

  const requestedSpaceId = typeof searchParams?.spaceId === 'string' ? searchParams.spaceId : '';
  const spaceMembership = requestedSpaceId && !user.isAdmin
    ? await getOperatingSpaceMembership(prisma, requestedSpaceId, user.identityId)
    : null;
  if (requestedSpaceId && !user.isAdmin) {
    if (!spaceMembership?.active) redirect('/ops/spaces');
    if (!(await hasOperatingSpaceCapability(prisma, requestedSpaceId, user.identityId, 'manage_tasks'))) {
      redirect('/ops/spaces/' + encodeURIComponent(requestedSpaceId));
    }
  }
  const spaceUnitIds = requestedSpaceId
    ? await getOperatingSpaceUnitIds(prisma, requestedSpaceId)
    : [];

  const staffProjectIds = await getDepartmentProjectIds(user, [
    'housekeeping', 'front_desk', 'maintenance', 'guest_care', 'reservations',
  ]);
  const mcScopes = getMCProjectScopes(user);
  if (!user.isAdmin && !staffProjectIds.length && !mcScopes.length) redirect('/');

  const mcManagedUnitIds = new Set<string>();
  for (const scope of mcScopes) {
    const units = await getMCManagedUnits(
      prisma,
      user.identityId,
      scope.projectId,
      scope.organizationId
    );
    for (const unit of units) mcManagedUnitIds.add(unit.id);
  }

  if (!user.isAdmin && !staffProjectIds.length && !mcManagedUnitIds.size) redirect('/');

  const requestedUnitId =
    typeof searchParams?.unitId === 'string' ? searchParams.unitId : undefined;
  const explicitMcMode = searchParams?.mc === '1' && mcScopes.length > 0;

  if (requestedUnitId && !user.isAdmin) {
    const requestedUnit = await prisma.unit.findUnique({
      where: { id: requestedUnitId },
      select: { projectId: true },
    });
    const allowed = explicitMcMode
      ? mcManagedUnitIds.has(requestedUnitId)
      : Boolean(
          requestedUnit &&
          (
            staffProjectIds.includes(requestedUnit.projectId) ||
            mcManagedUnitIds.has(requestedUnitId)
          )
        );
    if (!allowed) redirect(explicitMcMode ? '/ops/tasks?mc=1' : '/ops/tasks');
  }

  const authorizedSpaceUnitIds = requestedSpaceId && !user.isAdmin
    ? await getAuthorizedOperationalUnitIds(
        user,
        spaceUnitIds,
        ['housekeeping','front_desk','maintenance','guest_care','reservations'],
      )
    : spaceUnitIds;
  if (requestedSpaceId && !user.isAdmin && !authorizedSpaceUnitIds.length) redirect('/ops/spaces');

  const mcOnly = !user.isAdmin && !staffProjectIds.length && mcScopes.length > 0;
  const backHref = requestedSpaceId
    ? '/ops/spaces/' + encodeURIComponent(requestedSpaceId)
    : explicitMcMode || mcOnly ? '/mc/calendar' : '/ops/calendar';

  const taskFormData = requestedSpaceId
    ? await Promise.all([
        prisma.unit.findMany({
          where: { id: { in: authorizedSpaceUnitIds } },
          select: { id: true, name: true, project: { select: { name: true } } },
          orderBy: [{ project: { name: 'asc' } }, { name: 'asc' }],
        }),
        prisma.operatingTeam.findMany({
          where: { operatingSpaceId: requestedSpaceId, active: true },
          select: { id: true, name: true },
          orderBy: { name: 'asc' },
        }),
        prisma.operatingSpaceMember.findMany({
          where: { operatingSpaceId: requestedSpaceId, active: true },
          select: { identity: { select: { id: true, firstName: true, lastName: true } } },
          orderBy: { identity: { firstName: 'asc' } },
        }),
      ])
    : null;

  const labels = await getLabels({
    'staff.tasks.back': '← Calendar',
    'staff.tasks.title': 'Housekeeping & readiness',
    'staff.tasks.subtitle': 'Turnover cleaning and inspection tasks generated by checkout. Check-in is blocked while overdue required tasks remain open.',
    'staff.tasks.empty': 'No open readiness tasks.',
    'staff.tasks.update_failed': 'Task update failed',
    'staff.tasks.due': 'Due',
    'staff.tasks.assign_me': 'Assign to me',
    'staff.tasks.start': 'Start',
    'staff.tasks.inspected': 'Inspected',
    'staff.tasks.ready': 'Ready',
    'staff.tasks.resume': 'Resume',
    'staff.task_form.title': 'Task title',
    'staff.task_form.property': 'Property',
    'staff.task_form.employee': 'Employee',
    'staff.task_form.team': 'Team',
    'staff.task_form.priority.low': 'Low',
    'staff.task_form.priority.normal': 'Normal',
    'staff.task_form.priority.high': 'High',
    'staff.task_form.priority.urgent': 'Urgent',
    'staff.task_form.estimated_cost': 'Estimated cost THB',
    'staff.task_form.description': 'Description',
    'staff.task_form.blocks_inventory': 'Blocks inventory',
    'staff.task_form.creating': 'Creating…',
    'staff.task_form.create': 'Create task',
  });

  const tasks = await listOperationalTasks(prisma, {
    ...(requestedSpaceId
      ? { projectIds: [], unitIds: authorizedSpaceUnitIds }
      : !user.isAdmin
      ? explicitMcMode
        ? {
            projectIds: [],
            unitIds: Array.from(mcManagedUnitIds),
          }
        : {
            projectIds: staffProjectIds,
            unitIds: Array.from(mcManagedUnitIds),
          }
      : {}),
    unitId: requestedUnitId,
    statuses: ['planned', 'assigned', 'in_progress', 'inspected', 'blocked'],
  });

  return <main className="min-h-screen bg-surface-ivory p-16 md:p-32">
    <div className="mx-auto max-w-5xl">
      <div className="mb-24">
        <Link href={backHref} className="text-small font-semibold text-brand-andaman hover:underline">{labels['staff.tasks.back']}</Link>
        <h1 className="mt-8 font-display text-display-xl font-semibold text-text-ink">{labels['staff.tasks.title']}</h1>
        <p className="mt-4 text-body text-text-secondary">{labels['staff.tasks.subtitle']}</p>
      </div>
      {requestedSpaceId && taskFormData ? <OperationalTaskCreateForm
        operatingSpaceId={requestedSpaceId}
        units={taskFormData[0]}
        teams={taskFormData[1]}
        members={taskFormData[2]}
        labels={labels}
      /> : null}
      <OperationalTaskQueueClient
        labels={labels}
        tasks={tasks.map((task) => ({
          id: task.id,
          taskType: task.taskType,
          status: task.status,
          dueAt: task.dueAt.toISOString(),
          notes: task.notes,
          project: task.project,
          unit: task.unit,
          assignee: task.assignee,
          assignedTeam: task.assignedTeam,
          title: task.title,
          priority: task.priority,
          estimatedCostSatang: task.estimatedCostSatang,
          actualCostSatang: task.actualCostSatang,
          blocksInventory: task.blocksInventory,
        }))}
      />
    </div>
  </main>;
}
