import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getCurrentUser } from '@/app/actions/getCurrentUser';
import { getDepartmentProjectIds, getMCProjectScopes } from '@/app/libs/projectScope';
import { prisma } from '@/lib/prisma';
import { getLabels } from '@/lib/i18n';
import { getMCManagedUnits } from '@/modules/projects';
import { listOperationalTasks } from '@/modules/ops';
import OperationalTaskQueueClient from '@/components/ops/OperationalTaskQueueClient';

export const dynamic = 'force-dynamic';

export default async function OperationalTasksPage({
  searchParams,
}: { searchParams?: { unitId?: string } }) {
  const user = await getCurrentUser();
  if (!user) redirect('/login?next=/ops/tasks');

  const staffProjectIds = await getDepartmentProjectIds(user, [
    'housekeeping', 'front_desk', 'maintenance', 'guest_care', 'reservations',
  ]);
  let projectIds = user.isAdmin
    ? (await prisma.project.findMany({ select: { id: true } })).map((project) => project.id)
    : [...staffProjectIds];

  const mcScopes = getMCProjectScopes(user);
  projectIds = Array.from(new Set([...projectIds, ...mcScopes.map((scope) => scope.projectId)]));
  if (!projectIds.length) redirect('/');

  const mcManagedUnitIds = new Set<string>();
  for (const scope of mcScopes) {
    const units = await getMCManagedUnits(
      prisma,
      user.identityId,
      scope.projectId,
      scope.organizationId
    );
    for (const unit of units) mcManagedUnitIds.add(unit.id);
  }

  const requestedUnitId =
    typeof searchParams?.unitId === 'string' ? searchParams.unitId : undefined;

  if (
    requestedUnitId &&
    !user.isAdmin &&
    !staffProjectIds.length &&
    !mcManagedUnitIds.has(requestedUnitId)
  ) {
    redirect('/ops/tasks');
  }

  const labels = await getLabels({
    'staff.tasks.back': '← Calendar',
    'staff.tasks.title': 'Housekeeping & readiness',
    'staff.tasks.subtitle': 'Turnover cleaning and inspection tasks generated by checkout. Check-in is blocked while overdue required tasks remain open.',
    'staff.tasks.empty': 'No open readiness tasks.',
    'staff.tasks.update_failed': 'Task update failed',
    'staff.tasks.due': 'Due',
    'staff.tasks.assign_me': 'Assign to me',
    'staff.tasks.start': 'Start',
    'staff.tasks.inspected': 'Inspected',
    'staff.tasks.ready': 'Ready',
  });

  const tasks = await listOperationalTasks(prisma, {
    projectIds,
    unitId: requestedUnitId,
    ...(!user.isAdmin && !staffProjectIds.length
      ? { unitIds: Array.from(mcManagedUnitIds) }
      : {}),
    statuses: ['planned', 'assigned', 'in_progress', 'inspected'],
  });

  return <main className="min-h-screen bg-surface-ivory p-16 md:p-32">
    <div className="mx-auto max-w-5xl">
      <div className="mb-24">
        <Link href="/ops/calendar" className="text-small font-semibold text-brand-andaman hover:underline">{labels['staff.tasks.back']}</Link>
        <h1 className="mt-8 font-display text-display-xl font-semibold text-text-ink">{labels['staff.tasks.title']}</h1>
        <p className="mt-4 text-body text-text-secondary">{labels['staff.tasks.subtitle']}</p>
      </div>
      <OperationalTaskQueueClient
        labels={labels}
        tasks={tasks.map((task) => ({
          ...task,
          dueAt: task.dueAt.toISOString(),
        }))}
      />
    </div>
  </main>;
}
