import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getCurrentUser } from '@/app/actions/getCurrentUser';
import { getDepartmentProjectIds, getMCProjectScopes } from '@/app/libs/projectScope';
import { prisma } from '@/lib/prisma';
import { getLabels } from '@/lib/i18n';
import { getMCManagedUnits } from '@/modules/projects';
import { getOperatingSpaceMembership, getOperatingSpaceUnitIds, listOperationalTasks } from '@/modules/ops';
import OperationalTaskQueueClient from '@/components/ops/OperationalTaskQueueClient';

export const dynamic = 'force-dynamic';

export default async function OperationalTasksPage({
  searchParams,
}: { searchParams?: { unitId?: string; mc?: string; spaceId?: string } }) {
  const user = await getCurrentUser();
  if (!user) redirect('/login?next=/ops/tasks');

  const requestedSpaceId = typeof searchParams?.spaceId === 'string' ? searchParams.spaceId : '';
  const spaceMembership = requestedSpaceId && !user.isAdmin
    ? await getOperatingSpaceMembership(prisma, requestedSpaceId, user.identityId)
    : null;
  if (requestedSpaceId && !user.isAdmin && !spaceMembership?.active) redirect('/ops/spaces');
  const spaceUnitIds = requestedSpaceId
    ? await getOperatingSpaceUnitIds(prisma, requestedSpaceId)
    : [];

  const staffProjectIds = await getDepartmentProjectIds(user, [
    'housekeeping', 'front_desk', 'maintenance', 'guest_care', 'reservations',
  ]);
  const mcScopes = getMCProjectScopes(user);
  if (!user.isAdmin && !staffProjectIds.length && !mcScopes.length) redirect('/');

  const mcManagedUnitIds = new Set<string>();
  for (const scope of mcScopes) {
    const units = await getMCManagedUnits(
      prisma,
      user.identityId,
      scope.projectId,
      scope.organizationId
    );
    for (const unit of units) mcManagedUnitIds.add(unit.id);
  }

  if (!user.isAdmin && !staffProjectIds.length && !mcManagedUnitIds.size) redirect('/');

  const requestedUnitId =
    typeof searchParams?.unitId === 'string' ? searchParams.unitId : undefined;
  const explicitMcMode = searchParams?.mc === '1' && mcScopes.length > 0;

  if (requestedUnitId && !user.isAdmin) {
    const requestedUnit = await prisma.unit.findUnique({
      where: { id: requestedUnitId },
      select: { projectId: true },
    });
    const allowed = explicitMcMode
      ? mcManagedUnitIds.has(requestedUnitId)
      : Boolean(
          requestedUnit &&
          (
            staffProjectIds.includes(requestedUnit.projectId) ||
            mcManagedUnitIds.has(requestedUnitId)
          )
        );
    if (!allowed) redirect(explicitMcMode ? '/ops/tasks?mc=1' : '/ops/tasks');
  }

  const mcOnly = !user.isAdmin && !staffProjectIds.length && mcScopes.length > 0;
  const backHref = explicitMcMode || mcOnly ? '/mc/calendar' : '/ops/calendar';

  const labels = await getLabels({
    'staff.tasks.back': '← Calendar',
    'staff.tasks.title': 'Housekeeping & readiness',
    'staff.tasks.subtitle': 'Turnover cleaning and inspection tasks generated by checkout. Check-in is blocked while overdue required tasks remain open.',
    'staff.tasks.empty': 'No open readiness tasks.',
    'staff.tasks.update_failed': 'Task update failed',
    'staff.tasks.due': 'Due',
    'staff.tasks.assign_me': 'Assign to me',
    'staff.tasks.start': 'Start',
    'staff.tasks.inspected': 'Inspected',
    'staff.tasks.ready': 'Ready',
  });

  const tasks = await listOperationalTasks(prisma, {
    ...(requestedSpaceId
      ? { projectIds: [], unitIds: spaceUnitIds }
      : !user.isAdmin
      ? explicitMcMode
        ? {
            projectIds: [],
            unitIds: Array.from(mcManagedUnitIds),
          }
        : {
            projectIds: staffProjectIds,
            unitIds: Array.from(mcManagedUnitIds),
          }
      : {}),
    unitId: requestedUnitId,
    statuses: ['planned', 'assigned', 'in_progress', 'inspected'],
  });

  return <main className="min-h-screen bg-surface-ivory p-16 md:p-32">
    <div className="mx-auto max-w-5xl">
      <div className="mb-24">
        <Link href={backHref} className="text-small font-semibold text-brand-andaman hover:underline">{labels['staff.tasks.back']}</Link>
        <h1 className="mt-8 font-display text-display-xl font-semibold text-text-ink">{labels['staff.tasks.title']}</h1>
        <p className="mt-4 text-body text-text-secondary">{labels['staff.tasks.subtitle']}</p>
      </div>
      <OperationalTaskQueueClient
        labels={labels}
        tasks={tasks.map((task) => ({
          id: task.id,
          taskType: task.taskType,
          status: task.status,
          dueAt: task.dueAt.toISOString(),
          notes: task.notes,
          project: task.project,
          unit: task.unit,
          assignee: task.assignee,
        }))}
      />
    </div>
  </main>;
}
