-- myUNO — minimal demo data so the deployed app has properties to show.
--
-- Paste into the Supabase SQL editor and run once. Idempotent: every insert
-- skips rows that already exist, so a second run changes nothing.
--
-- What this is NOT: the full staging seed (`npm run db:seed`), which also loads
-- 1237 content keys, 2869 translations, 42 villas, and a walkthrough of
-- bookings, statements and reviews. That one needs a terminal. This is the
-- subset that makes search and booking work when all you have is a browser.
--
-- Content keys are deliberately omitted: the app falls back to English when a
-- key is missing, which is why the deployed page already reads correctly.

BEGIN;

-- Configuration registry (76 parameters). Pricing and booking read these;
-- a missing row returns undefined, which breaks money math quietly.
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'analytics.buyer_signal.long_stay_nights', 'int', '28'::jsonb, NULL, NULL, 'global', 'analytics', 'Nights that make a stay a long_stay signal' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'analytics.buyer_signal.long_stay_nights');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'analytics.buyer_signal.repeat_stay_threshold', 'int', '2'::jsonb, NULL, NULL, 'global', 'analytics', 'Completed stays threshold for repeat_stay signal' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'analytics.buyer_signal.repeat_stay_threshold');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'auth.token_ttl_minutes.account_claim', 'int', '10080'::jsonb, NULL, NULL, 'global', 'auth', 'Account claim token TTL (7 days)' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'auth.token_ttl_minutes.account_claim');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'auth.token_ttl_minutes.email_verify', 'int', '1440'::jsonb, NULL, NULL, 'global', 'auth', 'Email verification token TTL' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'auth.token_ttl_minutes.email_verify');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'auth.token_ttl_minutes.password_reset', 'int', '60'::jsonb, NULL, NULL, 'global', 'auth', 'Password reset token TTL' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'auth.token_ttl_minutes.password_reset');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.cash_due_blocks_checkin', 'boolean', 'true'::jsonb, NULL, NULL, 'project', 'booking', 'Whether check-in is gated on cash being collected' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.cash_due_blocks_checkin');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.checkin_hour', 'int', '15'::jsonb, NULL, NULL, 'unit', 'booking', 'Standard check-in time' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.checkin_hour');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.checkout_hour', 'int', '11'::jsonb, NULL, NULL, 'unit', 'booking', 'Standard check-out time' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.checkout_hour');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.deposit.amount_thb', 'money_thb', '0'::jsonb, NULL, NULL, 'unit', 'booking', 'Pre-auth amount when mode is preauth' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.deposit.amount_thb');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.deposit.mode', 'enum', '"off"'::jsonb, '["off", "preauth"]'::jsonb, NULL, 'unit', 'booking', 'Security deposit handling mode' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.deposit.mode');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.hold_minutes', 'int', '30'::jsonb, NULL, NULL, 'project', 'booking', 'How long an unpaid pending_payment booking blocks the calendar before expiring' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.hold_minutes');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.max_advance_days', 'int', '365'::jsonb, NULL, NULL, 'project', 'booking', 'How far ahead stays can be booked' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.max_advance_days');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.min_nights_default', 'int', '2'::jsonb, NULL, NULL, 'unit', 'booking', 'Default minimum stay for new units' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.min_nights_default');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.payment.cash_receipt_required', 'boolean', 'true'::jsonb, NULL, NULL, 'project', 'booking', 'Require a receipt/чек reference when cash is accepted' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.payment.cash_receipt_required');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.payment.methods_enabled', 'json', '["cash"]'::jsonb, NULL, NULL, 'project', 'booking', 'Which payment methods are offered' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.payment.methods_enabled');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.request_hours', 'int', '24'::jsonb, NULL, NULL, 'project', 'booking', 'Request-to-book: hours the host/ops side has to approve before auto-decline' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.request_hours');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.requests_block_calendar', 'boolean', 'false'::jsonb, NULL, NULL, 'project', 'booking', 'Whether un-answered requests block availability' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.requests_block_calendar');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'booking.same_day_cutoff_hour', 'int', '16'::jsonb, NULL, NULL, 'project', 'booking', 'Latest hour a same-day check-in can be booked' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'booking.same_day_cutoff_hour');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'cancellation.default_policy', 'enum', '"moderate"'::jsonb, '["flexible", "moderate", "strict"]'::jsonb, NULL, 'unit', 'cancellation', 'Default policy for new units' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'cancellation.default_policy');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'cancellation.host_cancel_full_refund', 'boolean', 'true'::jsonb, NULL, NULL, 'global', 'cancellation', 'Platform/host-side cancellation always refunds 100%' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'cancellation.host_cancel_full_refund');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'cancellation.no_show_treated_as', 'enum', '"late_cancel"'::jsonb, '["late_cancel", "forfeit"]'::jsonb, NULL, 'project', 'cancellation', 'No-show refund treatment' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'cancellation.no_show_treated_as');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'cancellation.policy.flexible', 'schedule', '[{"pct": 100, "days": 1}, {"pct": 0, "days": 0}]'::jsonb, NULL, NULL, 'global', 'cancellation', 'Flexible cancellation policy' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'cancellation.policy.flexible');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'cancellation.policy.moderate', 'schedule', '[{"pct": 100, "days": 5}, {"pct": 50, "days": 0}]'::jsonb, NULL, NULL, 'global', 'cancellation', 'Moderate cancellation policy' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'cancellation.policy.moderate');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'cancellation.policy.strict', 'schedule', '[{"pct": 50, "days": 14}, {"pct": 0, "days": 0}]'::jsonb, NULL, NULL, 'global', 'cancellation', 'Strict cancellation policy' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'cancellation.policy.strict');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'catalog.amenities', 'json', '[{"key": "pool", "icon": "waves"}, {"key": "sea_view", "icon": "eye"}, {"key": "gym", "icon": "dumbbell"}, {"key": "parking", "icon": "car"}, {"key": "wifi", "icon": "wifi"}, {"key": "aircon", "icon": "wind"}, {"key": "kitchen", "icon": "utensils"}, {"key": "washer", "icon": "shirt"}, {"key": "workspace", "icon": "laptop"}, {"key": "kids_friendly", "icon": "children"}, {"key": "pets_allowed", "icon": "paw"}, {"key": "security_24h", "icon": "shield"}]'::jsonb, NULL, NULL, 'global', 'catalogs', 'Amenities catalog' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'catalog.amenities');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'catalog.cancellation_policies', 'json', '[{"key": "flexible"}, {"key": "moderate"}, {"key": "strict"}]'::jsonb, NULL, NULL, 'global', 'catalogs', 'Cancellation policies catalog' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'catalog.cancellation_policies');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'catalog.service_categories', 'json', '[{"key": "transfer", "icon": "car"}, {"key": "car_hire", "icon": "car"}, {"key": "cleaning", "icon": "broom"}, {"key": "chef", "icon": "chef"}, {"key": "tours", "icon": "map"}, {"key": "yacht", "icon": "ship"}, {"key": "flowers", "icon": "flower"}, {"key": "water_delivery", "icon": "droplet"}, {"key": "laundry", "icon": "shirt"}, {"key": "babysitting", "icon": "children"}, {"key": "massage_spa", "icon": "spa"}, {"key": "repairs", "icon": "wrench"}, {"key": "emergency_medical", "icon": "plus"}]'::jsonb, NULL, NULL, 'global', 'catalogs', 'Service categories catalog' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'catalog.service_categories');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'catalog.ticket_categories', 'json', '[{"key": "maintenance"}, {"key": "housekeeping"}, {"key": "complaint"}, {"key": "billing_question"}, {"key": "access"}, {"key": "noise"}, {"key": "common_area"}, {"key": "other"}]'::jsonb, NULL, NULL, 'global', 'catalogs', 'Ticket categories catalog' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'catalog.ticket_categories');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'catalog.unit_categories', 'json', '[]'::jsonb, NULL, NULL, 'project', 'catalogs', 'Unit categories (sellable classes like "Superior 2BR") per project: {key, style_key, bedrooms}. Empty = project sells individual units only' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'catalog.unit_categories');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'catalog.unit_types', 'json', '[{"key": "villa"}, {"key": "condo"}, {"key": "townhouse"}]'::jsonb, NULL, NULL, 'global', 'catalogs', 'Unit types catalog' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'catalog.unit_types');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'comms.whatsapp_number', 'string', '""'::jsonb, NULL, NULL, 'project', 'notify', 'WhatsApp number for wa.me concierge deep links (E.164, no spaces). Empty = WhatsApp CTAs hidden' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'comms.whatsapp_number');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'compliance.expiry_warning_days', 'int', '30'::jsonb, NULL, NULL, 'project', 'compliance', 'Days before compliance document expiry to raise an alert' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'compliance.expiry_warning_days');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'compliance.passport_required_hours_before_checkin', 'int', '24'::jsonb, NULL, NULL, 'project', 'compliance', 'Pre-arrival passport deadline' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'compliance.passport_required_hours_before_checkin');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'compliance.tm30_escalation_hours_before', 'int', '6'::jsonb, NULL, NULL, 'global', 'compliance', 'Hours before due_at an unfiled TM30 escalates' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'compliance.tm30_escalation_hours_before');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'compliance.tm30_sla_hours', 'int', '24'::jsonb, NULL, NULL, 'global', 'compliance', 'Legal deadline for TM30 (only tightenable)' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'compliance.tm30_sla_hours');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'engagement.direct.noi_cap_annual_thb', 'money_thb', NULL::jsonb, NULL, NULL, 'global', 'engagement', 'Annual NOI cap for direct-managed units (no default, set per unit)' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'engagement.direct.noi_cap_annual_thb');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'engagement.direct.setup_fee_thb', 'money_thb', '0'::jsonb, NULL, NULL, 'project', 'engagement', 'One-time mobilization/setup fee' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'engagement.direct.setup_fee_thb');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'engagement.owner_direct.booking_fee_pct', 'percent', '10'::jsonb, NULL, NULL, 'project', 'engagement', 'myUNO fee on bookings of owner-direct listings' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'engagement.owner_direct.booking_fee_pct');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'engagement.seasonal_markup_share_pct', 'percent', '100'::jsonb, NULL, NULL, 'project', 'engagement', 'Share of season markup revenue treated as Estate before NOI split' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'engagement.seasonal_markup_share_pct');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'engagement.via_mc.mc_sees_owner_statement', 'boolean', 'false'::jsonb, NULL, NULL, 'project', 'engagement', 'Whether MC staff can view owner statements' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'engagement.via_mc.mc_sees_owner_statement');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'engagement.via_mc.platform_fee_pct', 'percent', '12'::jsonb, NULL, NULL, 'project', 'engagement', 'myUNO platform fee on rental revenue of MC-listed units' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'engagement.via_mc.platform_fee_pct');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'finance.occupancy_tax_pct', 'percent', '0'::jsonb, NULL, NULL, 'project', 'finance', 'Occupancy/local tax line if applicable' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'finance.occupancy_tax_pct');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'finance.payout.default_thb_account', 'string', '"Bank of Ayudhya (Krungsri) 475-1-22131-3 · SWIFT AYUDTHBK"'::jsonb, NULL, NULL, 'global', 'finance', 'Default THB payout account' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'finance.payout.default_thb_account');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'finance.statement.day_of_month', 'int', '5'::jsonb, NULL, NULL, 'global', 'finance', 'Day statements are generated as drafts' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'finance.statement.day_of_month');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'finance.statement.requires_admin_signoff', 'boolean', 'true'::jsonb, NULL, NULL, 'global', 'finance', 'Draft → published requires admin action' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'finance.statement.requires_admin_signoff');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'finance.statement.service_fee_pct', 'percent', '12'::jsonb, NULL, NULL, 'unit', 'finance', 'myUNO service fee on gross bookings, shown as the service_fee line on the owner statement (provisional — founder has not confirmed the rate)' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'finance.statement.service_fee_pct');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'i18n.default_locale', 'enum', '"ru"'::jsonb, '["ru", "en", "th", "zh"]'::jsonb, NULL, 'global', 'i18n', 'New-visitor default language' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'i18n.default_locale');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'messaging.response_sla_hours', 'int', '4'::jsonb, NULL, NULL, 'project', 'services', 'Guest-inquiry response SLA' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'messaging.response_sla_hours');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'notify.channel.email.enabled', 'boolean', 'true'::jsonb, NULL, NULL, 'global', 'notify', 'Email channel enabled' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'notify.channel.email.enabled');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'notify.channel.telegram.enabled', 'boolean', 'false'::jsonb, NULL, NULL, 'global', 'notify', 'Telegram channel enabled' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'notify.channel.telegram.enabled');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'notify.channel.whatsapp.enabled', 'boolean', 'false'::jsonb, NULL, NULL, 'global', 'notify', 'WhatsApp channel enabled' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'notify.channel.whatsapp.enabled');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'notify.prearrival_days_before', 'int', '5'::jsonb, NULL, NULL, 'project', 'notify', 'Days before check-in the pre-arrival reminder (passports + home space link) is sent' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'notify.prearrival_days_before');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'notify.review_prompt_days_after', 'int', '1'::jsonb, NULL, NULL, 'project', 'notify', 'Days after check-out the review prompt (with the green-season offer) is sent' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'notify.review_prompt_days_after');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'owner_stay.charge_cleaning', 'boolean', 'true'::jsonb, NULL, NULL, 'project', 'booking', 'Whether post-owner-stay turnover clean is charged' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'owner_stay.charge_cleaning');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'owner_stay.notice_hours', 'int', '48'::jsonb, NULL, NULL, 'project', 'booking', 'Minimum notice for an owner to book their own unit' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'owner_stay.notice_hours');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'pricing.category_rates', 'schedule', '{}'::jsonb, NULL, NULL, 'project', 'pricing', 'Absolute per-category rates (satang) keyed by season name: {category: {nightly: {season: satang}, monthly: {season: satang}}}. Empty = category pricing off; nights fall back to base × season markup' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'pricing.category_rates');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'pricing.cleaning_fee_thb', 'money_thb', '0'::jsonb, NULL, NULL, 'unit', 'pricing', 'Per-stay cleaning fee' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'pricing.cleaning_fee_thb');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'pricing.early_bird', 'json', '{"pct": 0, "min_days_before": null}'::jsonb, NULL, NULL, 'project', 'pricing', 'Early-bird discount: pct off the nightly subtotal when booked at least min_days_before days ahead. min_days_before null = disabled' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'pricing.early_bird');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'pricing.guest_service_fee_pct', 'percent', '0'::jsonb, NULL, NULL, 'project', 'pricing', 'Optional guest-facing service fee' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'pricing.guest_service_fee_pct');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'pricing.los_discount.monthly_pct', 'percent', '20'::jsonb, NULL, NULL, 'unit', 'pricing', 'Length-of-stay discount for >= 28 nights' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'pricing.los_discount.monthly_pct');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'pricing.los_discount.weekly_pct', 'percent', '5'::jsonb, NULL, NULL, 'unit', 'pricing', 'Length-of-stay discount for >= 7 nights' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'pricing.los_discount.weekly_pct');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'pricing.season.calendar', 'schedule', '[{"to": "01-15", "from": "12-15", "name": "peak", "markup_pct": 60}, {"to": "04-30", "from": "11-01", "name": "high", "markup_pct": 25}, {"to": "06-30", "from": "05-01", "name": "shoulder", "markup_pct": 10}, {"to": "10-31", "from": "07-01", "name": "low", "markup_pct": 0}]'::jsonb, NULL, NULL, 'project,unit', 'pricing', 'Season calendar with named price periods' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'pricing.season.calendar');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'retention.passport_media_days_after_checkout', 'int', '30'::jsonb, NULL, NULL, 'global', 'compliance', 'Auto-deletion deadline for passport images' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'retention.passport_media_days_after_checkout');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'service.accept_sla_hours', 'int', '12'::jsonb, NULL, NULL, 'project', 'cancellation', 'Hours provider has to accept order' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'service.accept_sla_hours');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'service.cancel_window_hours', 'int', '24'::jsonb, NULL, NULL, 'project', 'cancellation', 'Service orders: full refund window' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'service.cancel_window_hours');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'service.provider_no_show_refund_pct', 'percent', '100'::jsonb, NULL, NULL, 'global', 'cancellation', 'Provider no-show refund percentage' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'service.provider_no_show_refund_pct');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'services.advance_notice_hours_default', 'int', '24'::jsonb, NULL, NULL, 'project', 'services', 'Default earliest bookable slot' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'services.advance_notice_hours_default');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'services.payout_period', 'enum', '"weekly"'::jsonb, '["weekly", "biweekly", "monthly"]'::jsonb, NULL, 'global', 'services', 'Provider remittance cadence' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'services.payout_period');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'services.require_admin_approval', 'boolean', 'true'::jsonb, NULL, NULL, 'global', 'services', 'Require admin approval for new/edited services' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'services.require_admin_approval');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'services.take_rate_pct', 'percent', '15'::jsonb, NULL, NULL, 'project', 'services', 'myUNO commission on service orders' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'services.take_rate_pct');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'tickets.auto_close_resolved_days', 'int', '7'::jsonb, NULL, NULL, 'global', 'services', 'Auto-close resolved tickets after N days' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'tickets.auto_close_resolved_days');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'tickets.default_assignee', 'enum', '"project_ops_lead"'::jsonb, '["unassigned", "project_ops_lead"]'::jsonb, NULL, 'project', 'services', 'Auto-assignment target on creation' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'tickets.default_assignee');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'tickets.sla_hours.high', 'int', '24'::jsonb, NULL, NULL, 'project', 'services', 'High priority ticket SLA in hours' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'tickets.sla_hours.high');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'tickets.sla_hours.low', 'int', '168'::jsonb, NULL, NULL, 'project', 'services', 'Low priority ticket SLA in hours' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'tickets.sla_hours.low');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'tickets.sla_hours.normal', 'int', '72'::jsonb, NULL, NULL, 'project', 'services', 'Normal ticket SLA in hours' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'tickets.sla_hours.normal');
INSERT INTO config_parameter (id, created_at, updated_at, key, value_type, default_value, enum_options, json_schema, scopeable_to, group_key, description) SELECT gen_random_uuid()::text, now(), now(), 'tickets.sla_hours.urgent', 'int', '4'::jsonb, NULL, NULL, 'project', 'services', 'Urgent ticket SLA in hours' WHERE NOT EXISTS (SELECT 1 FROM config_parameter WHERE key = 'tickets.sla_hours.urgent');

-- The project -------------------------------------------------------------
INSERT INTO project (id, created_at, updated_at, slug, name, area_label_key, description_key, latitude, longitude, address, timezone, handbook_key, status, default_currency) SELECT '98e2a8de-59d3-440a-90c8-e6f0a497fb1e', now(), now(), 'layantara', 'Layantara Resort', 'project.layantara.area', 'project.layantara.description', 8.010600, 98.296500, 'Bang Tao–Layan, Cherngtalay, Thalang, Phuket', 'Asia/Bangkok', 'project.layantara.handbook', 'live'::"ProjectStatus", 'THB' WHERE NOT EXISTS (SELECT 1 FROM project WHERE slug = 'layantara');

-- Ten villas, live and permitted-use confirmed ------------------------------
INSERT INTO unit (id, created_at, updated_at, project_id, name, unit_type, bedrooms, bathrooms, max_guests, address_supplement, base_nightly_thb, min_nights, instant_book, status, category_key, amenity_keys, permitted_use_confirmed_at, asset_status) SELECT 'ff4900e7-1ead-4074-a6cc-e4f815d2ffd1', now(), now(), '98e2a8de-59d3-440a-90c8-e6f0a497fb1e', 'P1-02', 'villa'::"UnitType", 2, 2, 4, 'P1-02', 547900, 2, false, 'live'::"UnitStatus", 'standard_2br', ARRAY['pool','aircon','wifi','kitchen'], now(), 'managed'::"AssetStatus" WHERE NOT EXISTS (SELECT 1 FROM unit WHERE id = 'ff4900e7-1ead-4074-a6cc-e4f815d2ffd1');
INSERT INTO unit (id, created_at, updated_at, project_id, name, unit_type, bedrooms, bathrooms, max_guests, address_supplement, base_nightly_thb, min_nights, instant_book, status, category_key, amenity_keys, permitted_use_confirmed_at, asset_status) SELECT '9a387be8-e321-4cf2-9c08-03b40c131907', now(), now(), '98e2a8de-59d3-440a-90c8-e6f0a497fb1e', 'P1-01', 'villa'::"UnitType", 2, 2, 4, 'P1-01', 547900, 2, false, 'live'::"UnitStatus", 'standard_2br', ARRAY['pool','aircon','wifi','kitchen'], now(), 'managed'::"AssetStatus" WHERE NOT EXISTS (SELECT 1 FROM unit WHERE id = '9a387be8-e321-4cf2-9c08-03b40c131907');
INSERT INTO unit (id, created_at, updated_at, project_id, name, unit_type, bedrooms, bathrooms, max_guests, address_supplement, base_nightly_thb, min_nights, instant_book, status, category_key, amenity_keys, permitted_use_confirmed_at, asset_status) SELECT '87cb2d3d-a0cb-48fe-b4da-dc675e997828', now(), now(), '98e2a8de-59d3-440a-90c8-e6f0a497fb1e', 'P2-07', 'villa'::"UnitType", 2, 2, 4, 'P2-07', 626100, 2, false, 'live'::"UnitStatus", 'superior_2br', ARRAY['pool','aircon','wifi','kitchen'], now(), 'managed'::"AssetStatus" WHERE NOT EXISTS (SELECT 1 FROM unit WHERE id = '87cb2d3d-a0cb-48fe-b4da-dc675e997828');
INSERT INTO unit (id, created_at, updated_at, project_id, name, unit_type, bedrooms, bathrooms, max_guests, address_supplement, base_nightly_thb, min_nights, instant_book, status, category_key, amenity_keys, permitted_use_confirmed_at, asset_status) SELECT '393f8650-e9f4-4350-871c-ecc66bd2228b', now(), now(), '98e2a8de-59d3-440a-90c8-e6f0a497fb1e', 'P2-05', 'villa'::"UnitType", 2, 2, 4, 'P2-05', 626100, 2, false, 'live'::"UnitStatus", 'superior_2br', ARRAY['pool','aircon','wifi','kitchen'], now(), 'managed'::"AssetStatus" WHERE NOT EXISTS (SELECT 1 FROM unit WHERE id = '393f8650-e9f4-4350-871c-ecc66bd2228b');
INSERT INTO unit (id, created_at, updated_at, project_id, name, unit_type, bedrooms, bathrooms, max_guests, address_supplement, base_nightly_thb, min_nights, instant_book, status, category_key, amenity_keys, permitted_use_confirmed_at, asset_status) SELECT '1358c437-7de2-44bc-bcaa-a042692d4679', now(), now(), '98e2a8de-59d3-440a-90c8-e6f0a497fb1e', 'P2-02', 'villa'::"UnitType", 2, 2, 4, 'P2-02', 626100, 2, false, 'live'::"UnitStatus", 'superior_2br', ARRAY['pool','aircon','wifi','kitchen'], now(), 'managed'::"AssetStatus" WHERE NOT EXISTS (SELECT 1 FROM unit WHERE id = '1358c437-7de2-44bc-bcaa-a042692d4679');
INSERT INTO unit (id, created_at, updated_at, project_id, name, unit_type, bedrooms, bathrooms, max_guests, address_supplement, base_nightly_thb, min_nights, instant_book, status, category_key, amenity_keys, permitted_use_confirmed_at, asset_status) SELECT '953b89a3-3244-47d6-bdc7-8a6b17868bac', now(), now(), '98e2a8de-59d3-440a-90c8-e6f0a497fb1e', 'P2-01', 'villa'::"UnitType", 2, 2, 4, 'P2-01', 626100, 2, false, 'live'::"UnitStatus", 'superior_2br', ARRAY['pool','aircon','wifi','kitchen'], now(), 'managed'::"AssetStatus" WHERE NOT EXISTS (SELECT 1 FROM unit WHERE id = '953b89a3-3244-47d6-bdc7-8a6b17868bac');
INSERT INTO unit (id, created_at, updated_at, project_id, name, unit_type, bedrooms, bathrooms, max_guests, address_supplement, base_nightly_thb, min_nights, instant_book, status, category_key, amenity_keys, permitted_use_confirmed_at, asset_status) SELECT '5572b1cf-d09d-4904-ab0b-74e45ef5a9fb', now(), now(), '98e2a8de-59d3-440a-90c8-e6f0a497fb1e', 'P2-03', 'villa'::"UnitType", 2, 2, 4, 'P2-03', 626100, 2, false, 'live'::"UnitStatus", 'superior_2br', ARRAY['pool','aircon','wifi','kitchen'], now(), 'managed'::"AssetStatus" WHERE NOT EXISTS (SELECT 1 FROM unit WHERE id = '5572b1cf-d09d-4904-ab0b-74e45ef5a9fb');
INSERT INTO unit (id, created_at, updated_at, project_id, name, unit_type, bedrooms, bathrooms, max_guests, address_supplement, base_nightly_thb, min_nights, instant_book, status, category_key, amenity_keys, permitted_use_confirmed_at, asset_status) SELECT '45ee25a5-29a2-403c-9eb0-d7ce648d21de', now(), now(), '98e2a8de-59d3-440a-90c8-e6f0a497fb1e', 'P2-04', 'villa'::"UnitType", 2, 2, 4, 'P2-04', 626100, 2, false, 'live'::"UnitStatus", 'superior_2br', ARRAY['pool','aircon','wifi','kitchen'], now(), 'managed'::"AssetStatus" WHERE NOT EXISTS (SELECT 1 FROM unit WHERE id = '45ee25a5-29a2-403c-9eb0-d7ce648d21de');
INSERT INTO unit (id, created_at, updated_at, project_id, name, unit_type, bedrooms, bathrooms, max_guests, address_supplement, base_nightly_thb, min_nights, instant_book, status, category_key, amenity_keys, permitted_use_confirmed_at, asset_status) SELECT '495960e3-be94-418e-af96-fbb23462c3e1', now(), now(), '98e2a8de-59d3-440a-90c8-e6f0a497fb1e', 'P2-06', 'villa'::"UnitType", 2, 2, 4, 'P2-06', 626100, 2, false, 'live'::"UnitStatus", 'superior_2br', ARRAY['pool','aircon','wifi','kitchen'], now(), 'managed'::"AssetStatus" WHERE NOT EXISTS (SELECT 1 FROM unit WHERE id = '495960e3-be94-418e-af96-fbb23462c3e1');
INSERT INTO unit (id, created_at, updated_at, project_id, name, unit_type, bedrooms, bathrooms, max_guests, address_supplement, base_nightly_thb, min_nights, instant_book, status, category_key, amenity_keys, permitted_use_confirmed_at, asset_status) SELECT 'a179f361-275f-49d2-ba04-af6ecbfa1d5a', now(), now(), '98e2a8de-59d3-440a-90c8-e6f0a497fb1e', 'P2-08', 'villa'::"UnitType", 2, 2, 4, 'P2-08', 626100, 2, false, 'live'::"UnitStatus", 'superior_2br', ARRAY['pool','aircon','wifi','kitchen'], now(), 'managed'::"AssetStatus" WHERE NOT EXISTS (SELECT 1 FROM unit WHERE id = 'a179f361-275f-49d2-ba04-af6ecbfa1d5a');

COMMIT;

SELECT (SELECT count(*) FROM unit WHERE status='live')     AS live_villas,
       (SELECT count(*) FROM project WHERE status='live')  AS live_projects,
       (SELECT count(*) FROM config_parameter)             AS config_parameters;
