/** Agent / Distribution OS: draft translations for EN/RU/TH. */
export const AGENT_DISTRIBUTION_KEYS = [
  { key:'agent.common.back_workspace',namespace:'agent',description:'Back to agent workspace',en:'← Agent workspace',ru:'← Рабочее место агента',th:'← พื้นที่ทำงานเอเจนต์',status:'needs_review' as const },
  { key:'agent.common.back_inventory',namespace:'agent',description:'Back to inventory',en:'← Inventory',ru:'← Инвентарь',th:'← อินเวนทอรี',status:'needs_review' as const },
  { key:'agent.common.client',namespace:'agent',description:'Client label',en:'Client',ru:'Клиент',th:'ลูกค้า',status:'needs_review' as const },
  { key:'agent.common.no_client',namespace:'agent',description:'No protected client option',en:'No protected client',ru:'Без защищённого клиента',th:'ไม่มีลูกค้าที่ลงทะเบียน',status:'needs_review' as const },
  { key:'agent.common.brand',namespace:'agent',description:'Brand mode label',en:'Brand',ru:'Брендинг',th:'แบรนด์',status:'needs_review' as const },
  { key:'agent.common.brand.myuno',namespace:'agent',description:'myUNO brand mode',en:'myUNO',ru:'myUNO',th:'myUNO',status:'needs_review' as const },
  { key:'agent.common.brand.cobranded',namespace:'agent',description:'Co-branded mode',en:'Co-branded',ru:'Совместный бренд',th:'แบรนด์ร่วม',status:'needs_review' as const },
  { key:'agent.common.brand.agent',namespace:'agent',description:'Agent branded mode',en:'Agent branded',ru:'Бренд агента',th:'แบรนด์เอเจนต์',status:'needs_review' as const },
  { key:'agent.common.brand.neutral',namespace:'agent',description:'Neutral brand mode',en:'Neutral',ru:'Нейтральный',th:'ไม่ระบุแบรนด์',status:'needs_review' as const },
  { key:'agent.common.whatsapp_share',namespace:'agent',description:'WhatsApp share action',en:'Share in WhatsApp',ru:'Отправить в WhatsApp',th:'แชร์ใน WhatsApp',status:'needs_review' as const },
  { key:'agent.common.bedrooms_short',namespace:'agent',description:'Bedrooms short label',en:'BR',ru:'сп.',th:'ห้องนอน',status:'needs_review' as const },
  { key:'agent.common.bathrooms_short',namespace:'agent',description:'Bathrooms short label',en:'BA',ru:'ван.',th:'ห้องน้ำ',status:'needs_review' as const },

  { key:'agent.client_form.name',namespace:'agent',description:'Client name input',en:'Client name',ru:'Имя клиента',th:'ชื่อลูกค้า',status:'needs_review' as const },
  { key:'agent.client_form.whatsapp',namespace:'agent',description:'WhatsApp input',en:'WhatsApp',ru:'WhatsApp',th:'WhatsApp',status:'needs_review' as const },
  { key:'agent.client_form.phone',namespace:'agent',description:'Phone input',en:'Phone',ru:'Телефон',th:'โทรศัพท์',status:'needs_review' as const },
  { key:'agent.client_form.scope.all',namespace:'agent',description:'All transaction scopes',en:'All',ru:'Все',th:'ทั้งหมด',status:'needs_review' as const },
  { key:'agent.client_form.scope.stay',namespace:'agent',description:'Stay transaction scope',en:'Stay',ru:'Проживание',th:'เข้าพัก',status:'needs_review' as const },
  { key:'agent.client_form.scope.long_rent',namespace:'agent',description:'Long rent transaction scope',en:'Long rent',ru:'Долгосрочная аренда',th:'เช่าระยะยาว',status:'needs_review' as const },
  { key:'agent.client_form.scope.buy',namespace:'agent',description:'Buy transaction scope',en:'Buy',ru:'Покупка',th:'ซื้อ',status:'needs_review' as const },
  { key:'agent.client_form.protect',namespace:'agent',description:'Protect client action',en:'Protect',ru:'Зарегистрировать',th:'ลงทะเบียนลูกค้า',status:'needs_review' as const },

  { key:'agent.quote.new_title',namespace:'agent',description:'Create quote title',en:'Create quote',ru:'Создать предложение',th:'สร้างใบเสนอราคา',status:'needs_review' as const },
  { key:'agent.quote.checkin',namespace:'agent',description:'Quote check-in',en:'Check-in',ru:'Заезд',th:'เช็กอิน',status:'needs_review' as const },
  { key:'agent.quote.checkout',namespace:'agent',description:'Quote check-out',en:'Check-out',ru:'Выезд',th:'เช็กเอาต์',status:'needs_review' as const },
  { key:'agent.quote.adults',namespace:'agent',description:'Adults label',en:'Adults',ru:'Взрослые',th:'ผู้ใหญ่',status:'needs_review' as const },
  { key:'agent.quote.children',namespace:'agent',description:'Children label',en:'Children',ru:'Дети',th:'เด็ก',status:'needs_review' as const },
  { key:'agent.quote.markup',namespace:'agent',description:'Agent markup label',en:'Markup THB',ru:'Наценка THB',th:'มาร์กอัป THB',status:'needs_review' as const },
  { key:'agent.quote.discount',namespace:'agent',description:'Discount label',en:'Discount THB',ru:'Скидка THB',th:'ส่วนลด THB',status:'needs_review' as const },
  { key:'agent.quote.commission',namespace:'agent',description:'Commission percentage',en:'Commission %',ru:'Комиссия %',th:'คอมมิชชั่น %',status:'needs_review' as const },
  { key:'agent.quote.valid_hours',namespace:'agent',description:'Quote validity hours',en:'Valid hours',ru:'Срок действия, часов',th:'อายุใบเสนอราคา (ชม.)',status:'needs_review' as const },
  { key:'agent.quote.public_note',namespace:'agent',description:'Client note placeholder',en:'Client note',ru:'Комментарий для клиента',th:'หมายเหตุถึงลูกค้า',status:'needs_review' as const },
  { key:'agent.quote.create_share',namespace:'agent',description:'Create and share quote',en:'Create & share',ru:'Создать и отправить',th:'สร้างและแชร์',status:'needs_review' as const },
  { key:'agent.quote.creating',namespace:'agent',description:'Quote creating state',en:'Creating…',ru:'Создание…',th:'กำลังสร้าง…',status:'needs_review' as const },

  { key:'agent.shortlist.title_label',namespace:'agent',description:'Shortlist title field',en:'Title',ru:'Название',th:'ชื่อ',status:'needs_review' as const },
  { key:'agent.shortlist.default_title',namespace:'agent',description:'Default shortlist title',en:'Property shortlist',ru:'Подборка объектов',th:'รายการอสังหาริมทรัพย์',status:'needs_review' as const },
  { key:'agent.shortlist.notes',namespace:'agent',description:'Shortlist notes',en:'Notes',ru:'Заметки',th:'หมายเหตุ',status:'needs_review' as const },
  { key:'agent.shortlist.search',namespace:'agent',description:'Shortlist inventory search',en:'Search inventory',ru:'Поиск по инвентарю',th:'ค้นหาอินเวนทอรี',status:'needs_review' as const },
  { key:'agent.shortlist.selected',namespace:'agent',description:'Selected item suffix',en:'selected',ru:'выбрано',th:'เลือกแล้ว',status:'needs_review' as const },
  { key:'agent.shortlist.create_share',namespace:'agent',description:'Create and share shortlist',en:'Create & share',ru:'Создать и отправить',th:'สร้างและแชร์',status:'needs_review' as const },
  { key:'agent.shortlist.creating',namespace:'agent',description:'Shortlist creating state',en:'Creating…',ru:'Создание…',th:'กำลังสร้าง…',status:'needs_review' as const },
  { key:'agent.shortlist.page_title',namespace:'agent',description:'Shortlists page title',en:'Shortlists',ru:'Подборки',th:'รายการคัดเลือก',status:'needs_review' as const },
  { key:'agent.shortlist.new',namespace:'agent',description:'New shortlist action',en:'New shortlist',ru:'Новая подборка',th:'สร้างรายการใหม่',status:'needs_review' as const },
  { key:'agent.shortlist.new_title',namespace:'agent',description:'Create shortlist page title',en:'Create shortlist',ru:'Создать подборку',th:'สร้างรายการคัดเลือก',status:'needs_review' as const },
  { key:'agent.shortlist.properties',namespace:'agent',description:'Properties count suffix',en:'properties',ru:'объектов',th:'รายการ',status:'needs_review' as const },

  { key:'agent.commissions.title',namespace:'agent',description:'Agent commissions title',en:'Commissions',ru:'Комиссии',th:'คอมมิชชั่น',status:'needs_review' as const },
  { key:'agent.commissions.rate',namespace:'agent',description:'Commission rate',en:'Rate',ru:'Ставка',th:'อัตรา',status:'needs_review' as const },
  { key:'agent.commissions.amount',namespace:'agent',description:'Commission amount',en:'Amount',ru:'Сумма',th:'จำนวน',status:'needs_review' as const },
  { key:'agent.commissions.status',namespace:'agent',description:'Commission status',en:'Status',ru:'Статус',th:'สถานะ',status:'needs_review' as const },

  { key:'agent.share.client_total',namespace:'agent',description:'Public quote client total',en:'Client total',ru:'Итого для клиента',th:'ยอดรวมลูกค้า',status:'needs_review' as const },
  { key:'agent.share.availability',namespace:'agent',description:'Public quote availability',en:'Availability',ru:'Доступность',th:'สถานะว่าง',status:'needs_review' as const },
  { key:'agent.share.valid_until',namespace:'agent',description:'Public quote validity',en:'Valid until',ru:'Действует до',th:'ใช้ได้ถึง',status:'needs_review' as const },
  { key:'agent.share.view_property',namespace:'agent',description:'Public view property action',en:'View property',ru:'Посмотреть объект',th:'ดูอสังหาริมทรัพย์',status:'needs_review' as const },
  { key:'agent.share.selection_kicker',namespace:'agent',description:'Neutral selection kicker',en:'PROPERTY SELECTION',ru:'ПОДБОРКА ОБЪЕКТОВ',th:'รายการอสังหาริมทรัพย์',status:'needs_review' as const },
  { key:'agent.share.quote_title',namespace:'agent',description:'Fallback quote title',en:'Property quote',ru:'Предложение по объекту',th:'ใบเสนอราคาอสังหาริมทรัพย์',status:'needs_review' as const },
];
