/** Agent / Distribution OS: draft translations for EN/RU/TH. */
export const AGENT_DISTRIBUTION_KEYS = [
  { key:'agent.common.back_workspace',namespace:'agent',description:'Back to agent workspace',en:'← Agent workspace',ru:'← Рабочее место агента',th:'← พื้นที่ทำงานเอเจนต์',status:'needs_review' as const },
  { key:'agent.common.back_inventory',namespace:'agent',description:'Back to inventory',en:'← Inventory',ru:'← Инвентарь',th:'← อินเวนทอรี',status:'needs_review' as const },
  { key:'agent.common.client',namespace:'agent',description:'Client label',en:'Client',ru:'Клиент',th:'ลูกค้า',status:'needs_review' as const },
  { key:'agent.common.no_client',namespace:'agent',description:'No protected client option',en:'No protected client',ru:'Без защищённого клиента',th:'ไม่มีลูกค้าที่ลงทะเบียน',status:'needs_review' as const },
  { key:'agent.common.brand',namespace:'agent',description:'Brand mode label',en:'Brand',ru:'Брендинг',th:'แบรนด์',status:'needs_review' as const },
  { key:'agent.common.brand.myuno',namespace:'agent',description:'myUNO brand mode',en:'myUNO',ru:'myUNO',th:'myUNO',status:'needs_review' as const },
  { key:'agent.common.brand.cobranded',namespace:'agent',description:'Co-branded mode',en:'Co-branded',ru:'Совместный бренд',th:'แบรนด์ร่วม',status:'needs_review' as const },
  { key:'agent.common.brand.agent',namespace:'agent',description:'Agent branded mode',en:'Agent branded',ru:'Бренд агента',th:'แบรนด์เอเจนต์',status:'needs_review' as const },
  { key:'agent.common.brand.neutral',namespace:'agent',description:'Neutral brand mode',en:'Neutral',ru:'Нейтральный',th:'ไม่ระบุแบรนด์',status:'needs_review' as const },
  { key:'agent.common.whatsapp_share',namespace:'agent',description:'WhatsApp share action',en:'Share in WhatsApp',ru:'Отправить в WhatsApp',th:'แชร์ใน WhatsApp',status:'needs_review' as const },
  { key:'agent.common.bedrooms_short',namespace:'agent',description:'Bedrooms short label',en:'BR',ru:'сп.',th:'ห้องนอน',status:'needs_review' as const },
  { key:'agent.common.bathrooms_short',namespace:'agent',description:'Bathrooms short label',en:'BA',ru:'ван.',th:'ห้องน้ำ',status:'needs_review' as const },

  { key:'agent.client_form.name',namespace:'agent',description:'Client name input',en:'Client name',ru:'Имя клиента',th:'ชื่อลูกค้า',status:'needs_review' as const },
  { key:'agent.client_form.whatsapp',namespace:'agent',description:'WhatsApp input',en:'WhatsApp',ru:'WhatsApp',th:'WhatsApp',status:'needs_review' as const },
  { key:'agent.client_form.phone',namespace:'agent',description:'Phone input',en:'Phone',ru:'Телефон',th:'โทรศัพท์',status:'needs_review' as const },
  { key:'agent.client_form.scope.all',namespace:'agent',description:'All transaction scopes',en:'All',ru:'Все',th:'ทั้งหมด',status:'needs_review' as const },
  { key:'agent.client_form.scope.stay',namespace:'agent',description:'Stay transaction scope',en:'Stay',ru:'Проживание',th:'เข้าพัก',status:'needs_review' as const },
  { key:'agent.client_form.scope.long_rent',namespace:'agent',description:'Long rent transaction scope',en:'Long rent',ru:'Долгосрочная аренда',th:'เช่าระยะยาว',status:'needs_review' as const },
  { key:'agent.client_form.scope.buy',namespace:'agent',description:'Buy transaction scope',en:'Buy',ru:'Покупка',th:'ซื้อ',status:'needs_review' as const },
  { key:'agent.client_form.protect',namespace:'agent',description:'Protect client action',en:'Protect',ru:'Зарегистрировать',th:'ลงทะเบียนลูกค้า',status:'needs_review' as const },

  { key:'agent.quote.new_title',namespace:'agent',description:'Create quote title',en:'Create quote',ru:'Создать предложение',th:'สร้างใบเสนอราคา',status:'needs_review' as const },
  { key:'agent.quote.checkin',namespace:'agent',description:'Quote check-in',en:'Check-in',ru:'Заезд',th:'เช็กอิน',status:'needs_review' as const },
  { key:'agent.quote.checkout',namespace:'agent',description:'Quote check-out',en:'Check-out',ru:'Выезд',th:'เช็กเอาต์',status:'needs_review' as const },
  { key:'agent.quote.adults',namespace:'agent',description:'Adults label',en:'Adults',ru:'Взрослые',th:'ผู้ใหญ่',status:'needs_review' as const },
  { key:'agent.quote.children',namespace:'agent',description:'Children label',en:'Children',ru:'Дети',th:'เด็ก',status:'needs_review' as const },
  { key:'agent.quote.markup',namespace:'agent',description:'Agent markup label',en:'Markup THB',ru:'Наценка THB',th:'มาร์กอัป THB',status:'needs_review' as const },
  { key:'agent.quote.discount',namespace:'agent',description:'Discount label',en:'Discount THB',ru:'Скидка THB',th:'ส่วนลด THB',status:'needs_review' as const },
  { key:'agent.quote.commission',namespace:'agent',description:'Commission percentage',en:'Commission %',ru:'Комиссия %',th:'คอมมิชชั่น %',status:'needs_review' as const },
  { key:'agent.quote.valid_hours',namespace:'agent',description:'Quote validity hours',en:'Valid hours',ru:'Срок действия, часов',th:'อายุใบเสนอราคา (ชม.)',status:'needs_review' as const },
  { key:'agent.quote.public_note',namespace:'agent',description:'Client note placeholder',en:'Client note',ru:'Комментарий для клиента',th:'หมายเหตุถึงลูกค้า',status:'needs_review' as const },
  { key:'agent.quote.create_share',namespace:'agent',description:'Create and share quote',en:'Create & share',ru:'Создать и отправить',th:'สร้างและแชร์',status:'needs_review' as const },
  { key:'agent.quote.creating',namespace:'agent',description:'Quote creating state',en:'Creating…',ru:'Создание…',th:'กำลังสร้าง…',status:'needs_review' as const },

  { key:'agent.shortlist.title_label',namespace:'agent',description:'Shortlist title field',en:'Title',ru:'Название',th:'ชื่อ',status:'needs_review' as const },
  { key:'agent.shortlist.default_title',namespace:'agent',description:'Default shortlist title',en:'Property shortlist',ru:'Подборка объектов',th:'รายการอสังหาริมทรัพย์',status:'needs_review' as const },
  { key:'agent.shortlist.notes',namespace:'agent',description:'Shortlist notes',en:'Notes',ru:'Заметки',th:'หมายเหตุ',status:'needs_review' as const },
  { key:'agent.shortlist.search',namespace:'agent',description:'Shortlist inventory search',en:'Search inventory',ru:'Поиск по инвентарю',th:'ค้นหาอินเวนทอรี',status:'needs_review' as const },
  { key:'agent.shortlist.selected',namespace:'agent',description:'Selected item suffix',en:'selected',ru:'выбрано',th:'เลือกแล้ว',status:'needs_review' as const },
  { key:'agent.shortlist.create_share',namespace:'agent',description:'Create and share shortlist',en:'Create & share',ru:'Создать и отправить',th:'สร้างและแชร์',status:'needs_review' as const },
  { key:'agent.shortlist.creating',namespace:'agent',description:'Shortlist creating state',en:'Creating…',ru:'Создание…',th:'กำลังสร้าง…',status:'needs_review' as const },
  { key:'agent.shortlist.page_title',namespace:'agent',description:'Shortlists page title',en:'Shortlists',ru:'Подборки',th:'รายการคัดเลือก',status:'needs_review' as const },
  { key:'agent.shortlist.new',namespace:'agent',description:'New shortlist action',en:'New shortlist',ru:'Новая подборка',th:'สร้างรายการใหม่',status:'needs_review' as const },
  { key:'agent.shortlist.new_title',namespace:'agent',description:'Create shortlist page title',en:'Create shortlist',ru:'Создать подборку',th:'สร้างรายการคัดเลือก',status:'needs_review' as const },
  { key:'agent.shortlist.properties',namespace:'agent',description:'Properties count suffix',en:'properties',ru:'объектов',th:'รายการ',status:'needs_review' as const },

  { key:'agent.commissions.title',namespace:'agent',description:'Agent commissions title',en:'Commissions',ru:'Комиссии',th:'คอมมิชชั่น',status:'needs_review' as const },
  { key:'agent.commissions.rate',namespace:'agent',description:'Commission rate',en:'Rate',ru:'Ставка',th:'อัตรา',status:'needs_review' as const },
  { key:'agent.commissions.amount',namespace:'agent',description:'Commission amount',en:'Amount',ru:'Сумма',th:'จำนวน',status:'needs_review' as const },
  { key:'agent.commissions.status',namespace:'agent',description:'Commission status',en:'Status',ru:'Статус',th:'สถานะ',status:'needs_review' as const },

  { key:'agent.share.client_total',namespace:'agent',description:'Public quote client total',en:'Client total',ru:'Итого для клиента',th:'ยอดรวมลูกค้า',status:'needs_review' as const },
  { key:'agent.share.availability',namespace:'agent',description:'Public quote availability',en:'Availability',ru:'Доступность',th:'สถานะว่าง',status:'needs_review' as const },
  { key:'agent.share.valid_until',namespace:'agent',description:'Public quote validity',en:'Valid until',ru:'Действует до',th:'ใช้ได้ถึง',status:'needs_review' as const },
  { key:'agent.share.view_property',namespace:'agent',description:'Public view property action',en:'View property',ru:'Посмотреть объект',th:'ดูอสังหาริมทรัพย์',status:'needs_review' as const },
  { key:'agent.share.selection_kicker',namespace:'agent',description:'Neutral selection kicker',en:'PROPERTY SELECTION',ru:'ПОДБОРКА ОБЪЕКТОВ',th:'รายการอสังหาริมทรัพย์',status:'needs_review' as const },
  { key:'agent.share.quote_title',namespace:'agent',description:'Fallback quote title',en:'Property quote',ru:'Предложение по объекту',th:'ใบเสนอราคาอสังหาริมทรัพย์',status:'needs_review' as const },

  { key:'agent.home.kicker',namespace:'agent',description:'Agent workspace kicker',en:'AGENT WORKSPACE',ru:'РАБОЧЕЕ МЕСТО АГЕНТА',th:'พื้นที่ทำงานเอเจนต์',status:'needs_review' as const },
  { key:'agent.home.title',namespace:'agent',description:'Agent workspace title',en:'Distribution workspace',ru:'Рабочее место дистрибуции',th:'พื้นที่งานจัดจำหน่าย',status:'needs_review' as const },
  { key:'agent.home.subtitle',namespace:'agent',description:'Agent workspace subtitle',en:'Search inventory, protect clients, create quotes, share selections and track commission.',ru:'Ищите объекты, регистрируйте клиентов, создавайте предложения, отправляйте подборки и отслеживайте комиссию.',th:'ค้นหาอินเวนทอรี ลงทะเบียนลูกค้า สร้างใบเสนอราคา แชร์รายการ และติดตามคอมมิชชั่น',status:'needs_review' as const },
  { key:'agent.home.inventory',namespace:'agent',description:'Agent inventory action',en:'Inventory',ru:'Инвентарь',th:'อินเวนทอรี',status:'needs_review' as const },
  { key:'agent.home.clients',namespace:'agent',description:'Protected clients metric',en:'Protected clients',ru:'Защищённые клиенты',th:'ลูกค้าที่ลงทะเบียน',status:'needs_review' as const },
  { key:'agent.home.shortlists',namespace:'agent',description:'Shortlists metric',en:'Shortlists',ru:'Подборки',th:'รายการคัดเลือก',status:'needs_review' as const },
  { key:'agent.home.quotes',namespace:'agent',description:'Open quotes metric',en:'Open quotes',ru:'Открытые предложения',th:'ใบเสนอราคาที่เปิดอยู่',status:'needs_review' as const },
  { key:'agent.home.commissions',namespace:'agent',description:'Open commissions metric',en:'Open commissions',ru:'Открытые комиссии',th:'คอมมิชชั่นค้างอยู่',status:'needs_review' as const },
  { key:'agent.home.commission_value',namespace:'agent',description:'Commission value metric',en:'Commission value',ru:'Сумма комиссии',th:'มูลค่าคอมมิชชั่น',status:'needs_review' as const },
  { key:'agent.home.open',namespace:'agent',description:'Open workspace item',en:'Open →',ru:'Открыть →',th:'เปิด →',status:'needs_review' as const },

  { key:'agent.inventory.back',namespace:'agent',description:'Inventory back link',en:'← Agent workspace',ru:'← Рабочее место агента',th:'← พื้นที่ทำงานเอเจนต์',status:'needs_review' as const },
  { key:'agent.inventory.title',namespace:'agent',description:'Inventory page title',en:'Inventory',ru:'Инвентарь',th:'อินเวนทอรี',status:'needs_review' as const },
  { key:'agent.inventory.subtitle',namespace:'agent',description:'Inventory page subtitle',en:'One canonical inventory for agent distribution.',ru:'Единый канонический инвентарь для агентской дистрибуции.',th:'อินเวนทอรีหลักชุดเดียวสำหรับการจัดจำหน่ายผ่านเอเจนต์',status:'needs_review' as const },
  { key:'agent.inventory.search',namespace:'agent',description:'Inventory search',en:'Search project or home',ru:'Найти проект или объект',th:'ค้นหาโครงการหรือบ้าน',status:'needs_review' as const },
  { key:'agent.inventory.stay',namespace:'agent',description:'Stay mode',en:'Stay',ru:'Проживание',th:'เข้าพัก',status:'needs_review' as const },
  { key:'agent.inventory.rent',namespace:'agent',description:'Long rent mode',en:'Long rent',ru:'Долгосрочная аренда',th:'เช่าระยะยาว',status:'needs_review' as const },
  { key:'agent.inventory.buy',namespace:'agent',description:'Buy mode',en:'Buy',ru:'Покупка',th:'ซื้อ',status:'needs_review' as const },
  { key:'agent.inventory.instant',namespace:'agent',description:'Instant availability badge',en:'Instant',ru:'Мгновенно',th:'ยืนยันทันที',status:'needs_review' as const },
  { key:'agent.inventory.request',namespace:'agent',description:'Request availability badge',en:'Request',ru:'По запросу',th:'ตามคำขอ',status:'needs_review' as const },
  { key:'agent.inventory.quote',namespace:'agent',description:'Create quote action',en:'Create quote',ru:'Создать предложение',th:'สร้างใบเสนอราคา',status:'needs_review' as const },
  { key:'agent.inventory.add_shortlist',namespace:'agent',description:'Add to shortlist action',en:'Add to shortlist',ru:'В подборку',th:'เพิ่มในรายการคัดเลือก',status:'needs_review' as const },
  { key:'agent.inventory.empty',namespace:'agent',description:'No inventory state',en:'No distributable inventory matches this search.',ru:'По этому запросу нет доступного для дистрибуции инвентаря.',th:'ไม่พบอินเวนทอรีที่จัดจำหน่ายได้ตามการค้นหานี้',status:'needs_review' as const },

  { key:'agent.clients.back',namespace:'agent',description:'Clients back link',en:'← Agent workspace',ru:'← Рабочее место агента',th:'← พื้นที่ทำงานเอเจนต์',status:'needs_review' as const },
  { key:'agent.clients.title',namespace:'agent',description:'Protected clients title',en:'Protected clients',ru:'Защищённые клиенты',th:'ลูกค้าที่ลงทะเบียน',status:'needs_review' as const },
  { key:'agent.clients.subtitle',namespace:'agent',description:'Protected clients subtitle',en:'Register the client before sharing inventory or creating a transaction.',ru:'Зарегистрируйте клиента до отправки инвентаря или создания сделки.',th:'ลงทะเบียนลูกค้าก่อนแชร์อินเวนทอรีหรือสร้างธุรกรรม',status:'needs_review' as const },
  { key:'agent.clients.name',namespace:'agent',description:'Client name column',en:'Client',ru:'Клиент',th:'ลูกค้า',status:'needs_review' as const },
  { key:'agent.clients.contact',namespace:'agent',description:'Client contact column',en:'Contact',ru:'Контакт',th:'ติดต่อ',status:'needs_review' as const },
  { key:'agent.clients.scope',namespace:'agent',description:'Client protection scope column',en:'Scope',ru:'Область защиты',th:'ขอบเขต',status:'needs_review' as const },
  { key:'agent.clients.expires',namespace:'agent',description:'Client protection expiry column',en:'Protected until',ru:'Защита до',th:'คุ้มครองถึง',status:'needs_review' as const },
  { key:'agent.clients.empty',namespace:'agent',description:'No protected clients state',en:'No protected clients yet.',ru:'Защищённых клиентов пока нет.',th:'ยังไม่มีลูกค้าที่ลงทะเบียน',status:'needs_review' as const },

  { key:'agent.quotes.back',namespace:'agent',description:'Quotes back link',en:'← Agent workspace',ru:'← Рабочее место агента',th:'← พื้นที่ทำงานเอเจนต์',status:'needs_review' as const },
  { key:'agent.quotes.title',namespace:'agent',description:'Quotes page title',en:'Quotes',ru:'Предложения',th:'ใบเสนอราคา',status:'needs_review' as const },
  { key:'agent.quotes.new',namespace:'agent',description:'Create quote action',en:'Create quote',ru:'Создать предложение',th:'สร้างใบเสนอราคา',status:'needs_review' as const },
  { key:'agent.quotes.client',namespace:'agent',description:'Quotes client label',en:'Client',ru:'Клиент',th:'ลูกค้า',status:'needs_review' as const },
  { key:'agent.quotes.total',namespace:'agent',description:'Quotes client total label',en:'Client total',ru:'Итого для клиента',th:'ยอดรวมลูกค้า',status:'needs_review' as const },
  { key:'agent.quotes.commission',namespace:'agent',description:'Quotes commission label',en:'Commission',ru:'Комиссия',th:'คอมมิชชั่น',status:'needs_review' as const },
  { key:'agent.quotes.availability',namespace:'agent',description:'Quotes availability label',en:'Availability',ru:'Доступность',th:'สถานะว่าง',status:'needs_review' as const },
  { key:'agent.quotes.empty',namespace:'agent',description:'No quotes state',en:'No quotes yet.',ru:'Предложений пока нет.',th:'ยังไม่มีใบเสนอราคา',status:'needs_review' as const },
  { key:'agent.quotes.share',namespace:'agent',description:'Quote share action',en:'Share',ru:'Отправить',th:'แชร์',status:'needs_review' as const },
];
