export const AGENT_PORTAL_KEYS = [
  { key: 'agent.contracts', namespace: 'agent', description: 'Shared opportunity administration', en: 'Contracts and completion', ru: 'Договоры и завершение сделки', status: 'needs_review' as const },
  { key: 'agent.sqm', namespace: 'agent', description: 'Area unit', en: 'm²', ru: 'м²', status: 'needs_review' as const },
  { key: 'agent.home', namespace: 'agent', description: 'Agent portal: home', en: "Agent HomeSpace", ru: "Рабочее место агента", status: 'needs_review' as const },
  { key: 'agent.contacts', namespace: 'agent', description: 'Agent portal: contacts', en: "Contacts", ru: "Контакты", status: 'needs_review' as const },
  { key: 'agent.opportunities', namespace: 'agent', description: 'Agent portal: opportunities', en: "Opportunities", ru: "Сделки", status: 'needs_review' as const },
  { key: 'agent.activities', namespace: 'agent', description: 'Agent portal: activities', en: "Follow-ups", ru: "Задачи", status: 'needs_review' as const },
  { key: 'agent.inventory', namespace: 'agent', description: 'Agent portal: inventory', en: "Inventory", ru: "Объекты", status: 'needs_review' as const },
  { key: 'agent.offers', namespace: 'agent', description: 'Agent portal: offers', en: "Client offers", ru: "Предложения клиентам", status: 'needs_review' as const },
  { key: 'agent.knowledge', namespace: 'agent', description: 'Agent portal: knowledge', en: "Knowledge & FAQ", ru: "База знаний и FAQ", status: 'needs_review' as const },
  { key: 'agent.commissions', namespace: 'agent', description: 'Agent portal: commissions', en: "Commissions", ru: "Комиссии", status: 'needs_review' as const },
  { key: 'agent.team', namespace: 'agent', description: 'Agent portal: team', en: "Agency team", ru: "Команда", status: 'needs_review' as const },
  { key: 'agent.workspace', namespace: 'agent', description: 'Agent portal: workspace', en: "Agency workspace", ru: "Агентство", status: 'needs_review' as const },
  { key: 'agent.intro', namespace: 'agent', description: 'Agent portal: intro', en: "Your clients, inventory, answers and next actions in one place.", ru: "Клиенты, объекты, ответы и следующие шаги в одном месте.", status: 'needs_review' as const },
  { key: 'agent.privacy', namespace: 'agent', description: 'Agent portal: privacy', en: "Client channels and notes stay in your workspace. Share an opportunity with MyUNO when you need coordination.", ru: "Контакты клиентов и заметки остаются в вашем кабинете. Передавайте MyUNO конкретную сделку, когда нужна помощь.", status: 'needs_review' as const },
  { key: 'agent.empty', namespace: 'agent', description: 'Agent portal: empty', en: "Nothing here yet. Start with your next client or opportunity.", ru: "Пока ничего нет. Начните с нового клиента или сделки.", status: 'needs_review' as const },
  { key: 'agent.name', namespace: 'agent', description: 'Agent portal: name', en: "Client name", ru: "Имя клиента", status: 'needs_review' as const },
  { key: 'agent.email', namespace: 'agent', description: 'Agent portal: email', en: "Email", ru: "Email", status: 'needs_review' as const },
  { key: 'agent.phone', namespace: 'agent', description: 'Agent portal: phone', en: "Phone (+country code)", ru: "Телефон (+код страны)", status: 'needs_review' as const },
  { key: 'agent.telegram', namespace: 'agent', description: 'Agent portal: telegram', en: "Telegram username", ru: "Имя пользователя Telegram", status: 'needs_review' as const },
  { key: 'agent.privateNotes', namespace: 'agent', description: 'Agent portal: privateNotes', en: "Private notes", ru: "Личные заметки", status: 'needs_review' as const },
  { key: 'agent.newContact', namespace: 'agent', description: 'Agent portal: newContact', en: "Add contact", ru: "Добавить контакт", status: 'needs_review' as const },
  { key: 'agent.newOpportunity', namespace: 'agent', description: 'Agent portal: newOpportunity', en: "Create opportunity", ru: "Создать сделку", status: 'needs_review' as const },
  { key: 'agent.contact', namespace: 'agent', description: 'Agent portal: contact', en: "Contact", ru: "Контакт", status: 'needs_review' as const },
  { key: 'agent.title', namespace: 'agent', description: 'Agent portal: title', en: "Title", ru: "Название", status: 'needs_review' as const },
  { key: 'agent.type', namespace: 'agent', description: 'Agent portal: type', en: "Type", ru: "Тип", status: 'needs_review' as const },
  { key: 'agent.rental', namespace: 'agent', description: 'Agent portal: rental', en: "Rental", ru: "Аренда", status: 'needs_review' as const },
  { key: 'agent.purchase', namespace: 'agent', description: 'Agent portal: purchase', en: "Purchase", ru: "Покупка", status: 'needs_review' as const },
  { key: 'agent.sale', namespace: 'agent', description: 'Agent portal: sale', en: "Sale", ru: "Продажа", status: 'needs_review' as const },
  { key: 'agent.new', namespace: 'agent', description: 'Agent portal: new', en: "New", ru: "Новая", status: 'needs_review' as const },
  { key: 'agent.qualified', namespace: 'agent', description: 'Agent portal: qualified', en: "Qualified", ru: "Квалифицирована", status: 'needs_review' as const },
  { key: 'agent.discovery', namespace: 'agent', description: 'Agent portal: discovery', en: "Needs & selection", ru: "Потребности и подбор", status: 'needs_review' as const },
  { key: 'agent.proposal', namespace: 'agent', description: 'Agent portal: proposal', en: "Proposal", ru: "Предложение", status: 'needs_review' as const },
  { key: 'agent.negotiation', namespace: 'agent', description: 'Agent portal: negotiation', en: "Negotiation", ru: "Переговоры", status: 'needs_review' as const },
  { key: 'agent.nurture', namespace: 'agent', description: 'Agent portal: nurture', en: "Later", ru: "На будущее", status: 'needs_review' as const },
  { key: 'agent.won', namespace: 'agent', description: 'Agent portal: won', en: "Completed", ru: "Завершена", status: 'needs_review' as const },
  { key: 'agent.lost', namespace: 'agent', description: 'Agent portal: lost', en: "Lost", ru: "Закрыта без сделки", status: 'needs_review' as const },
  { key: 'agent.stage', namespace: 'agent', description: 'Agent portal: stage', en: "Stage", ru: "Этап", status: 'needs_review' as const },
  { key: 'agent.move', namespace: 'agent', description: 'Agent portal: move', en: "Update stage", ru: "Обновить этап", status: 'needs_review' as const },
  { key: 'agent.lostReason', namespace: 'agent', description: 'Agent portal: lostReason', en: "Reason if lost", ru: "Причина отказа", status: 'needs_review' as const },
  { key: 'agent.newTask', namespace: 'agent', description: 'Agent portal: newTask', en: "Schedule follow-up", ru: "Запланировать задачу", status: 'needs_review' as const },
  { key: 'agent.subject', namespace: 'agent', description: 'Agent portal: subject', en: "Next action", ru: "Следующий шаг", status: 'needs_review' as const },
  { key: 'agent.dueAt', namespace: 'agent', description: 'Agent portal: dueAt', en: "Due date", ru: "Срок", status: 'needs_review' as const },
  { key: 'agent.complete', namespace: 'agent', description: 'Agent portal: complete', en: "Complete", ru: "Завершить", status: 'needs_review' as const },
  { key: 'agent.completed', namespace: 'agent', description: 'Agent portal: completed', en: "Completed", ru: "Завершено", status: 'needs_review' as const },
  { key: 'agent.open', namespace: 'agent', description: 'Agent portal: open', en: "Open", ru: "Открыто", status: 'needs_review' as const },
  { key: 'agent.cancelled', namespace: 'agent', description: 'Agent portal: cancelled', en: "Cancelled", ru: "Отменено", status: 'needs_review' as const },
  { key: 'agent.handover', namespace: 'agent', description: 'Agent portal: handover', en: "Ask MyUNO to coordinate", ru: "Передать MyUNO на сопровождение", status: 'needs_review' as const },
  { key: 'agent.request', namespace: 'agent', description: 'Agent portal: request', en: "What should MyUNO handle?", ru: "Что нужно поручить MyUNO?", status: 'needs_review' as const },
  { key: 'agent.consent', namespace: 'agent', description: 'Agent portal: consent', en: "I have the client's permission to share their name and contact channels with MyUNO for this opportunity.", ru: "Клиент разрешил передать MyUNO имя и контакты для сопровождения этой сделки.", status: 'needs_review' as const },
  { key: 'agent.receipt', namespace: 'agent', description: 'Agent portal: receipt', en: "Introduction receipt", ru: "Регистрация знакомства", status: 'needs_review' as const },
  { key: 'agent.queued', namespace: 'agent', description: 'Agent portal: queued', en: "Awaiting coordinator", ru: "Ожидает координатора", status: 'needs_review' as const },
  { key: 'agent.acknowledged', namespace: 'agent', description: 'Agent portal: acknowledged', en: "Coordinator assigned", ru: "Назначен координатор", status: 'needs_review' as const },
  { key: 'agent.declined', namespace: 'agent', description: 'Agent portal: declined', en: "Declined", ru: "Отклонено", status: 'needs_review' as const },
  { key: 'agent.coordinator', namespace: 'agent', description: 'Agent portal: coordinator', en: "Your coordinator", ru: "Ваш координатор", status: 'needs_review' as const },
  { key: 'agent.quote', namespace: 'agent', description: 'Agent portal: quote', en: "Prepare client quote", ru: "Подготовить расчет для клиента", status: 'needs_review' as const },
  { key: 'agent.amount', namespace: 'agent', description: 'Agent portal: amount', en: "Property price / rental amount, THB", ru: "Стоимость объекта / аренды, THB", status: 'needs_review' as const },
  { key: 'agent.fee', namespace: 'agent', description: 'Agent portal: fee', en: "Client fees, THB", ru: "Сборы клиента, THB", status: 'needs_review' as const },
  { key: 'agent.deposit', namespace: 'agent', description: 'Agent portal: deposit', en: "Deposit (separate), THB", ru: "Депозит (отдельно), THB", status: 'needs_review' as const },
  { key: 'agent.terms', namespace: 'agent', description: 'Agent portal: terms', en: "Terms, dates and inclusions", ru: "Условия, даты и состав предложения", status: 'needs_review' as const },
  { key: 'agent.expiresAt', namespace: 'agent', description: 'Agent portal: expiresAt', en: "Valid until", ru: "Действует до", status: 'needs_review' as const },
  { key: 'agent.offering', namespace: 'agent', description: 'Agent portal: offering', en: "Property offering", ru: "Предложение по объекту", status: 'needs_review' as const },
  { key: 'agent.quotePolicy', namespace: 'agent', description: 'Agent portal: quotePolicy', en: "Drafts need MyUNO review before sharing. A quote does not reserve inventory or form a contract.", ru: "Перед отправкой черновик проверяет MyUNO. Расчет не резервирует объект и не является договором.", status: 'needs_review' as const },
  { key: 'agent.draft', namespace: 'agent', description: 'Agent portal: draft', en: "Draft", ru: "Черновик", status: 'needs_review' as const },
  { key: 'agent.submitted', namespace: 'agent', description: 'Agent portal: submitted', en: "In MyUNO review", ru: "На проверке MyUNO", status: 'needs_review' as const },
  { key: 'agent.approved', namespace: 'agent', description: 'Agent portal: approved', en: "Approved", ru: "Утверждено", status: 'needs_review' as const },
  { key: 'agent.revoked', namespace: 'agent', description: 'Agent portal: revoked', en: "Revoked", ru: "Отозвано", status: 'needs_review' as const },
  { key: 'agent.submit', namespace: 'agent', description: 'Agent portal: submit', en: "Request quote review", ru: "Отправить на проверку", status: 'needs_review' as const },
  { key: 'agent.revoke', namespace: 'agent', description: 'Agent portal: revoke', en: "Revoke offer", ru: "Отозвать предложение", status: 'needs_review' as const },
  { key: 'agent.share', namespace: 'agent', description: 'Agent portal: share', en: "Create share link", ru: "Создать ссылку", status: 'needs_review' as const },
  { key: 'agent.copy', namespace: 'agent', description: 'Agent portal: copy', en: "Copy link", ru: "Копировать ссылку", status: 'needs_review' as const },
  { key: 'agent.copied', namespace: 'agent', description: 'Agent portal: copied', en: "Link copied", ru: "Ссылка скопирована", status: 'needs_review' as const },
  { key: 'agent.whatsapp', namespace: 'agent', description: 'Agent portal: whatsapp', en: "Open WhatsApp", ru: "Открыть WhatsApp", status: 'needs_review' as const },
  { key: 'agent.telegramShare', namespace: 'agent', description: 'Agent portal: telegramShare', en: "Open Telegram", ru: "Открыть Telegram", status: 'needs_review' as const },
  { key: 'agent.shareNote', namespace: 'agent', description: 'Agent portal: shareNote', en: "Choose the client and press send in your messenger. Opening a messenger does not confirm delivery.", ru: "Выберите клиента и отправьте сообщение в мессенджере. Открытие мессенджера не подтверждает доставку.", status: 'needs_review' as const },
  { key: 'agent.search', namespace: 'agent', description: 'Agent portal: search', en: "Search approved answers", ru: "Поиск по проверенным ответам", status: 'needs_review' as const },
  { key: 'agent.searchAction', namespace: 'agent', description: 'Agent portal: searchAction', en: "Search", ru: "Найти", status: 'needs_review' as const },
  { key: 'agent.knowledgeEmpty', namespace: 'agent', description: 'Agent portal: knowledgeEmpty', en: "No approved answer found in this language. Ask your MyUNO coordinator through an opportunity handover.", ru: "Проверенный ответ на этом языке не найден. Задайте вопрос координатору MyUNO через передачу сделки.", status: 'needs_review' as const },
  { key: 'agent.source', namespace: 'agent', description: 'Agent portal: source', en: "Source", ru: "Источник", status: 'needs_review' as const },
  { key: 'agent.reviewed', namespace: 'agent', description: 'Agent portal: reviewed', en: "Published", ru: "Опубликовано", status: 'needs_review' as const },
  { key: 'agent.commissionNote', namespace: 'agent', description: 'Agent portal: commissionNote', en: "Payment target: same day once due, no later than 3 days. Your approved agreement defines the due milestone and day basis. No commission is estimated without approved terms.", ru: "Цель — выплата в день возникновения обязательства, не позднее 3 дней. Утвержденное соглашение определяет основание выплаты и порядок исчисления дней. Без согласованных условий комиссия не рассчитывается.", status: 'needs_review' as const },
  { key: 'agent.pending', namespace: 'agent', description: 'Agent portal: pending', en: "Pending", ru: "Ожидается", status: 'needs_review' as const },
  { key: 'agent.due', namespace: 'agent', description: 'Agent portal: due', en: "Due", ru: "К выплате", status: 'needs_review' as const },
  { key: 'agent.paid', namespace: 'agent', description: 'Agent portal: paid', en: "Paid", ru: "Оплачено", status: 'needs_review' as const },
  { key: 'agent.disputed', namespace: 'agent', description: 'Agent portal: disputed', en: "Under review", ru: "На рассмотрении", status: 'needs_review' as const },
  { key: 'agent.targetAt', namespace: 'agent', description: 'Agent portal: targetAt', en: "Target date", ru: "Целевая дата", status: 'needs_review' as const },
  { key: 'agent.deadlineAt', namespace: 'agent', description: 'Agent portal: deadlineAt', en: "Deadline", ru: "Крайний срок", status: 'needs_review' as const },
  { key: 'agent.manager', namespace: 'agent', description: 'Agent portal: manager', en: "Agency manager", ru: "Руководитель агентства", status: 'needs_review' as const },
  { key: 'agent.agent', namespace: 'agent', description: 'Agent portal: agent', en: "Agent", ru: "Агент", status: 'needs_review' as const },
  { key: 'agent.saved', namespace: 'agent', description: 'Agent portal: saved', en: "Saved", ru: "Сохранено", status: 'needs_review' as const },
  { key: 'agent.error', namespace: 'agent', description: 'Agent portal: error', en: "Could not complete this action. Check the fields or ask your coordinator.", ru: "Не удалось выполнить действие. Проверьте поля или обратитесь к координатору.", status: 'needs_review' as const },
  { key: 'agent.saving', namespace: 'agent', description: 'Agent portal: saving', en: "Saving…", ru: "Сохранение…", status: 'needs_review' as const },
  { key: 'agent.notMember', namespace: 'agent', description: 'Agent portal: notMember', en: "Your agent workspace is not activated yet. Register your account and contact MyUNO to set up your agency.", ru: "Ваш агентский кабинет еще не активирован. Создайте учетную запись и обратитесь в MyUNO для подключения.", status: 'needs_review' as const },
  { key: 'agent.register', namespace: 'agent', description: 'Agent portal: register', en: "Register an account", ru: "Создать учетную запись", status: 'needs_review' as const },
  { key: 'agent.help', namespace: 'agent', description: 'Agent portal: help', en: "Contact MyUNO", ru: "Связаться с MyUNO", status: 'needs_review' as const },
  { key: 'agent.adminTitle', namespace: 'agent', description: 'Agent portal: adminTitle', en: "Agent partners & coordination", ru: "Агенты и сопровождение", status: 'needs_review' as const },
  { key: 'agent.provision', namespace: 'agent', description: 'Agent portal: provision', en: "Activate agency", ru: "Подключить агентство", status: 'needs_review' as const },
  { key: 'agent.agencyName', namespace: 'agent', description: 'Agent portal: agencyName', en: "Agency name", ru: "Название агентства", status: 'needs_review' as const },
  { key: 'agent.memberEmail', namespace: 'agent', description: 'Agent portal: memberEmail', en: "Registered agent email", ru: "Email зарегистрированного агента", status: 'needs_review' as const },
  { key: 'agent.addMember', namespace: 'agent', description: 'Agent portal: addMember', en: "Add agency member", ru: "Добавить участника", status: 'needs_review' as const },
  { key: 'agent.role', namespace: 'agent', description: 'Agent portal: role', en: "Role", ru: "Роль", status: 'needs_review' as const },
  { key: 'agent.revokeMember', namespace: 'agent', description: 'Agent portal: revokeMember', en: "Revoke access", ru: "Отозвать доступ", status: 'needs_review' as const },
  { key: 'agent.suspend', namespace: 'agent', description: 'Agent portal: suspend', en: "Suspend workspace", ru: "Приостановить кабинет", status: 'needs_review' as const },
  { key: 'agent.activate', namespace: 'agent', description: 'Agent portal: activate', en: "Activate workspace", ru: "Активировать кабинет", status: 'needs_review' as const },
  { key: 'agent.approveQuote', namespace: 'agent', description: 'Agent portal: approveQuote', en: "Approve client quote", ru: "Утвердить расчет для клиента", status: 'needs_review' as const },
  { key: 'agent.approvalNote', namespace: 'agent', description: 'Agent portal: approvalNote', en: "Verify prices, fees, dates and terms against authorized commercial conditions before approving.", ru: "Перед утверждением проверьте цены, сборы, даты и условия по действующим коммерческим правилам.", status: 'needs_review' as const },
  { key: 'agent.handoverQueue', namespace: 'agent', description: 'Agent portal: handoverQueue', en: "Shared opportunities", ru: "Переданные сделки", status: 'needs_review' as const },
  { key: 'agent.reviewQueue', namespace: 'agent', description: 'Agent portal: reviewQueue', en: "Quote review queue", ru: "Расчеты на проверке", status: 'needs_review' as const },
  { key: 'agent.knowledgeDraft', namespace: 'agent', description: 'Agent portal: knowledgeDraft', en: "Draft knowledge article", ru: "Создать статью", status: 'needs_review' as const },
  { key: 'agent.body', namespace: 'agent', description: 'Agent portal: body', en: "Answer", ru: "Ответ", status: 'needs_review' as const },
  { key: 'agent.sourceUrl', namespace: 'agent', description: 'Agent portal: sourceUrl', en: "Source URL", ru: "Ссылка на источник", status: 'needs_review' as const },
  { key: 'agent.locale', namespace: 'agent', description: 'Agent portal: locale', en: "Language", ru: "Язык", status: 'needs_review' as const },
  { key: 'agent.publish', namespace: 'agent', description: 'Agent portal: publish', en: "Publish reviewed answer", ru: "Опубликовать проверенный ответ", status: 'needs_review' as const },
  { key: 'agent.withdraw', namespace: 'agent', description: 'Agent portal: withdraw', en: "Withdraw answer", ru: "Снять с публикации", status: 'needs_review' as const },
  { key: 'agent.withdrawn', namespace: 'agent', description: 'Agent portal: withdrawn', en: "Withdrawn", ru: "Снято с публикации", status: 'needs_review' as const },
  { key: 'agent.clientQuote', namespace: 'agent', description: 'Agent portal: clientQuote', en: "Client quotation", ru: "Расчет для клиента", status: 'needs_review' as const },
  { key: 'agent.total', namespace: 'agent', description: 'Agent portal: total', en: "Price plus client fees, THB", ru: "Стоимость и сборы клиента, THB", status: 'needs_review' as const },
  { key: 'agent.validUntil', namespace: 'agent', description: 'Agent portal: validUntil', en: "Valid until", ru: "Действует до", status: 'needs_review' as const },
  { key: 'agent.availabilityNote', namespace: 'agent', description: 'Agent portal: availabilityNote', en: "Availability and contractual terms will be confirmed by MyUNO before commitment.", ru: "MyUNO подтвердит доступность объекта и условия договора до принятия обязательств.", status: 'needs_review' as const },
  { key: 'agent.partnersTitle', namespace: 'agent', description: 'Agent portal: partnersTitle', en: "Work with MyUNO", ru: "Работайте с MyUNO", status: 'needs_review' as const },
  { key: 'agent.partnersBody', namespace: 'agent', description: 'Agent portal: partnersBody', en: "Focus on your client. Use our inventory, prepare client offers and ask MyUNO to coordinate administration and contracts. Access is activated for approved agencies.", ru: "Работайте с клиентом. Подбирайте объекты, готовьте предложения и передавайте MyUNO сопровождение документов и договоров. Доступ подключается для одобренных агентств.", status: 'needs_review' as const },
  { key: 'agent.goPortal', namespace: 'agent', description: 'Agent portal: goPortal', en: "Open Agent HomeSpace", ru: "Открыть кабинет агента", status: 'needs_review' as const },
  { key: 'agent.myunoAdmin', namespace: 'agent', description: 'Agent portal: myunoAdmin', en: "MyUNO coordination", ru: "Сопровождение MyUNO", status: 'needs_review' as const },
  { key: 'agent.seeAll', namespace: 'agent', description: 'Agent portal: seeAll', en: "View all", ru: "Все записи", status: 'needs_review' as const },
  { key: 'agent.limited', namespace: 'agent', description: 'Agent portal: limited', en: "Showing up to 100 recent records in each section.", ru: "В каждом разделе показано до 100 последних записей.", status: 'needs_review' as const },
  { key: 'agent.quoteExpiry', namespace: 'agent', description: 'Agent portal: quoteExpiry', en: "Quote expired", ru: "Предложение истекло", status: 'needs_review' as const },
  { key: 'agent.inventoryNote', namespace: 'agent', description: 'Agent portal: inventoryNote', en: "Sales and long-term rental listings shown here pass current authority checks. Availability is confirmed during coordination.", ru: "Объекты для продажи и долгосрочной аренды проходят текущие проверки полномочий. Доступность подтверждается при сопровождении.", status: 'needs_review' as const },
  { key: 'agent.status', namespace: 'agent', description: 'Agent portal: status', en: "Status", ru: "Статус", status: 'needs_review' as const },
  { key: 'agent.recordedAt', namespace: 'agent', description: 'Agent portal: recordedAt', en: "Recorded", ru: "Зарегистрировано", status: 'needs_review' as const },
  { key: 'nav.agent_portal', namespace: 'nav', description: 'Agent surface entry', en: 'Agent HomeSpace', ru: 'Кабинет агента', status: 'needs_review' as const },
];
