/**
 * Content introduced by the consolidated release surfaces.
 * Russian copy intentionally mirrors the English draft until editorial review;
 * status=needs_review keeps that debt explicit instead of silently falling back.
 */
export const CONSOLIDATED_RELEASE_KEYS = [
  {
    key: 'admin.project360.facilities_count',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project360.facilities_count',
    en: '{count} project amenities / facilities',
    ru: '{count} project amenities / facilities',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project360.facilities_manage',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project360.facilities_manage',
    en: 'Manage amenities, rules, access and booking →',
    ru: 'Manage amenities, rules, access and booking →',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_preview.private',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_preview.private',
    en: 'Private preview · not published',
    ru: 'Private preview · not published',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_preview.project360',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_preview.project360',
    en: 'Project 360',
    ru: 'Project 360',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_preview.edit_media',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_preview.edit_media',
    en: 'Edit project media',
    ru: 'Edit project media',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_preview.stats',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_preview.stats',
    en: '{categories} canonical categories · {units} physical units · {unitPhotos} linked unit photos · {projectPhotos} project gallery photos. Draft units are not available for booking.',
    ru: '{categories} canonical categories · {units} physical units · {unitPhotos} linked unit photos · {projectPhotos} project gallery photos. Draft units are not available for booking.',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_preview.categories',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_preview.categories',
    en: 'Accommodation categories and exact units',
    ru: 'Accommodation categories and exact units',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_preview.unit_stats',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_preview.unit_stats',
    en: '{bedrooms} bedrooms · {units} villas · {status}',
    ru: '{bedrooms} bedrooms · {units} villas · {status}',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_preview.photos',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_preview.photos',
    en: '{count} exact-unit photos · {status}',
    ru: '{count} exact-unit photos · {status}',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_preview.amenities_title',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_preview.amenities_title',
    en: 'Project amenities',
    ru: 'Project amenities',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_preview.amenities_manage',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_preview.amenities_manage',
    en: 'Manage amenities →',
    ru: 'Manage amenities →',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.amenities.kicker',
    namespace: 'project_page',
    description: 'Release 160 surface copy: project_page.amenities.kicker',
    en: 'Project amenities',
    ru: 'Project amenities',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.amenities.included',
    namespace: 'project_page',
    description: 'Release 160 surface copy: project_page.amenities.included',
    en: 'Included',
    ru: 'Included',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.amenities.free',
    namespace: 'project_page',
    description: 'Release 160 surface copy: project_page.amenities.free',
    en: 'Free',
    ru: 'Free',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.amenities.booking_required',
    namespace: 'project_page',
    description: 'Release 160 surface copy: project_page.amenities.booking_required',
    en: 'Booking required',
    ru: 'Booking required',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.title',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.title',
    en: 'Concierge preferences',
    ru: 'Concierge preferences',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.body',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.body',
    en: 'myUNO marketplace services are available across all projects. Configure only optional project-specific prices, lead times or commercial preferences here.',
    ru: 'myUNO marketplace services are available across all projects. Configure only optional project-specific prices, lead times or commercial preferences here.',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.back',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.back',
    en: 'Back to Project 360',
    ru: 'Back to Project 360',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.base_price',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.base_price',
    en: 'Base price',
    ru: 'Base price',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.price_override',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.price_override',
    en: 'Project price (THB)',
    ru: 'Project price (THB)',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.lead_time',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.lead_time',
    en: 'Project lead time (hours)',
    ru: 'Project lead time (hours)',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.take_rate',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.take_rate',
    en: 'Project take rate (%)',
    ru: 'Project take rate (%)',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.save_terms',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.save_terms',
    en: 'Save preference',
    ru: 'Save preference',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.clear',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.clear',
    en: 'Use global defaults',
    ru: 'Use global defaults',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.saved',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.saved',
    en: 'Concierge preference saved.',
    ru: 'Concierge preference saved.',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.inherit',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.inherit',
    en: 'global default',
    ru: 'global default',
    status: 'needs_review' as const,
  },
  {
    key: 'admin.project_services.error',
    namespace: 'admin',
    description: 'Release 160 surface copy: admin.project_services.error',
    en: 'Could not update concierge preference.',
    ru: 'Could not update concierge preference.',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.back',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.back',
    en: 'Back to amenity',
    ru: 'Back to amenity',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.title',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.title',
    en: 'Reserve {amenity}',
    ru: 'Reserve {amenity}',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.new',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.new',
    en: 'Choose a time',
    ru: 'Choose a time',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.policy',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.policy',
    en: '{slot}-minute slots · minimum lead {lead} min · up to {days} days ahead',
    ru: '{slot}-minute slots · minimum lead {lead} min · up to {days} days ahead',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.start',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.start',
    en: 'Start time',
    ru: 'Start time',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.duration',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.duration',
    en: 'Duration',
    ru: 'Duration',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.minutes',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.minutes',
    en: '{count} minutes',
    ru: '{count} minutes',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.party',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.party',
    en: 'Party size',
    ru: 'Party size',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.note',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.note',
    en: 'Note (optional)',
    ru: 'Note (optional)',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.submit',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.submit',
    en: 'Reserve',
    ru: 'Reserve',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.saving',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.saving',
    en: 'Checking…',
    ru: 'Checking…',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.upcoming',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.upcoming',
    en: 'Your upcoming reservations',
    ru: 'Your upcoming reservations',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.party_count',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.party_count',
    en: '{count} guest(s)',
    ru: '{count} guest(s)',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.cancel',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.cancel',
    en: 'Cancel',
    ru: 'Cancel',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.none',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.none',
    en: 'No upcoming reservations for this amenity.',
    ru: 'No upcoming reservations for this amenity.',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.confirmed',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.confirmed',
    en: 'Reservation confirmed.',
    ru: 'Reservation confirmed.',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.requested',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.requested',
    en: 'Reservation request sent.',
    ru: 'Reservation request sent.',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.cancelled',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.cancelled',
    en: 'Reservation cancelled.',
    ru: 'Reservation cancelled.',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.invalid_time',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.invalid_time',
    en: 'Choose a valid start time.',
    ru: 'Choose a valid start time.',
    status: 'needs_review' as const,
  },
  {
    key: 'amenity_booking.error',
    namespace: 'amenity_booking',
    description: 'Release 160 surface copy: amenity_booking.error',
    en: 'Could not reserve this amenity.',
    ru: 'Could not reserve this amenity.',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.back',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.back',
    en: 'All amenities',
    ru: 'All amenities',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.terms',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.terms',
    en: 'Terms of use',
    ru: 'Terms of use',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.rules',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.rules',
    en: 'Rules',
    ru: 'Rules',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.location',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.location',
    en: 'Location',
    ru: 'Location',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.access',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.access',
    en: 'Access',
    ru: 'Access',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.how_access',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.how_access',
    en: 'How to access',
    ru: 'How to access',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.cost',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.cost',
    en: 'Cost',
    ru: 'Cost',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.capacity',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.capacity',
    en: 'Capacity',
    ru: 'Capacity',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.min_age',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.min_age',
    en: 'Minimum age',
    ru: 'Minimum age',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.booking',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.booking',
    en: 'Booking',
    ru: 'Booking',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.hours',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.hours',
    en: 'Opening hours',
    ru: 'Opening hours',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.book',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.book',
    en: 'Book this amenity',
    ru: 'Book this amenity',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.free',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.free',
    en: 'Free',
    ru: 'Free',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenity.included',
    namespace: 'project_amenity',
    description: 'Release 160 surface copy: project_amenity.included',
    en: 'Included',
    ru: 'Included',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenities.back',
    namespace: 'project_amenities',
    description: 'Release 160 surface copy: project_amenities.back',
    en: 'Back to project',
    ru: 'Back to project',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenities.title',
    namespace: 'project_amenities',
    description: 'Release 160 surface copy: project_amenities.title',
    en: 'Amenities & facilities',
    ru: 'Amenities & facilities',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenities.body',
    namespace: 'project_amenities',
    description: 'Release 160 surface copy: project_amenities.body',
    en: 'Everything available inside {project}, including access, opening hours, booking requirements and usage rules.',
    ru: 'Everything available inside {project}, including access, opening hours, booking requirements and usage rules.',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenities.free',
    namespace: 'project_amenities',
    description: 'Release 160 surface copy: project_amenities.free',
    en: 'Free',
    ru: 'Free',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenities.included',
    namespace: 'project_amenities',
    description: 'Release 160 surface copy: project_amenities.included',
    en: 'Included',
    ru: 'Included',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenities.booking_required',
    namespace: 'project_amenities',
    description: 'Release 160 surface copy: project_amenities.booking_required',
    en: 'Booking required',
    ru: 'Booking required',
    status: 'needs_review' as const,
  },
  {
    key: 'project_amenities.empty',
    namespace: 'project_amenities',
    description: 'Release 160 surface copy: project_amenities.empty',
    en: 'No published amenities yet.',
    ru: 'No published amenities yet.',
    status: 'needs_review' as const,
  },
  {
    key: 'project_category.back',
    namespace: 'project_category',
    description: 'Release 160 surface copy: project_category.back',
    en: 'Back to project',
    ru: 'Back to project',
    status: 'needs_review' as const,
  },
  {
    key: 'project_category.available',
    namespace: 'project_category',
    description: 'Release 160 surface copy: project_category.available',
    en: '{count} homes in this category',
    ru: '{count} homes in this category',
    status: 'needs_review' as const,
  },
  {
    key: 'project_category.bedrooms',
    namespace: 'project_category',
    description: 'Release 160 surface copy: project_category.bedrooms',
    en: '{count} bedrooms',
    ru: '{count} bedrooms',
    status: 'needs_review' as const,
  },
  {
    key: 'project_category.from',
    namespace: 'project_category',
    description: 'Release 160 surface copy: project_category.from',
    en: 'from ฿{price} / night',
    ru: 'from ฿{price} / night',
    status: 'needs_review' as const,
  },
  {
    key: 'project_category.search',
    namespace: 'project_category',
    description: 'Release 160 surface copy: project_category.search',
    en: 'Check availability',
    ru: 'Check availability',
    status: 'needs_review' as const,
  },
  {
    key: 'project_category.units',
    namespace: 'project_category',
    description: 'Release 160 surface copy: project_category.units',
    en: 'Exact homes in this category',
    ru: 'Exact homes in this category',
    status: 'needs_review' as const,
  },
  {
    key: 'project_category.guests',
    namespace: 'project_category',
    description: 'Release 160 surface copy: project_category.guests',
    en: 'Up to {count} guests',
    ru: 'Up to {count} guests',
    status: 'needs_review' as const,
  },
  {
    key: 'project_category.size',
    namespace: 'project_category',
    description: 'Release 160 surface copy: project_category.size',
    en: '{count} sqm',
    ru: '{count} sqm',
    status: 'needs_review' as const,
  },
  {
    key: 'project_category.view_unit',
    namespace: 'project_category',
    description: 'Release 160 surface copy: project_category.view_unit',
    en: 'View exact home →',
    ru: 'View exact home →',
    status: 'needs_review' as const,
  },
  {
    key: 'project_category.gallery',
    namespace: 'project_category',
    description: 'Release 160 surface copy: project_category.gallery',
    en: 'Category gallery',
    ru: 'Category gallery',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.owner_intake.title',
    namespace: 'project_page',
    description: 'Release 160 surface copy: project_page.owner_intake.title',
    en: 'Own or manage a home here?',
    ru: "Вы владеете объектом здесь или управляете им?",
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.owner_intake.body',
    namespace: 'project_page',
    description: 'Release 160 surface copy: project_page.owner_intake.body',
    en: 'Submit your home to this existing residence. Our team verifies your authority and the listing before publication.',
    ru: "Добавьте свой объект в эту резиденцию. Перед публикацией команда проверит ваши полномочия и объявление.",
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.owner_intake.cta',
    namespace: 'project_page',
    description: 'Release 160 surface copy: project_page.owner_intake.cta',
    en: 'Add your home →',
    ru: "Добавить свой объект →",
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.amenities.view_all',
    namespace: 'project_page',
    description: 'Release 160 surface copy: project_page.amenities.view_all',
    en: 'View all amenities →',
    ru: 'View all amenities →',
    status: 'needs_review' as const,
  },
  {
    key: 'project.services.eyebrow',
    namespace: 'project',
    description: 'Release 160 surface copy: project.services.eyebrow',
    en: 'myUNO services',
    ru: "Сервисы myUNO",
    status: 'needs_review' as const,
  },
  {
    key: 'project.services.title',
    namespace: 'project',
    description: 'Release 160 surface copy: project.services.title',
    en: 'Everything around your stay',
    ru: "Всё для вашего проживания",
    status: 'needs_review' as const,
  },
  {
    key: 'project.services.body',
    namespace: 'project',
    description: 'Release 160 surface copy: project.services.body',
    en: 'Transfers, flowers, wellness, dining and other vetted services available for {project}.',
    ru: "Трансферы, цветы, оздоровительные процедуры, питание и другие проверенные услуги, доступные для {project}.",
    status: 'needs_review' as const,
  },
  {
    key: 'project.services.view_all',
    namespace: 'project',
    description: 'Release 160 surface copy: project.services.view_all',
    en: 'Explore all services →',
    ru: "Все услуги →",
    status: 'needs_review' as const,
  },
  {
    key: 'project.services.from',
    namespace: 'project',
    description: 'Release 160 surface copy: project.services.from',
    en: 'from ฿{price}',
    ru: "от ฿{price}",
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.rules.title',
    namespace: 'project_page',
    description: 'Release 160 surface copy: project_page.rules.title',
    en: 'House rules',
    ru: 'House rules',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.shuttle.title',
    namespace: 'project_page',
    description: 'Release 160 surface copy: project_page.shuttle.title',
    en: 'Shuttle & transport',
    ru: 'Shuttle & transport',
    status: 'needs_review' as const,
  },
  {
    key: 'home.amenities.title',
    namespace: 'home',
    description: 'Release 160 surface copy: home.amenities.title',
    en: 'Amenities at your project',
    ru: 'Amenities at your project',
    status: 'needs_review' as const,
  },
  {
    key: 'home.amenities.view_all',
    namespace: 'home',
    description: 'Release 160 surface copy: home.amenities.view_all',
    en: 'View all amenities →',
    ru: 'View all amenities →',
    status: 'needs_review' as const,
  },
  {
    key: 'home.amenities.kicker',
    namespace: 'home',
    description: 'Release 160 surface copy: home.amenities.kicker',
    en: 'Project amenities',
    ru: 'Project amenities',
    status: 'needs_review' as const,
  },
  {
    key: 'home.amenities.included',
    namespace: 'home',
    description: 'Release 160 surface copy: home.amenities.included',
    en: 'Included',
    ru: 'Included',
    status: 'needs_review' as const,
  },
  {
    key: 'home.amenities.free',
    namespace: 'home',
    description: 'Release 160 surface copy: home.amenities.free',
    en: 'Free',
    ru: 'Free',
    status: 'needs_review' as const,
  },
  {
    key: 'home.amenities.booking_required',
    namespace: 'home',
    description: 'Release 160 surface copy: home.amenities.booking_required',
    en: 'Booking required',
    ru: 'Booking required',
    status: 'needs_review' as const,
  },
  {
    key: 'saved.remove',
    namespace: 'saved',
    description: 'Release 160 surface copy: saved.remove',
    en: 'Remove from saved',
    ru: 'Remove from saved',
    status: 'needs_review' as const,
  },
  {
    key: 'saved.removing',
    namespace: 'saved',
    description: 'Release 160 surface copy: saved.removing',
    en: 'Removing…',
    ru: 'Removing…',
    status: 'needs_review' as const,
  },
  {
    key: 'saved.remove_failed',
    namespace: 'saved',
    description: 'Release 160 surface copy: saved.remove_failed',
    en: 'Could not remove this home. Please try again.',
    ru: 'Could not remove this home. Please try again.',
    status: 'needs_review' as const,
  },
  {
    key: 'saved.default_list',
    namespace: 'saved',
    description: 'Release 160 surface copy: saved.default_list',
    en: 'Saved homes',
    ru: 'Saved homes',
    status: 'needs_review' as const,
  },
  {
    key: 'staff.ops.portfolio_link',
    namespace: 'staff',
    description: 'Ops navigation to managed portfolio',
    en: 'Managed portfolio →',
    ru: 'Управляемый портфель →',
    status: 'needs_review' as const,
  },
  {
    key: 'staff.ops.add_unit_link',
    namespace: 'staff',
    description: 'Ops navigation to add property',
    en: 'Add property →',
    ru: 'Добавить объект →',
    status: 'needs_review' as const,
  },
  {
    key: 'staff.ops.team_link',
    namespace: 'staff',
    description: 'Ops navigation to project team',
    en: 'Project team →',
    ru: 'Команда проекта →',
    status: 'needs_review' as const,
  },
];
