/** Distribution Controller workspace labels. */
export const DISTRIBUTION_CONTROLLER_KEYS = [
  { key:'distribution.back_space',namespace:'distribution',description:'Back to operating space',en:'← Operating space',ru:'← Операционный контур',th:'← พื้นที่ปฏิบัติการ',status:'needs_review' as const },
  { key:'distribution.kicker',namespace:'distribution',description:'Distribution controller kicker',en:'DISTRIBUTION CONTROL',ru:'УПРАВЛЕНИЕ ДИСТРИБУЦИЕЙ',th:'ควบคุมการจัดจำหน่าย',status:'needs_review' as const },
  { key:'distribution.title',namespace:'distribution',description:'Distribution controller title',en:'Distribution',ru:'Дистрибуция',th:'การจัดจำหน่าย',status:'needs_review' as const },
  { key:'distribution.subtitle',namespace:'distribution',description:'Distribution controller subtitle',en:'Control how each commercial offering is distributed without duplicating inventory.',ru:'Управляйте дистрибуцией каждого предложения без дублирования инвентаря.',th:'ควบคุมการจัดจำหน่ายแต่ละข้อเสนอโดยไม่ทำซ้ำอินเวนทอรี',status:'needs_review' as const },
  { key:'distribution.metric.offerings',namespace:'distribution',description:'Active offerings metric',en:'Active offerings',ru:'Активные предложения',th:'ข้อเสนอที่ใช้งาน',status:'needs_review' as const },
  { key:'distribution.metric.agent',namespace:'distribution',description:'Agent enabled metric',en:'Agent enabled',ru:'Доступно агентам',th:'เปิดให้เอเจนต์',status:'needs_review' as const },
  { key:'distribution.metric.request',namespace:'distribution',description:'Request-only metric',en:'Request availability',ru:'Доступность по запросу',th:'ขอสถานะว่าง',status:'needs_review' as const },
  { key:'distribution.metric.partner',namespace:'distribution',description:'Partner inventory metric',en:'Partner inventory',ru:'Партнёрский инвентарь',th:'อินเวนทอรีพาร์ทเนอร์',status:'needs_review' as const },
  { key:'distribution.metric.errors',namespace:'distribution',description:'Channel errors metric',en:'Channel errors',ru:'Ошибки каналов',th:'ข้อผิดพลาดช่องทาง',status:'needs_review' as const },
  { key:'distribution.project_unit',namespace:'distribution',description:'Project and unit column',en:'Property',ru:'Объект',th:'อสังหาริมทรัพย์',status:'needs_review' as const },
  { key:'distribution.offering',namespace:'distribution',description:'Offering type column',en:'Offering',ru:'Предложение',th:'ข้อเสนอ',status:'needs_review' as const },
  { key:'distribution.source',namespace:'distribution',description:'Inventory source',en:'Source',ru:'Источник',th:'แหล่งที่มา',status:'needs_review' as const },
  { key:'distribution.availability',namespace:'distribution',description:'Availability mode',en:'Availability',ru:'Доступность',th:'สถานะว่าง',status:'needs_review' as const },
  { key:'distribution.booking',namespace:'distribution',description:'Booking mode',en:'Booking',ru:'Бронирование',th:'การจอง',status:'needs_review' as const },
  { key:'distribution.agent',namespace:'distribution',description:'Agent distribution toggle',en:'Agents',ru:'Агенты',th:'เอเจนต์',status:'needs_review' as const },
  { key:'distribution.ota',namespace:'distribution',description:'OTA distribution toggle',en:'OTA',ru:'OTA',th:'OTA',status:'needs_review' as const },
  { key:'distribution.commission',namespace:'distribution',description:'Default agent commission',en:'Agent commission %',ru:'Комиссия агента %',th:'คอมมิชชั่นเอเจนต์ %',status:'needs_review' as const },
  { key:'distribution.markup',namespace:'distribution',description:'Agent markup permission',en:'Agent markup',ru:'Наценка агента',th:'มาร์กอัปเอเจนต์',status:'needs_review' as const },
  { key:'distribution.max_markup',namespace:'distribution',description:'Max agent markup',en:'Max markup %',ru:'Макс. наценка %',th:'มาร์กอัปสูงสุด %',status:'needs_review' as const },
  { key:'distribution.sla',namespace:'distribution',description:'Confirmation SLA',en:'Confirm SLA, min',ru:'SLA подтверждения, мин',th:'SLA ยืนยัน, นาที',status:'needs_review' as const },
  { key:'distribution.stale',namespace:'distribution',description:'Sync stale threshold',en:'Stale after, min',ru:'Считать устаревшим через, мин',th:'ถือว่าล้าสมัยหลัง, นาที',status:'needs_review' as const },
  { key:'distribution.partner_org',namespace:'distribution',description:'Supply partner organization',en:'Supply partner',ru:'Партнёр-поставщик',th:'พาร์ทเนอร์ซัพพลาย',status:'needs_review' as const },
  { key:'distribution.none',namespace:'distribution',description:'No selection',en:'None',ru:'Нет',th:'ไม่มี',status:'needs_review' as const },
  { key:'distribution.yes',namespace:'distribution',description:'Yes',en:'Yes',ru:'Да',th:'ใช่',status:'needs_review' as const },
  { key:'distribution.no',namespace:'distribution',description:'No',en:'No',ru:'Нет',th:'ไม่',status:'needs_review' as const },
  { key:'distribution.save',namespace:'distribution',description:'Save policy',en:'Save',ru:'Сохранить',th:'บันทึก',status:'needs_review' as const },
  { key:'distribution.saving',namespace:'distribution',description:'Saving policy',en:'Saving…',ru:'Сохранение…',th:'กำลังบันทึก…',status:'needs_review' as const },
  { key:'distribution.saved',namespace:'distribution',description:'Policy saved',en:'Saved',ru:'Сохранено',th:'บันทึกแล้ว',status:'needs_review' as const },
  { key:'distribution.channel_ok',namespace:'distribution',description:'Channel health okay',en:'Healthy',ru:'Норма',th:'ปกติ',status:'needs_review' as const },
  { key:'distribution.channel_error',namespace:'distribution',description:'Channel error',en:'Attention',ru:'Внимание',th:'ต้องตรวจสอบ',status:'needs_review' as const },
  { key:'distribution.no_channel_mapping',namespace:'distribution',description:'No channel mapping',en:'No channel mapping',ru:'Канал не настроен',th:'ไม่มีการเชื่อมต่อช่องทาง',status:'needs_review' as const },
  { key:'distribution.channel_attention_required',namespace:'distribution',description:'Channel attention required',en:'Channel attention required',ru:'Канал требует внимания',th:'ช่องทางต้องตรวจสอบ',status:'needs_review' as const },
  { key:'distribution.source.managed',namespace:'distribution',description:'Managed source option',en:'Managed',ru:'Под управлением',th:'บริหารจัดการ',status:'needs_review' as const },
  { key:'distribution.source.partner',namespace:'distribution',description:'Partner source option',en:'Partner',ru:'Партнёр',th:'พาร์ทเนอร์',status:'needs_review' as const },
  { key:'distribution.availability.live',namespace:'distribution',description:'Live availability option',en:'LIVE',ru:'LIVE',th:'LIVE',status:'needs_review' as const },
  { key:'distribution.availability.synced',namespace:'distribution',description:'Synced availability option',en:'SYNCED',ru:'СИНХРОНИЗИРОВАНО',th:'ซิงค์แล้ว',status:'needs_review' as const },
  { key:'distribution.availability.request',namespace:'distribution',description:'Request availability option',en:'REQUEST',ru:'ПО ЗАПРОСУ',th:'ตามคำขอ',status:'needs_review' as const },
  { key:'distribution.booking.instant',namespace:'distribution',description:'Instant booking option',en:'Instant',ru:'Мгновенно',th:'ทันที',status:'needs_review' as const },
  { key:'distribution.booking.request',namespace:'distribution',description:'Request booking option',en:'Request',ru:'По запросу',th:'ตามคำขอ',status:'needs_review' as const },
  { key:'distribution.booking.operator_approval',namespace:'distribution',description:'Operator approval booking option',en:'Operator approval',ru:'Подтверждение оператора',th:'อนุมัติโดยผู้ดำเนินการ',status:'needs_review' as const },
  { key:'distribution.booking.partner_approval',namespace:'distribution',description:'Partner approval booking option',en:'Partner approval',ru:'Подтверждение партнёра',th:'อนุมัติโดยพาร์ทเนอร์',status:'needs_review' as const },
  { key:'distribution.booking.not_agent_bookable',namespace:'distribution',description:'Not agent bookable option',en:'Not agent bookable',ru:'Недоступно агентам',th:'เอเจนต์จองไม่ได้',status:'needs_review' as const },
] as const;
