/** Operating Space manager workspace: draft translations for EN/RU/TH. */
export const OPERATING_SPACE_KEYS = [
  { key: 'staff.spaces.back', namespace: 'staff', description: 'Operating spaces back link', en: '← Operations', ru: '← Операции', th: '← การปฏิบัติงาน', status: 'needs_review' as const },
  { key: 'staff.spaces.kicker', namespace: 'staff', description: 'Operating spaces kicker', en: 'MANAGED PORTFOLIO', ru: 'УПРАВЛЯЕМЫЙ ПОРТФЕЛЬ', th: 'พอร์ตที่บริหาร', status: 'needs_review' as const },
  { key: 'staff.spaces.title', namespace: 'staff', description: 'Operating spaces title', en: 'Operating spaces', ru: 'Операционные пространства', th: 'พื้นที่ปฏิบัติการ', status: 'needs_review' as const },
  { key: 'staff.spaces.subtitle', namespace: 'staff', description: 'Operating spaces subtitle', en: 'Choose the management context for calendar, reservations, tasks, pricing and reporting.', ru: 'Выберите контур управления для календаря, бронирований, задач, цен и отчётности.', th: 'เลือกบริบทการจัดการสำหรับปฏิทิน การจอง งาน ราคา และรายงาน', status: 'needs_review' as const },
  { key: 'staff.spaces.units', namespace: 'staff', description: 'Operating spaces unit count', en: 'managed homes', ru: 'объектов в управлении', th: 'บ้านที่บริหาร', status: 'needs_review' as const },
  { key: 'staff.spaces.team', namespace: 'staff', description: 'Operating spaces team count', en: 'team members', ru: 'членов команды', th: 'สมาชิกทีม', status: 'needs_review' as const },
  { key: 'staff.spaces.open', namespace: 'staff', description: 'Open operating space', en: 'Open workspace →', ru: 'Открыть →', th: 'เปิดพื้นที่ทำงาน →', status: 'needs_review' as const },
  { key: 'staff.spaces.empty', namespace: 'staff', description: 'No operating spaces state', en: 'No operating spaces are assigned to this account.', ru: 'Для этой учётной записи нет назначенных операционных пространств.', th: 'บัญชีนี้ยังไม่ได้รับมอบหมายพื้นที่ปฏิบัติการ', status: 'needs_review' as const },

  { key: 'staff.space.back', namespace: 'staff', description: 'Operating space back link', en: '← Operating spaces', ru: '← Операционные пространства', th: '← พื้นที่ปฏิบัติการ', status: 'needs_review' as const },
  { key: 'staff.space.kicker', namespace: 'staff', description: 'Operating space kicker', en: 'OPERATING SPACE', ru: 'ОПЕРАЦИОННОЕ ПРОСТРАНСТВО', th: 'พื้นที่ปฏิบัติการ', status: 'needs_review' as const },
  { key: 'staff.space.today', namespace: 'staff', description: 'Operating space today section', en: 'Today', ru: 'Сегодня', th: 'วันนี้', status: 'needs_review' as const },
  { key: 'staff.space.units', namespace: 'staff', description: 'Managed units metric', en: 'Managed homes', ru: 'Объекты в управлении', th: 'บ้านที่บริหาร', status: 'needs_review' as const },
  { key: 'staff.space.arrivals', namespace: 'staff', description: 'Arrivals metric', en: 'Arrivals', ru: 'Заезды', th: 'เช็กอิน', status: 'needs_review' as const },
  { key: 'staff.space.departures', namespace: 'staff', description: 'Departures metric', en: 'Departures', ru: 'Выезды', th: 'เช็กเอาต์', status: 'needs_review' as const },
  { key: 'staff.space.occupied', namespace: 'staff', description: 'Occupied metric', en: 'Occupied now', ru: 'Занято сейчас', th: 'มีผู้เข้าพัก', status: 'needs_review' as const },
  { key: 'staff.space.requests', namespace: 'staff', description: 'Booking requests metric', en: 'Booking requests', ru: 'Запросы на бронирование', th: 'คำขอจอง', status: 'needs_review' as const },
  { key: 'staff.space.tasks', namespace: 'staff', description: 'Open tasks metric', en: 'Open readiness tasks', ru: 'Открытые задачи готовности', th: 'งานเตรียมความพร้อมที่เปิดอยู่', status: 'needs_review' as const },
  { key: 'staff.space.calendar', namespace: 'staff', description: 'Operating space calendar link', en: 'Calendar', ru: 'Календарь', th: 'ปฏิทิน', status: 'needs_review' as const },
  { key: 'staff.space.reservations', namespace: 'staff', description: 'Operating space reservations link', en: 'Reservations', ru: 'Бронирования', th: 'การจอง', status: 'needs_review' as const },
  { key: 'staff.space.housekeeping', namespace: 'staff', description: 'Operating space housekeeping link', en: 'Housekeeping & tasks', ru: 'Хаускипинг и задачи', th: 'แม่บ้านและงาน', status: 'needs_review' as const },
  { key: 'staff.space.pricing', namespace: 'staff', description: 'Operating space pricing link', en: 'Pricing', ru: 'Ценообразование', th: 'ราคา', status: 'needs_review' as const },
  { key: 'staff.space.team', namespace: 'staff', description: 'Operating space team link', en: 'Team', ru: 'Команда', th: 'ทีม', status: 'needs_review' as const },
  { key: 'staff.space.finance', namespace: 'staff', description: 'Operating space finance link', en: 'Finance & reports', ru: 'Финансы и отчёты', th: 'การเงินและรายงาน', status: 'needs_review' as const },
  { key: 'staff.space.channels', namespace: 'staff', description: 'Operating space channels link', en: 'Channels', ru: 'Каналы', th: 'ช่องทาง', status: 'needs_review' as const },
  { key: 'staff.space.scope_hint', namespace: 'staff', description: 'Operating space canonical scope explanation', en: 'All actions stay within this operating space and continue to use canonical Unit, Booking, Pricing and Finance records.', ru: 'Все действия ограничены этим операционным пространством и используют канонические записи объектов, бронирований, цен и финансов.', th: 'ทุกการดำเนินการอยู่ภายในพื้นที่ปฏิบัติการนี้และใช้ข้อมูลหลักของยูนิต การจอง ราคา และการเงิน', status: 'needs_review' as const },
];
