const draft=(key:string,en:string,ru:string,namespace='staff')=>({
  key,namespace,description:'PMS operations: '+key,en,ru,status:'needs_review' as const,
});

export const PMS_OPERATIONS_KEYS=[
  draft('staff.spaces.manage','Manage spaces','Управление пространствами'),
  draft('staff.space.tasks_link','Tasks','Задачи'),
  draft('staff.space.incidents','Incidents','Инциденты'),

  draft('staff.finance.back','← Workspace','← Рабочее пространство'),
  draft('staff.finance.title','Finance & owner reporting','Финансы и отчётность собственникам'),
  draft('staff.finance.subtitle','Canonical ledger and owner statements for the properties in this operating space.','Канонический реестр и отчёты собственникам по объектам этого операционного пространства.'),
  draft('staff.finance.ledger','Ledger','Реестр'),
  draft('staff.finance.statements','Owner statements','Отчёты собственникам'),
  draft('staff.finance.no_ledger','No ledger entries in this scope.','В этом контуре нет записей реестра.'),
  draft('staff.finance.no_statements','No owner statements in this scope.','В этом контуре нет отчётов собственникам.'),
  draft('staff.finance.revenue','Revenue','Выручка'),
  draft('staff.finance.costs','Costs','Расходы'),
  draft('staff.finance.noi','NOI','NOI'),
  draft('staff.finance.owner_share','Owner','Собственнику'),
  draft('staff.finance.generate_statement','Generate owner statement','Сформировать отчёт собственнику'),
  draft('staff.finance.generate_hint','Create the draft owner statement from canonical bookings, payments, ledger costs and the active management engagement.','Создайте черновик отчёта из канонических бронирований, платежей, расходов и действующего мандата управления.'),
  draft('staff.finance.statement_error','Could not generate the owner statement.','Не удалось сформировать отчёт собственнику.'),
  draft('staff.finance.statement_created','Draft owner statement created.','Черновик отчёта собственнику создан.'),
  draft('staff.finance.property','Property','Объект'),
  draft('staff.finance.choose_property','Choose property','Выберите объект'),
  draft('staff.finance.period_start','Period start','Начало периода'),
  draft('staff.finance.period_end','Period end','Конец периода'),
  draft('staff.finance.generate','Generate draft','Сформировать черновик'),
  draft('staff.finance.generating','Generating…','Формирование…'),

  draft('staff.incidents.back','← Workspace','← Рабочее пространство'),
  draft('staff.incidents.title','Incidents & accidents','Инциденты и происшествия'),
  draft('staff.incidents.subtitle','Report, assign and resolve operational incidents only within this management scope.','Регистрируйте, назначайте и закрывайте инциденты только в пределах этого контура управления.'),
  draft('staff.incidents.report','Report incident','Зарегистрировать инцидент'),
  draft('staff.incidents.property','Select property','Выберите объект'),
  draft('staff.incidents.unassigned','Unassigned','Не назначено'),
  draft('staff.incidents.description','What happened, impact, and immediate action taken','Что произошло, последствия и предпринятые действия'),
  draft('staff.incidents.create','Create incident','Создать инцидент'),
  draft('staff.incidents.saving','Saving…','Сохранение…'),
  draft('staff.incidents.open','Open incidents','Открытые инциденты'),
  draft('staff.incidents.empty','No open incidents in this operating space.','В этом операционном пространстве нет открытых инцидентов.'),
  draft('staff.incidents.assigned','Assigned to','Назначено'),
  draft('staff.incidents.ack','Acknowledge','Принять'),
  draft('staff.incidents.start','Start work','Начать работу'),
  draft('staff.incidents.resolve','Resolve','Закрыть'),
  draft('staff.incidents.resolve_prompt','Resolution / corrective action','Решение / корректирующие действия'),
  draft('staff.incidents.created','Incident created.','Инцидент создан.'),
  draft('staff.incidents.updated','Incident updated.','Инцидент обновлён.'),
  draft('staff.incidents.error','Incident action failed.','Не удалось выполнить действие с инцидентом.'),

  draft('staff.space_access.back','← Workspace','← Рабочее пространство'),
  draft('staff.space_access.title','Team & access','Команда и доступ'),
  draft('staff.space_access.subtitle','Control exactly who can operate this portfolio, which properties they can touch, and what actions they may perform.','Точно задайте, кто управляет портфелем, к каким объектам имеет доступ и какие действия может выполнять.'),
  draft('staff.space_access.loading','Loading access model…','Загрузка модели доступа…'),
  draft('staff.space_access.error','Could not update team access.','Не удалось обновить доступ команды.'),
  draft('staff.space_access.saved','Access saved.','Доступ сохранён.'),
  draft('staff.space_access.removed','Access removed.','Доступ удалён.'),
  draft('staff.space_access.member_title','Add or edit operator','Добавить или изменить сотрудника'),
  draft('staff.space_access.member_hint','Capabilities define what this person may do; selected properties define where they may do it.','Полномочия определяют, что человек может делать; выбранные объекты — где именно.'),
  draft('staff.space_access.email','Existing myUNO account email','Email существующей учётной записи myUNO'),
  draft('staff.space_access.capabilities','Capabilities','Полномочия'),
  draft('staff.space_access.properties','Managed properties','Объекты в управлении'),
  draft('staff.space_access.select_all','Select all','Выбрать все'),
  draft('staff.space_access.save_member','Save operator access','Сохранить доступ'),
  draft('staff.space_access.saving','Saving…','Сохранение…'),
  draft('staff.space_access.members','Operators','Сотрудники'),
  draft('staff.space_access.members_empty','No operators assigned yet.','Сотрудники ещё не назначены.'),
  draft('staff.space_access.properties_count','properties','объектов'),
  draft('staff.space_access.no_capabilities','No operational capabilities','Нет операционных полномочий'),
  draft('staff.space_access.edit','Edit access','Изменить доступ'),
  draft('staff.space_access.remove','Remove','Удалить'),
  draft('staff.space_access.remove_confirm','Remove this person from the operating space and revoke their unit access?','Удалить человека из операционного пространства и отозвать доступ к объектам?'),
  draft('staff.space_access.teams','Operating teams','Операционные команды'),
  draft('staff.space_access.team_name','Team name','Название команды'),
  draft('staff.space_access.create_team','Create team','Создать команду'),
  draft('staff.space_access.team_created','Team created.','Команда создана.'),
  draft('staff.space_access.team_saved','Team membership saved.','Состав команды сохранён.'),

  draft('staff.space_manage.back','← Operating spaces','← Операционные пространства'),
  draft('staff.space_manage.title','Operating-space setup','Настройка операционных пространств'),
  draft('staff.space_manage.subtitle','Create management portfolios and define exactly which properties belong to each operating context.','Создавайте контуры управления и точно определяйте состав объектов каждого из них.'),
  draft('staff.space_manage.error','Could not save the operating space.','Не удалось сохранить операционное пространство.'),
  draft('staff.space_manage.create','Create operating space','Создать операционное пространство'),
  draft('staff.space_manage.edit','Edit operating space','Изменить операционное пространство'),
  draft('staff.space_manage.hint','Use one space for each independently operated resort, portfolio, or management team context.','Используйте отдельное пространство для каждого независимо управляемого курорта, портфеля или команды.'),
  draft('staff.space_manage.cancel','Cancel edit','Отменить изменение'),
  draft('staff.space_manage.name','Name','Название'),
  draft('staff.space_manage.key','Key','Ключ'),
  draft('staff.space_manage.organization','Organization','Организация'),
  draft('staff.space_manage.status','Status','Статус'),
  draft('staff.space_manage.choose','Choose organization','Выберите организацию'),
  draft('staff.space_manage.active','Active','Активно'),
  draft('staff.space_manage.archived','Archived','Архив'),
  draft('staff.space_manage.properties','Properties in this space','Объекты в пространстве'),
  draft('staff.space_manage.properties_hint','A space may contain a full resort or selected units across different projects.','Пространство может включать весь курорт или выбранные юниты из разных проектов.'),
  draft('staff.space_manage.search','Search project, category or property','Поиск проекта, категории или объекта'),
  draft('staff.space_manage.selected','properties selected','объектов выбрано'),
  draft('staff.space_manage.save','Save operating space','Сохранить пространство'),
  draft('staff.space_manage.saving','Saving…','Сохранение…'),
  draft('staff.space_manage.created','Operating space created.','Операционное пространство создано.'),
  draft('staff.space_manage.updated','Operating space updated.','Операционное пространство обновлено.'),
  draft('staff.space_manage.existing','Existing operating spaces','Существующие операционные пространства'),
  draft('staff.space_manage.properties_count','properties','объектов'),
  draft('staff.space_manage.members_count','operators','сотрудников'),
  draft('staff.space_manage.teams_count','teams','команд'),
  draft('staff.space_manage.edit_action','Edit','Изменить'),
];
