/** PMS release slice: readiness, effective-rate and channel-health operational UI. */
export const PMS_RELEASE_KEYS = [
  { key: 'staff.unified_calendar.readiness', namespace: 'staff', description: 'Calendar readiness label', en: 'Readiness', ru: 'Готовность', th: 'ความพร้อม', status: 'needs_review' as const },
  { key: 'staff.unified_calendar.ready', namespace: 'staff', description: 'Calendar readiness: ready', en: 'Ready', ru: 'Готово', th: 'พร้อม', status: 'needs_review' as const },
  { key: 'staff.unified_calendar.needs_cleaning', namespace: 'staff', description: 'Calendar readiness: needs cleaning', en: 'Needs cleaning', ru: 'Нужна уборка', th: 'ต้องทำความสะอาด', status: 'needs_review' as const },
  { key: 'staff.unified_calendar.needs_inspection', namespace: 'staff', description: 'Calendar readiness: needs inspection', en: 'Needs inspection', ru: 'Нужна проверка', th: 'ต้องตรวจสอบ', status: 'needs_review' as const },
  { key: 'staff.unified_calendar.in_progress', namespace: 'staff', description: 'Calendar readiness: work in progress', en: 'In progress', ru: 'В работе', th: 'กำลังดำเนินการ', status: 'needs_review' as const },
  { key: 'staff.unified_calendar.channel_health', namespace: 'staff', description: 'Calendar channel health label', en: 'Channels', ru: 'Каналы', th: 'ช่องทาง', status: 'needs_review' as const },
  { key: 'staff.unified_calendar.channel_warning', namespace: 'staff', description: 'Calendar warning for non-healthy ARI channels', en: 'homes do not have fully verified healthy ARI. iCal/manual channels do not push rates or restrictions.', ru: 'объектов не имеют подтверждённого здорового ARI. iCal/ручные каналы не отправляют цены и ограничения.', th: 'ยูนิตยังไม่มี ARI ที่ยืนยันว่าทำงานสมบูรณ์ ช่องทาง iCal/แบบแมนนวลไม่ส่งราคาและข้อจำกัด', status: 'needs_review' as const },
  { key: 'staff.unified_calendar.rate_unavailable', namespace: 'staff', description: 'Calendar canonical rate unavailable', en: 'Rate unavailable', ru: 'Ставка недоступна', th: 'ไม่มีอัตราราคา', status: 'needs_review' as const },
  { key: 'staff.unified_calendar.effective_rate', namespace: 'staff', description: 'Calendar effective daily rate label', en: 'Effective daily rate', ru: 'Эффективная ставка за день', th: 'อัตรารายวันที่มีผล', status: 'needs_review' as const },
  { key: 'staff.unified_calendar.tasks', namespace: 'staff', description: 'Calendar link to housekeeping readiness queue', en: 'Housekeeping & readiness →', ru: 'Уборка и готовность →', th: 'แม่บ้านและความพร้อม →', status: 'needs_review' as const },

  { key: 'staff.tasks.back', namespace: 'staff', description: 'Readiness queue back link', en: '← Calendar', ru: '← Календарь', th: '← ปฏิทิน', status: 'needs_review' as const },
  { key: 'staff.tasks.title', namespace: 'staff', description: 'Readiness queue title', en: 'Housekeeping & readiness', ru: 'Уборка и готовность', th: 'แม่บ้านและความพร้อม', status: 'needs_review' as const },
  { key: 'staff.tasks.subtitle', namespace: 'staff', description: 'Readiness queue explanation', en: 'Turnover cleaning and inspection tasks generated by checkout. Check-in is blocked while overdue required tasks remain open.', ru: 'Задачи уборки и инспекции создаются при выезде. Заселение блокируется, пока обязательные просроченные задачи не закрыты.', th: 'งานทำความสะอาดและตรวจสอบถูกสร้างเมื่อเช็กเอาต์ ระบบจะบล็อกเช็กอินหากงานที่จำเป็นยังไม่เสร็จ', status: 'needs_review' as const },
  { key: 'staff.tasks.empty', namespace: 'staff', description: 'Readiness queue empty state', en: 'No open readiness tasks.', ru: 'Нет открытых задач по готовности.', th: 'ไม่มีงานความพร้อมที่เปิดอยู่', status: 'needs_review' as const },
  { key: 'staff.tasks.update_failed', namespace: 'staff', description: 'Readiness queue update error', en: 'Task update failed', ru: 'Не удалось обновить задачу', th: 'อัปเดตงานไม่สำเร็จ', status: 'needs_review' as const },
  { key: 'staff.tasks.due', namespace: 'staff', description: 'Readiness task due label', en: 'Due', ru: 'Срок', th: 'กำหนด', status: 'needs_review' as const },
  { key: 'staff.tasks.assign_me', namespace: 'staff', description: 'Readiness task assign action', en: 'Assign to me', ru: 'Назначить мне', th: 'มอบหมายให้ฉัน', status: 'needs_review' as const },
  { key: 'staff.tasks.start', namespace: 'staff', description: 'Readiness task start action', en: 'Start', ru: 'Начать', th: 'เริ่ม', status: 'needs_review' as const },
  { key: 'staff.tasks.inspected', namespace: 'staff', description: 'Readiness task inspected action', en: 'Inspected', ru: 'Проверено', th: 'ตรวจแล้ว', status: 'needs_review' as const },
  { key: 'staff.tasks.ready', namespace: 'staff', description: 'Readiness task ready action', en: 'Ready', ru: 'Готово', th: 'พร้อม', status: 'needs_review' as const },
];
