/** Completion keys for production PMS operating-space surfaces. */
export const PMS_COMPLETION_KEYS = [
  { key: 'staff.finance.back', namespace: 'staff', description: 'Production PMS: Back', en: 'Back', ru: 'Back', th: 'Back', status: 'needs_review' as const },
  { key: 'staff.finance.choose_property', namespace: 'staff', description: 'Production PMS: Choose Property', en: 'Choose Property', ru: 'Choose Property', th: 'Choose Property', status: 'needs_review' as const },
  { key: 'staff.finance.costs', namespace: 'staff', description: 'Production PMS: Costs', en: 'Costs', ru: 'Costs', th: 'Costs', status: 'needs_review' as const },
  { key: 'staff.finance.generate', namespace: 'staff', description: 'Production PMS: Generate', en: 'Generate', ru: 'Generate', th: 'Generate', status: 'needs_review' as const },
  { key: 'staff.finance.generate_hint', namespace: 'staff', description: 'Production PMS: Generate Hint', en: 'Generate Hint', ru: 'Generate Hint', th: 'Generate Hint', status: 'needs_review' as const },
  { key: 'staff.finance.generate_statement', namespace: 'staff', description: 'Production PMS: Generate Statement', en: 'Generate Statement', ru: 'Generate Statement', th: 'Generate Statement', status: 'needs_review' as const },
  { key: 'staff.finance.generating', namespace: 'staff', description: 'Production PMS: Generating', en: 'Generating', ru: 'Generating', th: 'Generating', status: 'needs_review' as const },
  { key: 'staff.finance.ledger', namespace: 'staff', description: 'Production PMS: Ledger', en: 'Ledger', ru: 'Ledger', th: 'Ledger', status: 'needs_review' as const },
  { key: 'staff.finance.no_ledger', namespace: 'staff', description: 'Production PMS: No Ledger', en: 'No Ledger', ru: 'No Ledger', th: 'No Ledger', status: 'needs_review' as const },
  { key: 'staff.finance.no_statements', namespace: 'staff', description: 'Production PMS: No Statements', en: 'No Statements', ru: 'No Statements', th: 'No Statements', status: 'needs_review' as const },
  { key: 'staff.finance.noi', namespace: 'staff', description: 'Production PMS: Noi', en: 'Noi', ru: 'Noi', th: 'Noi', status: 'needs_review' as const },
  { key: 'staff.finance.owner_share', namespace: 'staff', description: 'Production PMS: Owner Share', en: 'Owner Share', ru: 'Owner Share', th: 'Owner Share', status: 'needs_review' as const },
  { key: 'staff.finance.period_end', namespace: 'staff', description: 'Production PMS: Period End', en: 'Period End', ru: 'Period End', th: 'Period End', status: 'needs_review' as const },
  { key: 'staff.finance.period_start', namespace: 'staff', description: 'Production PMS: Period Start', en: 'Period Start', ru: 'Period Start', th: 'Period Start', status: 'needs_review' as const },
  { key: 'staff.finance.property', namespace: 'staff', description: 'Production PMS: Property', en: 'Property', ru: 'Property', th: 'Property', status: 'needs_review' as const },
  { key: 'staff.finance.revenue', namespace: 'staff', description: 'Production PMS: Revenue', en: 'Revenue', ru: 'Revenue', th: 'Revenue', status: 'needs_review' as const },
  { key: 'staff.finance.statement_created', namespace: 'staff', description: 'Production PMS: Statement Created', en: 'Statement Created', ru: 'Statement Created', th: 'Statement Created', status: 'needs_review' as const },
  { key: 'staff.finance.statement_error', namespace: 'staff', description: 'Production PMS: Statement Error', en: 'Statement Error', ru: 'Statement Error', th: 'Statement Error', status: 'needs_review' as const },
  { key: 'staff.finance.statements', namespace: 'staff', description: 'Production PMS: Statements', en: 'Statements', ru: 'Statements', th: 'Statements', status: 'needs_review' as const },
  { key: 'staff.finance.subtitle', namespace: 'staff', description: 'Production PMS: Subtitle', en: 'Subtitle', ru: 'Subtitle', th: 'Subtitle', status: 'needs_review' as const },
  { key: 'staff.finance.title', namespace: 'staff', description: 'Production PMS: Title', en: 'Title', ru: 'Title', th: 'Title', status: 'needs_review' as const },
  { key: 'staff.incidents.ack', namespace: 'staff', description: 'Production PMS: Ack', en: 'Ack', ru: 'Ack', th: 'Ack', status: 'needs_review' as const },
  { key: 'staff.incidents.assigned', namespace: 'staff', description: 'Production PMS: Assigned', en: 'Assigned', ru: 'Assigned', th: 'Assigned', status: 'needs_review' as const },
  { key: 'staff.incidents.back', namespace: 'staff', description: 'Production PMS: Back', en: 'Back', ru: 'Back', th: 'Back', status: 'needs_review' as const },
  { key: 'staff.incidents.create', namespace: 'staff', description: 'Production PMS: Create', en: 'Create', ru: 'Create', th: 'Create', status: 'needs_review' as const },
  { key: 'staff.incidents.created', namespace: 'staff', description: 'Production PMS: Created', en: 'Created', ru: 'Created', th: 'Created', status: 'needs_review' as const },
  { key: 'staff.incidents.description', namespace: 'staff', description: 'Production PMS: Description', en: 'Description', ru: 'Description', th: 'Description', status: 'needs_review' as const },
  { key: 'staff.incidents.empty', namespace: 'staff', description: 'Production PMS: Empty', en: 'Empty', ru: 'Empty', th: 'Empty', status: 'needs_review' as const },
  { key: 'staff.incidents.error', namespace: 'staff', description: 'Production PMS: Error', en: 'Error', ru: 'Error', th: 'Error', status: 'needs_review' as const },
  { key: 'staff.incidents.open', namespace: 'staff', description: 'Production PMS: Open', en: 'Open', ru: 'Open', th: 'Open', status: 'needs_review' as const },
  { key: 'staff.incidents.property', namespace: 'staff', description: 'Production PMS: Property', en: 'Property', ru: 'Property', th: 'Property', status: 'needs_review' as const },
  { key: 'staff.incidents.report', namespace: 'staff', description: 'Production PMS: Report', en: 'Report', ru: 'Report', th: 'Report', status: 'needs_review' as const },
  { key: 'staff.incidents.resolve', namespace: 'staff', description: 'Production PMS: Resolve', en: 'Resolve', ru: 'Resolve', th: 'Resolve', status: 'needs_review' as const },
  { key: 'staff.incidents.resolve_prompt', namespace: 'staff', description: 'Production PMS: Resolve Prompt', en: 'Resolve Prompt', ru: 'Resolve Prompt', th: 'Resolve Prompt', status: 'needs_review' as const },
  { key: 'staff.incidents.saving', namespace: 'staff', description: 'Production PMS: Saving', en: 'Saving', ru: 'Saving', th: 'Saving', status: 'needs_review' as const },
  { key: 'staff.incidents.start', namespace: 'staff', description: 'Production PMS: Start', en: 'Start', ru: 'Start', th: 'Start', status: 'needs_review' as const },
  { key: 'staff.incidents.subtitle', namespace: 'staff', description: 'Production PMS: Subtitle', en: 'Subtitle', ru: 'Subtitle', th: 'Subtitle', status: 'needs_review' as const },
  { key: 'staff.incidents.title', namespace: 'staff', description: 'Production PMS: Title', en: 'Title', ru: 'Title', th: 'Title', status: 'needs_review' as const },
  { key: 'staff.incidents.unassigned', namespace: 'staff', description: 'Production PMS: Unassigned', en: 'Unassigned', ru: 'Unassigned', th: 'Unassigned', status: 'needs_review' as const },
  { key: 'staff.incidents.updated', namespace: 'staff', description: 'Production PMS: Updated', en: 'Updated', ru: 'Updated', th: 'Updated', status: 'needs_review' as const },
  { key: 'staff.space.incidents', namespace: 'staff', description: 'Production PMS: Incidents', en: 'Incidents', ru: 'Incidents', th: 'Incidents', status: 'needs_review' as const },
  { key: 'staff.space.tasks_link', namespace: 'staff', description: 'Production PMS: Tasks Link', en: 'Tasks Link', ru: 'Tasks Link', th: 'Tasks Link', status: 'needs_review' as const },
  { key: 'staff.space_access.back', namespace: 'staff', description: 'Production PMS: Back', en: 'Back', ru: 'Back', th: 'Back', status: 'needs_review' as const },
  { key: 'staff.space_access.capabilities', namespace: 'staff', description: 'Production PMS: Capabilities', en: 'Capabilities', ru: 'Capabilities', th: 'Capabilities', status: 'needs_review' as const },
  { key: 'staff.space_access.create_team', namespace: 'staff', description: 'Production PMS: Create Team', en: 'Create Team', ru: 'Create Team', th: 'Create Team', status: 'needs_review' as const },
  { key: 'staff.space_access.edit', namespace: 'staff', description: 'Production PMS: Edit', en: 'Edit', ru: 'Edit', th: 'Edit', status: 'needs_review' as const },
  { key: 'staff.space_access.email', namespace: 'staff', description: 'Production PMS: Email', en: 'Email', ru: 'Email', th: 'Email', status: 'needs_review' as const },
  { key: 'staff.space_access.error', namespace: 'staff', description: 'Production PMS: Error', en: 'Error', ru: 'Error', th: 'Error', status: 'needs_review' as const },
  { key: 'staff.space_access.loading', namespace: 'staff', description: 'Production PMS: Loading', en: 'Loading', ru: 'Loading', th: 'Loading', status: 'needs_review' as const },
  { key: 'staff.space_access.member_hint', namespace: 'staff', description: 'Production PMS: Member Hint', en: 'Member Hint', ru: 'Member Hint', th: 'Member Hint', status: 'needs_review' as const },
  { key: 'staff.space_access.member_title', namespace: 'staff', description: 'Production PMS: Member Title', en: 'Member Title', ru: 'Member Title', th: 'Member Title', status: 'needs_review' as const },
  { key: 'staff.space_access.members', namespace: 'staff', description: 'Production PMS: Members', en: 'Members', ru: 'Members', th: 'Members', status: 'needs_review' as const },
  { key: 'staff.space_access.members_empty', namespace: 'staff', description: 'Production PMS: Members Empty', en: 'Members Empty', ru: 'Members Empty', th: 'Members Empty', status: 'needs_review' as const },
  { key: 'staff.space_access.no_capabilities', namespace: 'staff', description: 'Production PMS: No Capabilities', en: 'No Capabilities', ru: 'No Capabilities', th: 'No Capabilities', status: 'needs_review' as const },
  { key: 'staff.space_access.properties', namespace: 'staff', description: 'Production PMS: Properties', en: 'Properties', ru: 'Properties', th: 'Properties', status: 'needs_review' as const },
  { key: 'staff.space_access.properties_count', namespace: 'staff', description: 'Production PMS: Properties Count', en: 'Properties Count', ru: 'Properties Count', th: 'Properties Count', status: 'needs_review' as const },
  { key: 'staff.space_access.remove', namespace: 'staff', description: 'Production PMS: Remove', en: 'Remove', ru: 'Remove', th: 'Remove', status: 'needs_review' as const },
  { key: 'staff.space_access.remove_confirm', namespace: 'staff', description: 'Production PMS: Remove Confirm', en: 'Remove Confirm', ru: 'Remove Confirm', th: 'Remove Confirm', status: 'needs_review' as const },
  { key: 'staff.space_access.removed', namespace: 'staff', description: 'Production PMS: Removed', en: 'Removed', ru: 'Removed', th: 'Removed', status: 'needs_review' as const },
  { key: 'staff.space_access.save_member', namespace: 'staff', description: 'Production PMS: Save Member', en: 'Save Member', ru: 'Save Member', th: 'Save Member', status: 'needs_review' as const },
  { key: 'staff.space_access.saved', namespace: 'staff', description: 'Production PMS: Saved', en: 'Saved', ru: 'Saved', th: 'Saved', status: 'needs_review' as const },
  { key: 'staff.space_access.saving', namespace: 'staff', description: 'Production PMS: Saving', en: 'Saving', ru: 'Saving', th: 'Saving', status: 'needs_review' as const },
  { key: 'staff.space_access.select_all', namespace: 'staff', description: 'Production PMS: Select All', en: 'Select All', ru: 'Select All', th: 'Select All', status: 'needs_review' as const },
  { key: 'staff.space_access.subtitle', namespace: 'staff', description: 'Production PMS: Subtitle', en: 'Subtitle', ru: 'Subtitle', th: 'Subtitle', status: 'needs_review' as const },
  { key: 'staff.space_access.team_created', namespace: 'staff', description: 'Production PMS: Team Created', en: 'Team Created', ru: 'Team Created', th: 'Team Created', status: 'needs_review' as const },
  { key: 'staff.space_access.team_name', namespace: 'staff', description: 'Production PMS: Team Name', en: 'Team Name', ru: 'Team Name', th: 'Team Name', status: 'needs_review' as const },
  { key: 'staff.space_access.team_saved', namespace: 'staff', description: 'Production PMS: Team Saved', en: 'Team Saved', ru: 'Team Saved', th: 'Team Saved', status: 'needs_review' as const },
  { key: 'staff.space_access.teams', namespace: 'staff', description: 'Production PMS: Teams', en: 'Teams', ru: 'Teams', th: 'Teams', status: 'needs_review' as const },
  { key: 'staff.space_access.title', namespace: 'staff', description: 'Production PMS: Title', en: 'Title', ru: 'Title', th: 'Title', status: 'needs_review' as const },
  { key: 'staff.space_manage.active', namespace: 'staff', description: 'Production PMS: Active', en: 'Active', ru: 'Active', th: 'Active', status: 'needs_review' as const },
  { key: 'staff.space_manage.archived', namespace: 'staff', description: 'Production PMS: Archived', en: 'Archived', ru: 'Archived', th: 'Archived', status: 'needs_review' as const },
  { key: 'staff.space_manage.back', namespace: 'staff', description: 'Production PMS: Back', en: 'Back', ru: 'Back', th: 'Back', status: 'needs_review' as const },
  { key: 'staff.space_manage.cancel', namespace: 'staff', description: 'Production PMS: Cancel', en: 'Cancel', ru: 'Cancel', th: 'Cancel', status: 'needs_review' as const },
  { key: 'staff.space_manage.choose', namespace: 'staff', description: 'Production PMS: Choose', en: 'Choose', ru: 'Choose', th: 'Choose', status: 'needs_review' as const },
  { key: 'staff.space_manage.create', namespace: 'staff', description: 'Production PMS: Create', en: 'Create', ru: 'Create', th: 'Create', status: 'needs_review' as const },
  { key: 'staff.space_manage.created', namespace: 'staff', description: 'Production PMS: Created', en: 'Created', ru: 'Created', th: 'Created', status: 'needs_review' as const },
  { key: 'staff.space_manage.edit', namespace: 'staff', description: 'Production PMS: Edit', en: 'Edit', ru: 'Edit', th: 'Edit', status: 'needs_review' as const },
  { key: 'staff.space_manage.edit_action', namespace: 'staff', description: 'Production PMS: Edit Action', en: 'Edit Action', ru: 'Edit Action', th: 'Edit Action', status: 'needs_review' as const },
  { key: 'staff.space_manage.error', namespace: 'staff', description: 'Production PMS: Error', en: 'Error', ru: 'Error', th: 'Error', status: 'needs_review' as const },
  { key: 'staff.space_manage.existing', namespace: 'staff', description: 'Production PMS: Existing', en: 'Existing', ru: 'Existing', th: 'Existing', status: 'needs_review' as const },
  { key: 'staff.space_manage.hint', namespace: 'staff', description: 'Production PMS: Hint', en: 'Hint', ru: 'Hint', th: 'Hint', status: 'needs_review' as const },
  { key: 'staff.space_manage.key', namespace: 'staff', description: 'Production PMS: Key', en: 'Key', ru: 'Key', th: 'Key', status: 'needs_review' as const },
  { key: 'staff.space_manage.members_count', namespace: 'staff', description: 'Production PMS: Members Count', en: 'Members Count', ru: 'Members Count', th: 'Members Count', status: 'needs_review' as const },
  { key: 'staff.space_manage.name', namespace: 'staff', description: 'Production PMS: Name', en: 'Name', ru: 'Name', th: 'Name', status: 'needs_review' as const },
  { key: 'staff.space_manage.organization', namespace: 'staff', description: 'Production PMS: Organization', en: 'Organization', ru: 'Organization', th: 'Organization', status: 'needs_review' as const },
  { key: 'staff.space_manage.properties', namespace: 'staff', description: 'Production PMS: Properties', en: 'Properties', ru: 'Properties', th: 'Properties', status: 'needs_review' as const },
  { key: 'staff.space_manage.properties_count', namespace: 'staff', description: 'Production PMS: Properties Count', en: 'Properties Count', ru: 'Properties Count', th: 'Properties Count', status: 'needs_review' as const },
  { key: 'staff.space_manage.properties_hint', namespace: 'staff', description: 'Production PMS: Properties Hint', en: 'Properties Hint', ru: 'Properties Hint', th: 'Properties Hint', status: 'needs_review' as const },
  { key: 'staff.space_manage.save', namespace: 'staff', description: 'Production PMS: Save', en: 'Save', ru: 'Save', th: 'Save', status: 'needs_review' as const },
  { key: 'staff.space_manage.saving', namespace: 'staff', description: 'Production PMS: Saving', en: 'Saving', ru: 'Saving', th: 'Saving', status: 'needs_review' as const },
  { key: 'staff.space_manage.search', namespace: 'staff', description: 'Production PMS: Search', en: 'Search', ru: 'Search', th: 'Search', status: 'needs_review' as const },
  { key: 'staff.space_manage.selected', namespace: 'staff', description: 'Production PMS: Selected', en: 'Selected', ru: 'Selected', th: 'Selected', status: 'needs_review' as const },
  { key: 'staff.space_manage.status', namespace: 'staff', description: 'Production PMS: Status', en: 'Status', ru: 'Status', th: 'Status', status: 'needs_review' as const },
  { key: 'staff.space_manage.subtitle', namespace: 'staff', description: 'Production PMS: Subtitle', en: 'Subtitle', ru: 'Subtitle', th: 'Subtitle', status: 'needs_review' as const },
  { key: 'staff.space_manage.teams_count', namespace: 'staff', description: 'Production PMS: Teams Count', en: 'Teams Count', ru: 'Teams Count', th: 'Teams Count', status: 'needs_review' as const },
  { key: 'staff.space_manage.title', namespace: 'staff', description: 'Production PMS: Title', en: 'Title', ru: 'Title', th: 'Title', status: 'needs_review' as const },
  { key: 'staff.space_manage.updated', namespace: 'staff', description: 'Production PMS: Updated', en: 'Updated', ru: 'Updated', th: 'Updated', status: 'needs_review' as const },
  { key: 'staff.spaces.manage', namespace: 'staff', description: 'Production PMS: Manage', en: 'Manage', ru: 'Manage', th: 'Manage', status: 'needs_review' as const },
  { key: 'staff.stay_360.completed_stays', namespace: 'staff', description: 'Production PMS: Completed Stays', en: 'Completed Stays', ru: 'Completed Stays', th: 'Completed Stays', status: 'needs_review' as const },
  { key: 'staff.stay_360.conversation', namespace: 'staff', description: 'Production PMS: Conversation', en: 'Conversation', ru: 'Conversation', th: 'Conversation', status: 'needs_review' as const },
  { key: 'staff.stay_360.crm_stage', namespace: 'staff', description: 'Production PMS: Crm Stage', en: 'Crm Stage', ru: 'Crm Stage', th: 'Crm Stage', status: 'needs_review' as const },
  { key: 'staff.stay_360.guest_context', namespace: 'staff', description: 'Production PMS: Guest Context', en: 'Guest Context', ru: 'Guest Context', th: 'Guest Context', status: 'needs_review' as const },
  { key: 'staff.stay_360.open_issues', namespace: 'staff', description: 'Production PMS: Open Issues', en: 'Open Issues', ru: 'Open Issues', th: 'Open Issues', status: 'needs_review' as const },
];
