/** Project-scoped team administration labels, shared by admin/manager operation surfaces. */
export const PROJECT_TEAM_KEYS = [
  { key: 'ops.team.back', namespace: 'ops', description: 'Return to operations', en: '← Operations', ru: '← Операции', th: '← งานปฏิบัติการ', status: 'needs_review' as const },
  { key: 'ops.team.title', namespace: 'ops', description: 'Project team heading', en: 'Project team', ru: 'Команда проекта', th: 'ทีมโครงการ', status: 'needs_review' as const },
  { key: 'ops.team.description', namespace: 'ops', description: 'Project team safety scope', en: 'Assign existing myUNO users as onsite hosts only in your authorized projects. Platform roles, financial access and management mandates remain administrator-controlled.', ru: 'Назначайте действующих пользователей myUNO сотрудниками только в разрешённых проектах. Общие роли, финансы и договоры управления остаются под контролем администратора.', th: 'กำหนดพนักงานหน้างานเฉพาะโครงการที่คุณมีสิทธิ์ บทบาทระดับแพลตฟอร์ม การเงิน และสิทธิ์การบริหารยังอยู่ภายใต้ผู้ดูแลระบบ', status: 'needs_review' as const },
  { key: 'ops.team.advanced', namespace: 'ops', description: 'Advanced people controls', en: 'Invite new people or manage advanced permissions →', ru: 'Пригласить сотрудника или настроить расширенные права →', th: 'เชิญบุคคลใหม่หรือจัดการสิทธิ์ขั้นสูง →', status: 'needs_review' as const },
  { key: 'ops.team.project', namespace: 'ops', description: 'Project selector', en: 'Managed project', ru: 'Проект под управлением', th: 'โครงการที่ดูแล', status: 'needs_review' as const },
  { key: 'ops.team.email', namespace: 'ops', description: 'Existing person email', en: "Existing user's email", ru: 'Email действующего пользователя', th: 'อีเมลผู้ใช้ที่มีอยู่', status: 'needs_review' as const },
  { key: 'ops.team.assign', namespace: 'ops', description: 'Assign scoped onsite role', en: 'Assign onsite host', ru: 'Назначить сотрудника', th: 'มอบหมายพนักงานหน้างาน', status: 'needs_review' as const },
  { key: 'ops.team.invite_note', namespace: 'ops', description: 'Active account prerequisite', en: 'The person must have an active myUNO account. New invitations are administered in People & Roles.', ru: 'У сотрудника должна быть активная учётная запись myUNO. Новые приглашения оформляются в разделе People & Roles.', th: 'บุคคลนั้นต้องมีบัญชี myUNO ที่ใช้งานอยู่ คำเชิญใหม่จัดการใน People & Roles', status: 'needs_review' as const },
  { key: 'ops.team.members', namespace: 'ops', description: 'Project onsite hosts', en: 'Onsite hosts for this project', ru: 'Сотрудники проекта', th: 'พนักงานหน้างานของโครงการ', status: 'needs_review' as const },
  { key: 'ops.team.loading', namespace: 'ops', description: 'Team load state', en: 'Refreshing…', ru: 'Обновление…', th: 'กำลังอัปเดต…', status: 'needs_review' as const },
  { key: 'ops.team.empty', namespace: 'ops', description: 'No team members', en: 'No onsite hosts assigned yet.', ru: 'Сотрудники пока не назначены.', th: 'ยังไม่ได้มอบหมายพนักงานหน้างาน', status: 'needs_review' as const },
  { key: 'ops.team.revoke', namespace: 'ops', description: 'Revoke project team grant', en: 'Revoke project role', ru: 'Отозвать доступ к проекту', th: 'เพิกถอนบทบาทในโครงการ', status: 'needs_review' as const },
  { key: 'ops.team.admin_managed', namespace: 'ops', description: 'Grant belongs to another administrator', en: 'Admin-managed access', ru: 'Доступ под управлением администратора', th: 'สิทธิ์ที่ผู้ดูแลระบบจัดการ', status: 'needs_review' as const },
  { key: 'ops.team.assigned', namespace: 'ops', description: 'Team assigned confirmation', en: 'Onsite host access assigned.', ru: 'Доступ сотруднику назначен.', th: 'มอบสิทธิ์พนักงานหน้างานแล้ว', status: 'needs_review' as const },
  { key: 'ops.team.revoked', namespace: 'ops', description: 'Team revoked confirmation', en: 'Project access revoked.', ru: 'Доступ к проекту отозван.', th: 'เพิกถอนสิทธิ์โครงการแล้ว', status: 'needs_review' as const },
];
