export const PROJECT_PORTAL_KEYS = [
  {
    key: 'project_page.nearby.kicker',
    namespace: 'project_page',
    description: 'Project portal: nearby places section kicker',
    en: 'Around the project',
    ru: 'Рядом с проектом',
    th: 'รอบโครงการ',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nearby.title',
    namespace: 'project_page',
    description: 'Project portal: nearby places section title',
    en: 'What is nearby',
    ru: 'Что находится рядом',
    th: 'สถานที่ใกล้เคียง',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nearby.body',
    namespace: 'project_page',
    description: 'Project portal: nearby places section explanatory copy',
    en: 'Useful places around the residence, with distance and travel estimates where they have been provided or can be calculated.',
    ru: 'Полезные места рядом с резиденцией — с расстояниями и временем в пути, когда они указаны или могут быть рассчитаны.',
    th: 'สถานที่ที่เป็นประโยชน์รอบที่พัก พร้อมระยะทางและเวลาเดินทางเมื่อมีข้อมูลหรือสามารถคำนวณได้',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nearby.distance',
    namespace: 'project_page',
    description: 'Project portal: nearby place distance',
    en: '{distance} away',
    ru: '{distance}',
    th: 'ห่าง {distance}',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nearby.walk',
    namespace: 'project_page',
    description: 'Project portal: walking estimate',
    en: '{minutes} min walk',
    ru: '{minutes} мин пешком',
    th: 'เดิน {minutes} นาที',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nearby.drive',
    namespace: 'project_page',
    description: 'Project portal: driving estimate',
    en: '{minutes} min drive',
    ru: '{minutes} мин на машине',
    th: 'ขับรถ {minutes} นาที',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nearby.open_map',
    namespace: 'project_page',
    description: 'Project portal: open nearby place in map',
    en: 'Open map →',
    ru: 'Открыть карту →',
    th: 'เปิดแผนที่ →',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nav.stay',
    namespace: 'project_page',
    description: 'Project portal navigation: stay availability',
    en: 'Stay',
    ru: 'Проживание',
    th: 'เข้าพัก',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nav.homes',
    namespace: 'project_page',
    description: 'Project portal navigation: homes',
    en: 'Homes',
    ru: 'Объекты',
    th: 'ที่พัก',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nav.amenities',
    namespace: 'project_page',
    description: 'Project portal navigation: amenities and facilities',
    en: 'Amenities',
    ru: 'Инфраструктура',
    th: 'สิ่งอำนวยความสะดวก',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nav.services',
    namespace: 'project_page',
    description: 'Project portal navigation: services',
    en: 'Services',
    ru: 'Сервисы',
    th: 'บริการ',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nav.nearby',
    namespace: 'project_page',
    description: 'Project portal navigation: nearby places',
    en: 'Nearby',
    ru: 'Рядом',
    th: 'ใกล้เคียง',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nav.location',
    namespace: 'project_page',
    description: 'Project portal navigation: location',
    en: 'Location',
    ru: 'Локация',
    th: 'ที่ตั้ง',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.nav.contact',
    namespace: 'project_page',
    description: 'Project portal navigation: project inquiry',
    en: 'Ask us',
    ru: 'Задать вопрос',
    th: 'สอบถามเรา',
    status: 'needs_review' as const,
  },
];
