export const PROJECT_RESTYLE_KEYS = [
  {
    key: 'project_category.inquiry_unit',
    namespace: 'project_category',
    description: 'Project category: CTA on a home without online booking',
    en: 'Ask about this home →',
    ru: 'Узнать об этом доме →',
    th: 'บ้านหลังนี้สอบถามได้ →',
    status: 'needs_review' as const,
  },
  {
    key: 'project_category.pending',
    namespace: 'project_category',
    description: 'Project category: note when photos or booking terms are incomplete',
    en: 'Exact photos or online booking terms are still being completed.',
    ru: 'Точные фотографии и условия онлайн-бронирования ещё уточняются.',
    th: 'รูปภาพและเงื่อนไขการจองออนไลน์อยู่ระหว่างจัดทำ',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.units.details_pending',
    namespace: 'project_page',
    description: 'Project landing: unit card without photo or price',
    en: 'Details are being completed.',
    ru: 'Информация уточняется.',
    th: 'รายละเอียดอยู่ระหว่างจัดทำ',
    status: 'needs_review' as const,
  },
  {
    key: 'project_page.units.inquiry',
    namespace: 'project_page',
    description: 'Project landing: CTA for a home without online booking',
    en: 'Send an inquiry →',
    ru: 'Отправить запрос →',
    th: 'ส่งคำถาม →',
    status: 'needs_review' as const,
  },
  {
    key: 'projects.hub.no_photo',
    namespace: 'projects',
    description: 'Projects hub: illustrative image badge',
    en: 'Sample photo · to be replaced',
    ru: 'Пример фото · будет заменено',
    th: 'ภาพตัวอย่าง · จะเปลี่ยนเป็นภาพจริง',
    status: 'needs_review' as const,
  },
  {
    key: 'projects.hub.responsibility_project',
    namespace: 'projects',
    description: 'Projects hub: verified operator of the whole project',
    en: 'Operations managed by {org}',
    ru: 'Управление осуществляет {org}',
    th: 'ดูแลโดย {org}',
    status: 'needs_review' as const,
  },
  {
    key: 'projects.hub.responsibility_selected',
    namespace: 'projects',
    description: 'Projects hub: verified operator of selected homes',
    en: 'Selected homes managed by {org}',
    ru: 'Отдельными домами управляет {org}',
    th: 'บ้านบางหลังดูแลโดย {org}',
    status: 'needs_review' as const,
  },
];
