/** Property application copy. All language drafts require editorial review before approval. */
export const PROPERTY_ONBOARDING_KEYS = [
  {
    key: 'property.onboard.back_listings',
    en: '← My listings',
    ru: '← Мои объявления',
    th: '← ประกาศของฉัน',
    zh: '← 我的房源',
  },
  {
    key: 'property.onboard.kicker',
    en: 'ADD A PROPERTY',
    ru: 'ДОБАВИТЬ ОБЪЕКТ',
    th: 'เพิ่มทรัพย์สิน',
    zh: '添加房源',
  },
  {
    key: 'property.onboard.title',
    en: 'Tell us about your place',
    ru: 'Расскажите о вашем объекте',
    th: 'บอกเราเกี่ยวกับที่พักของคุณ',
    zh: '介绍您的房源',
  },
  {
    key: 'property.onboard.intro',
    en: 'Save your progress at any time. The property listing is published only after myUNO review and approval.',
    ru: 'Сохраняйте черновик на любом шаге и возвращайтесь к нему позже. Объект появится на сайте только после проверки и одобрения myUNO.',
    th: 'บันทึกฉบับร่างได้ทุกขั้นตอนและกลับมาทำต่อภายหลัง ประกาศที่พักจะเผยแพร่หลังจาก myUNO ตรวจสอบและอนุมัติแล้วเท่านั้น',
    zh: '您可以随时保存草稿并稍后继续。只有经过 myUNO 审核批准后，房源才会公开。',
  },
  {
    key: 'property.onboard.steps.label',
    en: 'Property application steps',
    ru: 'Шаги добавления объекта',
    th: 'ขั้นตอนการเพิ่มทรัพย์สิน',
    zh: '房源申请步骤',
  },
  {
    key: 'property.onboard.steps.kind',
    en: 'Your property',
    ru: 'Ваш объект',
    th: 'ทรัพย์สินของคุณ',
    zh: '您的房源',
  },
  {
    key: 'property.onboard.steps.residence',
    en: 'Residence',
    ru: 'Комплекс',
    th: 'โครงการ',
    zh: '住宅项目',
  },
  {
    key: 'property.onboard.steps.details',
    en: 'Home details',
    ru: 'Об объекте',
    th: 'รายละเอียดที่พัก',
    zh: '房源详情',
  },
  {
    key: 'property.onboard.steps.photos',
    en: 'Photos',
    ru: 'Фотографии',
    th: 'รูปภาพ',
    zh: '照片',
  },
  {
    key: 'property.onboard.steps.offers',
    en: 'Offers and management',
    ru: 'Условия и управление',
    th: 'ข้อเสนอและการจัดการ',
    zh: '出租、出售与管理',
  },
  {
    key: 'property.onboard.steps.review',
    en: 'Review application',
    ru: 'Проверка заявки',
    th: 'ตรวจสอบใบสมัคร',
    zh: '检查申请',
  },
  {
    key: 'property.onboard.resume',
    en: 'Continue an earlier application',
    ru: 'Продолжить заполнение заявки',
    th: 'ดำเนินการใบสมัครเดิมต่อ',
    zh: '继续之前的申请',
  },
  {
    key: 'property.onboard.untitled',
    en: 'Untitled property',
    ru: 'Объект без названия',
    th: 'ทรัพย์สินที่ยังไม่มีชื่อ',
    zh: '未命名房源',
  },
  { key: 'property.onboard.status.draft', en: 'Draft', ru: 'Черновик', th: 'ฉบับร่าง', zh: '草稿' },
  {
    key: 'property.onboard.status.submitted',
    en: 'Under review',
    ru: 'На проверке',
    th: 'อยู่ระหว่างตรวจสอบ',
    zh: '审核中',
  },
  {
    key: 'property.onboard.status.converted',
    en: 'Property record created or linked',
    ru: 'Объект создан или найден в системе',
    th: 'สร้างหรือเชื่อมข้อมูลทรัพย์สินแล้ว',
    zh: '已创建或关联房源记录',
  },
  {
    key: 'property.onboard.status.unknown',
    en: 'Status unavailable',
    ru: 'Статус недоступен',
    th: 'ไม่สามารถแสดงสถานะได้',
    zh: '状态暂不可用',
  },
  {
    key: 'property.onboard.converted',
    en: 'Your application is linked to a new or existing property record. The current status and outstanding checks are shown below.',
    ru: 'Ваша заявка связана с новым или существующим объектом в системе. Ниже показаны текущий этап и незавершённые проверки.',
    th: 'ใบสมัครของคุณเชื่อมกับข้อมูลทรัพย์สินใหม่หรือที่มีอยู่แล้ว สถานะปัจจุบันและรายการตรวจสอบที่ค้างอยู่แสดงด้านล่าง',
    zh: '您的申请已关联至新建或现有房源记录。当前状态及待完成的检查如下。',
  },
  {
    key: 'property.onboard.state.label',
    en: 'Onboarding status',
    ru: 'Этап подключения',
    th: 'สถานะการเริ่มใช้งาน',
    zh: '接入状态',
  },
  {
    key: 'property.onboard.blockers.title',
    en: 'Still to complete',
    ru: 'Что ещё нужно завершить',
    th: 'สิ่งที่ยังต้องดำเนินการ',
    zh: '待完成事项',
  },
  {
    key: 'property.onboard.blockers.none',
    en: 'No outstanding checks are recorded here. This alone does not confirm publication or booking availability.',
    ru: 'Незавершённых проверок здесь не указано. Само по себе это не означает, что объект опубликован или доступен для бронирования.',
    th: 'ไม่มีรายการตรวจสอบค้างอยู่ในหน้านี้ แต่ไม่ได้ยืนยันว่าประกาศเผยแพร่หรือเปิดรับการจองแล้ว',
    zh: '此处没有记录待完成的检查，但这不代表房源已发布或可以预订。',
  },
  {
    key: 'property.onboard.settings',
    en: 'My listings and property settings',
    ru: 'Мои объявления и настройки объектов',
    th: 'ประกาศและการตั้งค่าทรัพย์สินของฉัน',
    zh: '我的房源与设置',
  },
  {
    key: 'property.onboard.submitted',
    en: 'Your application is under review. The myUNO team will verify your relationship to the property and permissions before activation.',
    ru: 'Заявка отправлена на проверку. Перед активацией команда myUNO проверит вашу связь с объектом и необходимые полномочия.',
    th: 'ใบสมัครอยู่ระหว่างตรวจสอบ ทีม myUNO จะยืนยันความเกี่ยวข้องของคุณกับทรัพย์สินและสิทธิ์ก่อนเปิดใช้งาน',
    zh: '您的申请正在审核中。myUNO 团队将在启用前核实您与房源的关系及相关权限。',
  },
  {
    key: 'property.onboard.kind.home',
    en: 'One home',
    ru: 'Отдельный объект',
    th: 'ที่พักหนึ่งยูนิต',
    zh: '单套房源',
  },
  {
    key: 'property.onboard.kind.home_hint',
    en: 'Apartment, condo, villa or house',
    ru: 'Квартира, апартаменты, вилла или дом',
    th: 'อพาร์ตเมนต์ คอนโด วิลล่า หรือบ้าน',
    zh: '公寓、产权公寓、别墅或住宅',
  },
  {
    key: 'property.onboard.kind.resort',
    en: 'An entire property',
    ru: 'Целый комплекс',
    th: 'โครงการทั้งแห่ง',
    zh: '整个物业项目',
  },
  {
    key: 'property.onboard.kind.resort_hint',
    en: 'Resort, hotel or villa estate',
    ru: 'Курорт, отель или комплекс вилл',
    th: 'รีสอร์ต โรงแรม หรือโครงการวิลล่า',
    zh: '度假村、酒店或别墅社区',
  },
  {
    key: 'property.onboard.kind.management',
    en: 'I represent a management company',
    ru: 'Я представляю управляющую компанию',
    th: 'ฉันเป็นตัวแทนบริษัทจัดการ',
    zh: '我代表物业管理公司',
  },
  {
    key: 'property.onboard.kind.management_hint',
    en: 'Submit properties on behalf of owners',
    ru: 'Добавление объектов от имени собственников',
    th: 'ส่งข้อมูลทรัพย์สินในนามเจ้าของ',
    zh: '代表业主提交房源',
  },
  {
    key: 'property.onboard.residence.search',
    en: 'Find an existing residence',
    ru: 'Найдите комплекс в списке',
    th: 'ค้นหาโครงการที่มีอยู่',
    zh: '查找已有住宅项目',
  },
  {
    key: 'property.onboard.residence.search_placeholder',
    en: 'Search by building or address',
    ru: 'Название комплекса или адрес',
    th: 'ค้นหาจากชื่ออาคารหรือที่อยู่',
    zh: '按楼宇名称或地址搜索',
  },
  {
    key: 'property.onboard.residence.not_listed',
    en: 'My residence is not listed',
    ru: 'Моего комплекса нет в списке',
    th: 'ไม่มีโครงการของฉันในรายการ',
    zh: '列表中没有我的住宅项目',
  },
  {
    key: 'property.onboard.residence.name_placeholder',
    en: 'Name of the complex or standalone property',
    ru: 'Название комплекса или отдельно стоящего объекта',
    th: 'ชื่อโครงการหรือทรัพย์สินแยกเดี่ยว',
    zh: '住宅项目或独立物业名称',
  },
  {
    key: 'property.onboard.residence.duplicate_hint',
    en: 'A new residence is checked for duplicates before its record is created.',
    ru: 'Перед созданием нового комплекса команда проверит, нет ли его уже в системе.',
    th: 'ทีมงานจะตรวจสอบข้อมูลซ้ำก่อนสร้างโครงการใหม่',
    zh: '创建新住宅项目记录前，团队会检查是否已有相同项目。',
  },
  {
    key: 'property.onboard.residence.details',
    en: 'Tell us about this residence',
    ru: 'Расскажите о комплексе',
    th: 'บอกเราเกี่ยวกับโครงการนี้',
    zh: '介绍此住宅项目',
  },
  {
    key: 'property.onboard.residence.type',
    en: 'Property type',
    ru: 'Тип комплекса',
    th: 'ประเภทโครงการ',
    zh: '物业项目类型',
  },
  {
    key: 'property.onboard.type.condominium',
    en: 'Condominium',
    ru: 'Кондоминиум',
    th: 'คอนโดมิเนียม',
    zh: '产权公寓',
  },
  {
    key: 'property.onboard.type.resort',
    en: 'Resort / hotel',
    ru: 'Курорт / отель',
    th: 'รีสอร์ต / โรงแรม',
    zh: '度假村／酒店',
  },
  {
    key: 'property.onboard.type.villa_estate',
    en: 'Villa estate',
    ru: 'Комплекс вилл',
    th: 'โครงการวิลล่า',
    zh: '别墅社区',
  },
  {
    key: 'property.onboard.type.standalone',
    en: 'Standalone property',
    ru: 'Отдельно стоящий объект',
    th: 'ทรัพย์สินแยกเดี่ยว',
    zh: '独立物业',
  },
  {
    key: 'property.onboard.residence.address',
    en: 'Address',
    ru: 'Адрес',
    th: 'ที่อยู่',
    zh: '地址',
  },
  {
    key: 'property.onboard.residence.address_placeholder',
    en: 'Street, district, city',
    ru: 'Улица, район, город',
    th: 'ถนน เขต/อำเภอ เมือง',
    zh: '街道、区域、城市',
  },
  { key: 'property.onboard.residence.area', en: 'Area', ru: 'Район', th: 'พื้นที่', zh: '区域' },
  {
    key: 'property.onboard.residence.area_placeholder',
    en: 'Select area',
    ru: 'Выберите район',
    th: 'เลือกพื้นที่',
    zh: '选择区域',
  },
  {
    key: 'property.onboard.residence.latitude',
    en: 'Latitude',
    ru: 'Широта',
    th: 'ละติจูด',
    zh: '纬度',
  },
  {
    key: 'property.onboard.residence.longitude',
    en: 'Longitude',
    ru: 'Долгота',
    th: 'ลองจิจูด',
    zh: '经度',
  },
  {
    key: 'property.onboard.residence.location_hint',
    en: 'You can copy coordinates from a map app. The team will verify the location.',
    ru: 'Координаты можно скопировать из приложения с картами. Команда проверит местоположение.',
    th: 'คัดลอกพิกัดจากแอปแผนที่ได้ ทีมงานจะตรวจสอบตำแหน่ง',
    zh: '您可以从地图应用复制坐标。团队将核实位置。',
  },
  {
    key: 'property.onboard.residence.photos',
    en: 'Shared areas and building photos',
    ru: 'Фото комплекса и общих зон',
    th: 'รูปอาคารและพื้นที่ส่วนกลาง',
    zh: '楼宇与公共区域照片',
  },
  {
    key: 'property.onboard.residence.photo_count',
    en: 'Project photos: {count}. The first photo is the proposed cover.',
    ru: 'Фото комплекса: {count}. Первое фото предлагается для обложки.',
    th: 'รูปโครงการ: {count} รูปแรกเป็นรูปหน้าปกที่เสนอ',
    zh: '项目照片：{count}。第一张照片将作为建议封面。',
  },
  {
    key: 'property.onboard.residence.photo_alt',
    en: 'Residence photo {number}',
    ru: 'Фото комплекса {number}',
    th: 'รูปโครงการ {number}',
    zh: '住宅项目照片 {number}',
  },
  {
    key: 'property.onboard.residence.empty',
    en: 'No matching residence found. You can enter a new one below.',
    ru: 'Подходящий комплекс не найден. Ниже можно указать новый.',
    th: 'ไม่พบโครงการที่ตรงกัน คุณกรอกโครงการใหม่ด้านล่างได้',
    zh: '未找到匹配的住宅项目。您可以在下方填写新项目。',
  },
  {
    key: 'property.onboard.details.reuse_hint',
    en: 'First check whether your home is already listed. Select it to avoid creating a duplicate.',
    ru: 'Сначала проверьте, есть ли ваш объект в списке. Выберите его, чтобы не создавать дубликат.',
    th: 'ตรวจสอบก่อนว่ามีที่พักของคุณในรายการแล้วหรือไม่ เลือกที่พักนั้นเพื่อไม่ให้เกิดข้อมูลซ้ำ',
    zh: '请先检查列表中是否已有您的房源。选择现有房源可避免重复创建。',
  },
  {
    key: 'property.onboard.details.search',
    en: 'Search existing homes',
    ru: 'Найдите объект в комплексе',
    th: 'ค้นหาที่พักที่มีอยู่',
    zh: '搜索已有房源',
  },
  {
    key: 'property.onboard.details.search_placeholder',
    en: 'Unit number, villa name or floor',
    ru: 'Номер квартиры, название виллы или этаж',
    th: 'หมายเลขยูนิต ชื่อวิลล่า หรือชั้น',
    zh: '房号、别墅名称或楼层',
  },
  {
    key: 'property.onboard.details.summary',
    en: 'Bedrooms: {bedrooms} · Bathrooms: {bathrooms}',
    ru: 'Спальни: {bedrooms} · Ванные: {bathrooms}',
    th: 'ห้องนอน: {bedrooms} · ห้องน้ำ: {bathrooms}',
    zh: '卧室：{bedrooms} · 浴室：{bathrooms}',
  },
  {
    key: 'property.onboard.details.floor_summary',
    en: 'Floor: {floor}',
    ru: 'Этаж: {floor}',
    th: 'ชั้น: {floor}',
    zh: '楼层：{floor}',
  },
  {
    key: 'property.onboard.details.area_summary',
    en: '{area} m²',
    ru: '{area} м²',
    th: '{area} ตร.ม.',
    zh: '{area} 平方米',
  },
  {
    key: 'property.onboard.details.not_listed',
    en: 'My home is not listed',
    ru: 'Моего объекта нет в списке',
    th: 'ไม่มีที่พักของฉันในรายการ',
    zh: '列表中没有我的房源',
  },
  {
    key: 'property.onboard.details.empty',
    en: 'No matching homes are available in this list.',
    ru: 'В этом списке подходящих объектов нет.',
    th: 'ไม่มีที่พักที่ตรงกันในรายการนี้',
    zh: '此列表中没有匹配的房源。',
  },
  {
    key: 'property.onboard.details.name',
    en: 'Home name or number',
    ru: 'Название или номер объекта',
    th: 'ชื่อหรือหมายเลขที่พัก',
    zh: '房源名称或编号',
  },
  {
    key: 'property.onboard.details.name_placeholder',
    en: 'For example: Building F, 705',
    ru: 'Например: корпус F, квартира 705',
    th: 'ตัวอย่าง: อาคาร F ห้อง 705',
    zh: '例如：F 栋 705 室',
  },
  {
    key: 'property.onboard.details.type',
    en: 'Home type',
    ru: 'Тип объекта',
    th: 'ประเภทที่พัก',
    zh: '房源类型',
  },
  {
    key: 'property.onboard.type.apartment',
    en: 'Apartment',
    ru: 'Апартаменты',
    th: 'อพาร์ตเมนต์',
    zh: '公寓',
  },
  { key: 'property.onboard.type.villa', en: 'Villa', ru: 'Вилла', th: 'วิลล่า', zh: '别墅' },
  { key: 'property.onboard.type.house', en: 'House', ru: 'Дом', th: 'บ้าน', zh: '住宅' },
  {
    key: 'property.onboard.details.max_guests',
    en: 'Maximum guests',
    ru: 'Максимум гостей',
    th: 'จำนวนผู้เข้าพักสูงสุด',
    zh: '最多入住人数',
  },
  {
    key: 'property.onboard.details.bedrooms',
    en: 'Bedrooms',
    ru: 'Спальни',
    th: 'ห้องนอน',
    zh: '卧室',
  },
  {
    key: 'property.onboard.details.bathrooms',
    en: 'Bathrooms',
    ru: 'Ванные комнаты',
    th: 'ห้องน้ำ',
    zh: '浴室',
  },
  {
    key: 'property.onboard.details.size',
    en: 'Area (m²)',
    ru: 'Площадь (м²)',
    th: 'พื้นที่ (ตร.ม.)',
    zh: '面积（平方米）',
  },
  { key: 'property.onboard.details.floor', en: 'Floor', ru: 'Этаж', th: 'ชั้น', zh: '楼层' },
  {
    key: 'property.onboard.details.description',
    en: 'Describe your home',
    ru: 'Описание объекта',
    th: 'อธิบายที่พักของคุณ',
    zh: '房源描述',
  },
  {
    key: 'property.onboard.details.description_placeholder',
    en: 'Layout, features and other useful details',
    ru: 'Планировка, особенности и другие полезные сведения',
    th: 'ผังห้อง จุดเด่น และรายละเอียดที่เป็นประโยชน์',
    zh: '布局、特色及其他实用信息',
  },
  {
    key: 'property.onboard.photos.hint',
    en: 'Upload photos of this home. Photos of shared areas belong to the residence and are managed separately by authorized editors.',
    ru: 'Загрузите фотографии именно этого объекта. Фото общих зон относятся к комплексу и редактируются отдельно пользователями с соответствующими правами.',
    th: 'อัปโหลดรูปที่พักนี้ รูปพื้นที่ส่วนกลางเป็นของโครงการและจัดการแยกโดยผู้มีสิทธิ์แก้ไข',
    zh: '请上传此房源的照片。公共区域照片属于住宅项目，由授权编辑者单独管理。',
  },
  {
    key: 'property.onboard.photos.upload',
    en: 'Add home photos',
    ru: 'Добавить фотографии объекта',
    th: 'เพิ่มรูปที่พัก',
    zh: '添加房源照片',
  },
  {
    key: 'property.onboard.photos.count',
    en: 'Attached photos: {count}. Up to 50 photos, 8 MB each. The first photo becomes the cover.',
    ru: 'Прикреплено фото: {count}. До 50 фотографий, не более 8 МБ каждая. Первое фото станет обложкой.',
    th: 'รูปที่แนบ: {count} สูงสุด 50 รูป รูปละไม่เกิน 8 MB รูปแรกจะเป็นหน้าปก',
    zh: '已附照片：{count}。最多 50 张，每张不超过 8 MB。第一张照片将作为封面。',
  },
  {
    key: 'property.onboard.photos.alt',
    en: 'Home photo {number}',
    ru: 'Фото объекта {number}',
    th: 'รูปที่พัก {number}',
    zh: '房源照片 {number}',
  },
  {
    key: 'property.onboard.photos.cover',
    en: 'Set cover',
    ru: 'Сделать обложкой',
    th: 'ตั้งเป็นหน้าปก',
    zh: '设为封面',
  },
  {
    key: 'property.onboard.photos.left',
    en: 'Move left',
    ru: 'Сдвинуть влево',
    th: 'เลื่อนไปทางซ้าย',
    zh: '向左移动',
  },
  { key: 'property.onboard.photos.remove', en: 'Remove', ru: 'Удалить', th: 'นำออก', zh: '移除' },
  {
    key: 'property.onboard.offers.hint',
    en: 'Choose how you want to offer the property. Terms and responsibility will be verified before activation.',
    ru: 'Выберите, как вы хотите сдавать или продавать объект. Перед активацией команда проверит условия и ответственность сторон.',
    th: 'เลือกวิธีเสนอทรัพย์สิน ทีมงานจะตรวจสอบเงื่อนไขและความรับผิดชอบก่อนเปิดใช้งาน',
    zh: '选择房源的出租或出售方式。团队将在启用前核实条款及各方责任。',
  },
  {
    key: 'property.onboard.offers.short_stay',
    en: 'Short stays',
    ru: 'Краткосрочная аренда',
    th: 'เข้าพักระยะสั้น',
    zh: '短期住宿',
  },
  {
    key: 'property.onboard.offers.monthly',
    en: 'Monthly rental',
    ru: 'Помесячная аренда',
    th: 'เช่ารายเดือน',
    zh: '按月出租',
  },
  {
    key: 'property.onboard.offers.yearly',
    en: 'Long-term rental',
    ru: 'Долгосрочная аренда',
    th: 'เช่าระยะยาว',
    zh: '长期出租',
  },
  { key: 'property.onboard.offers.sale', en: 'For sale', ru: 'Продажа', th: 'ขาย', zh: '出售' },
  {
    key: 'property.onboard.operating.title',
    en: 'Who will manage property services?',
    ru: 'Кто будет обслуживать объект?',
    th: 'ใครจะดูแลบริการของทรัพย์สิน',
    zh: '谁将负责物业服务？',
  },
  {
    key: 'property.onboard.operating.owner_direct',
    en: 'I am the owner and will manage the property',
    ru: 'Я собственник и буду обслуживать объект самостоятельно',
    th: 'ฉันเป็นเจ้าของและจะดูแลทรัพย์สินเอง',
    zh: '我是业主，将自行管理房源',
  },
  {
    key: 'property.onboard.operating.via_management_company',
    en: 'I represent an authorized management company',
    ru: 'Я представляю уполномоченную управляющую компанию',
    th: 'ฉันเป็นตัวแทนบริษัทจัดการที่ได้รับอนุญาต',
    zh: '我代表获授权的物业管理公司',
  },
  {
    key: 'property.onboard.operating.direct_managed',
    en: 'I want to apply for myUNO management',
    ru: 'Хочу подать заявку на передачу объекта в управление myUNO',
    th: 'ฉันต้องการสมัครให้ myUNO จัดการ',
    zh: '我想申请 myUNO 托管',
  },
  {
    key: 'property.onboard.operating.company',
    en: 'Management company name',
    ru: 'Название управляющей компании',
    th: 'ชื่อบริษัทจัดการ',
    zh: '物业管理公司名称',
  },
  {
    key: 'property.onboard.operating.company_placeholder',
    en: 'Company or manager name',
    ru: 'Название компании или имя управляющего',
    th: 'ชื่อบริษัทหรือผู้จัดการ',
    zh: '公司名称或管理人姓名',
  },
  {
    key: 'property.onboard.operating.hint',
    en: 'This records your request only. It does not grant management authority, staff access or permission to accept bookings.',
    ru: 'Это только пожелание в заявке. Оно не даёт полномочий на управление, доступа сотрудникам или права принимать бронирования.',
    th: 'ข้อมูลนี้เป็นเพียงคำขอ ไม่ได้ให้สิทธิ์จัดการ สิทธิ์พนักงาน หรือสิทธิ์รับการจอง',
    zh: '此处仅记录您的申请意向，不会授予管理权限、员工访问权限或接受预订的权限。',
  },
  {
    key: 'property.onboard.offers.price',
    en: 'Proposed nightly price, THB',
    ru: 'Предлагаемая цена за ночь, THB',
    th: 'ราคาต่อคืนที่เสนอ (THB)',
    zh: '建议每晚价格（THB）',
  },
  {
    key: 'property.onboard.offers.minimum',
    en: 'Minimum nights',
    ru: 'Минимум ночей',
    th: 'จำนวนคืนขั้นต่ำ',
    zh: '最少入住晚数',
  },
  {
    key: 'property.onboard.offers.terms_hint',
    en: 'Proposed rental terms are reviewed before publication. Once your authority and access are confirmed, you can manage prices, unavailable dates and photos in property settings.',
    ru: 'Предложенные условия аренды проверят перед публикацией. После подтверждения полномочий и доступа вы сможете менять цены, закрытые даты и фото в настройках объекта.',
    th: 'เงื่อนไขการเช่าที่เสนอจะได้รับการตรวจสอบก่อนเผยแพร่ เมื่อยืนยันสิทธิ์และการเข้าถึงแล้ว คุณจะจัดการราคา วันที่ไม่ว่าง และรูปภาพในการตั้งค่าทรัพย์สินได้',
    zh: '建议租赁条款将在发布前审核。权限与访问资格确认后，您可在房源设置中管理价格、不可订日期和照片。',
  },
  {
    key: 'property.onboard.offers.contact',
    en: 'Preferred contact',
    ru: 'Как с вами связаться',
    th: 'ช่องทางติดต่อที่สะดวก',
    zh: '首选联系方式',
  },
  {
    key: 'property.onboard.offers.contact_placeholder',
    en: 'Phone or email',
    ru: 'Телефон или электронная почта',
    th: 'โทรศัพท์หรืออีเมล',
    zh: '电话或电子邮箱',
  },
  {
    key: 'property.onboard.review.property',
    en: 'Property',
    ru: 'Объект',
    th: 'ทรัพย์สิน',
    zh: '房源',
  },
  {
    key: 'property.onboard.review.existing',
    en: 'Existing property record selected',
    ru: 'Выбрана существующая запись объекта',
    th: 'เลือกข้อมูลทรัพย์สินที่มีอยู่แล้ว',
    zh: '已选择现有房源记录',
  },
  {
    key: 'property.onboard.review.residence',
    en: 'Residence',
    ru: 'Комплекс',
    th: 'โครงการ',
    zh: '住宅项目',
  },
  {
    key: 'property.onboard.review.offers',
    en: 'Offers',
    ru: 'Варианты аренды и продажи',
    th: 'ข้อเสนอ',
    zh: '出租与出售方式',
  },
  {
    key: 'property.onboard.review.operating',
    en: 'Management preference',
    ru: 'Предпочтения по управлению',
    th: 'รูปแบบการจัดการที่ต้องการ',
    zh: '管理意向',
  },
  {
    key: 'property.onboard.review.not_supplied',
    en: 'Not supplied',
    ru: 'Не указано',
    th: 'ยังไม่ระบุ',
    zh: '未填写',
  },
  {
    key: 'property.onboard.review.not_selected',
    en: 'Not selected',
    ru: 'Не выбрано',
    th: 'ยังไม่เลือก',
    zh: '未选择',
  },
  {
    key: 'property.onboard.review.hint',
    en: 'Submitting starts a review. It does not publish the property, verify ownership, appoint a manager or authorize bookings.',
    ru: 'После отправки начнётся проверка. Заявка сама по себе не публикует объект, не подтверждает право собственности, не назначает управляющего и не разрешает принимать бронирования.',
    th: 'การส่งใบสมัครเริ่มกระบวนการตรวจสอบเท่านั้น ไม่ใช่การเผยแพร่ ยืนยันเจ้าของ แต่งตั้งผู้จัดการ หรืออนุญาตให้รับการจอง',
    zh: '提交后将开始审核。提交申请本身不会发布房源、验证所有权、任命管理方或授权接受预订。',
  },
  { key: 'property.onboard.action.back', en: 'Back', ru: 'Назад', th: 'ย้อนกลับ', zh: '返回' },
  {
    key: 'property.onboard.action.save',
    en: 'Save draft',
    ru: 'Сохранить черновик',
    th: 'บันทึกฉบับร่าง',
    zh: '保存草稿',
  },
  {
    key: 'property.onboard.action.next',
    en: 'Save and continue →',
    ru: 'Сохранить и продолжить →',
    th: 'บันทึกและดำเนินการต่อ →',
    zh: '保存并继续 →',
  },
  {
    key: 'property.onboard.action.submit',
    en: 'Submit for review',
    ru: 'Отправить на проверку',
    th: 'ส่งเพื่อตรวจสอบ',
    zh: '提交审核',
  },
  {
    key: 'property.onboard.action.retry',
    en: 'Try again',
    ru: 'Повторить',
    th: 'ลองอีกครั้ง',
    zh: '重试',
  },
  {
    key: 'property.onboard.loading',
    en: 'Loading saved applications…',
    ru: 'Загружаем сохранённые заявки…',
    th: 'กำลังโหลดใบสมัครที่บันทึกไว้…',
    zh: '正在加载已保存的申请…',
  },
  {
    key: 'property.onboard.loading_units',
    en: 'Loading homes…',
    ru: 'Загружаем объекты…',
    th: 'กำลังโหลดที่พัก…',
    zh: '正在加载房源…',
  },
  {
    key: 'property.onboard.saving',
    en: 'Saving…',
    ru: 'Сохраняем…',
    th: 'กำลังบันทึก…',
    zh: '正在保存…',
  },
  {
    key: 'property.onboard.uploading',
    en: 'Uploading photos…',
    ru: 'Загружаем фотографии…',
    th: 'กำลังอัปโหลดรูปภาพ…',
    zh: '正在上传照片…',
  },
  {
    key: 'property.onboard.notice.saved',
    en: 'Draft saved. You can return to it later.',
    ru: 'Черновик сохранён. Вы сможете вернуться к нему позже.',
    th: 'บันทึกฉบับร่างแล้ว คุณกลับมาทำต่อภายหลังได้',
    zh: '草稿已保存。您可以稍后继续。',
  },
  {
    key: 'property.onboard.notice.submitted',
    en: 'Application sent to the myUNO team for verification.',
    ru: 'Заявка отправлена команде myUNO на проверку.',
    th: 'ส่งใบสมัครให้ทีม myUNO ตรวจสอบแล้ว',
    zh: '申请已发送至 myUNO 团队审核。',
  },
  {
    key: 'property.onboard.notice.uploaded',
    en: 'Photos uploaded. Save the draft to attach them to the application.',
    ru: 'Фотографии загружены. Сохраните черновик, чтобы прикрепить их к заявке.',
    th: 'อัปโหลดรูปแล้ว บันทึกฉบับร่างเพื่อแนบรูปกับใบสมัคร',
    zh: '照片已上传。请保存草稿以将照片附加到申请。',
  },
  {
    key: 'property.onboard.error.load',
    en: 'Could not load your applications. Try again before continuing.',
    ru: 'Не удалось загрузить ваши заявки. Повторите попытку, прежде чем продолжить.',
    th: 'โหลดใบสมัครไม่ได้ โปรดลองอีกครั้งก่อนดำเนินการต่อ',
    zh: '无法加载您的申请。请重试后再继续。',
  },
  {
    key: 'property.onboard.error.units',
    en: 'Could not load existing homes. Try again before adding a new one.',
    ru: 'Не удалось загрузить существующие объекты. Повторите попытку перед добавлением нового.',
    th: 'โหลดที่พักที่มีอยู่ไม่ได้ โปรดลองอีกครั้งก่อนเพิ่มที่พักใหม่',
    zh: '无法加载已有房源。请重试后再添加新房源。',
  },
  {
    key: 'property.onboard.error.save',
    en: 'Could not save. Your entries are still here; try again.',
    ru: 'Не удалось сохранить. Введённые данные остались на странице. Повторите попытку.',
    th: 'บันทึกไม่ได้ ข้อมูลที่กรอกยังอยู่ โปรดลองอีกครั้ง',
    zh: '无法保存。您填写的内容仍保留在此页，请重试。',
  },
  {
    key: 'property.onboard.error.upload',
    en: 'Could not upload the photo. Try a JPG, PNG or WebP file up to 8 MB.',
    ru: 'Не удалось загрузить фото. Попробуйте файл JPG, PNG или WebP размером до 8 МБ.',
    th: 'อัปโหลดรูปไม่ได้ โปรดลองใช้ไฟล์ JPG, PNG หรือ WebP ไม่เกิน 8 MB',
    zh: '无法上传照片。请尝试不超过 8 MB 的 JPG、PNG 或 WebP 文件。',
  },
  {
    key: 'property.onboard.error.unauthorized',
    en: 'Your session has ended. Sign in again to continue.',
    ru: 'Сессия завершилась. Войдите снова, чтобы продолжить.',
    th: 'เซสชันสิ้นสุดแล้ว โปรดเข้าสู่ระบบอีกครั้ง',
    zh: '您的会话已结束，请重新登录以继续。',
  },
  {
    key: 'property.onboard.error.project_required',
    en: 'Choose the residence for the selected home.',
    ru: 'Выберите комплекс, к которому относится выбранный объект.',
    th: 'เลือกโครงการของที่พักที่เลือก',
    zh: '请选择所选房源所属的住宅项目。',
  },
  {
    key: 'property.onboard.error.kind',
    en: 'Choose what you are adding.',
    ru: 'Выберите, какой объект вы добавляете.',
    th: 'เลือกสิ่งที่คุณต้องการเพิ่ม',
    zh: '请选择您要添加的对象。',
  },
  {
    key: 'property.onboard.error.measurements',
    en: 'Check the area, room counts and maximum guests. Use non-negative numbers and a whole number of guests.',
    ru: 'Проверьте площадь, количество комнат и гостей. Значения не могут быть отрицательными, число гостей должно быть целым.',
    th: 'ตรวจสอบพื้นที่ จำนวนห้อง และจำนวนผู้เข้าพัก ใช้ค่าที่ไม่ติดลบและจำนวนผู้เข้าพักเป็นจำนวนเต็ม',
    zh: '请检查面积、房间数和最多入住人数。数值不可为负，入住人数须为整数。',
  },
  {
    key: 'property.onboard.error.location',
    en: 'Check the coordinates: latitude from −90 to 90, longitude from −180 to 180.',
    ru: 'Проверьте координаты: широта от −90 до 90, долгота от −180 до 180.',
    th: 'ตรวจสอบพิกัด: ละติจูด −90 ถึง 90 และลองจิจูด −180 ถึง 180',
    zh: '请检查坐标：纬度为 −90 至 90，经度为 −180 至 180。',
  },
  {
    key: 'property.onboard.error.terms',
    en: 'Use whole numbers: nightly price from 1 to 10,000,000 THB and minimum stay from 1 to 365 nights.',
    ru: 'Укажите целые числа: цена за ночь от 1 до 10 000 000 THB, минимум ночей от 1 до 365.',
    th: 'ใช้จำนวนเต็ม: ราคาต่อคืน 1–10,000,000 THB และจำนวนคืนขั้นต่ำ 1–365 คืน',
    zh: '请填写整数：每晚价格 1 至 10,000,000 THB，最少入住晚数 1 至 365。',
  },
  {
    key: 'property.onboard.error.photo_access',
    en: 'Only public photos uploaded by you can be attached.',
    ru: 'Можно прикреплять только публичные фотографии, загруженные вами.',
    th: 'แนบได้เฉพาะรูปสาธารณะที่คุณอัปโหลดเอง',
    zh: '只能附加您本人上传的公开照片。',
  },
  {
    key: 'property.onboard.error.project',
    en: 'This residence is unavailable. Choose another residence or try again.',
    ru: 'Этот комплекс недоступен. Выберите другой или повторите попытку.',
    th: 'โครงการนี้ไม่พร้อมใช้งาน เลือกโครงการอื่นหรือลองอีกครั้ง',
    zh: '此住宅项目不可用。请选择其他项目或重试。',
  },
  {
    key: 'property.onboard.error.unit',
    en: 'The selected home is unavailable in this residence. Check your selection.',
    ru: 'Выбранный объект недоступен в этом комплексе. Проверьте выбор.',
    th: 'ที่พักที่เลือกไม่พร้อมใช้งานในโครงการนี้ โปรดตรวจสอบตัวเลือก',
    zh: '所选房源在此住宅项目中不可用，请检查您的选择。',
  },
  {
    key: 'property.onboard.error.incomplete',
    en: 'Before submitting, enter the home details, choose a residence and select an offer.',
    ru: 'Перед отправкой заполните сведения об объекте, выберите комплекс и вариант аренды или продажи.',
    th: 'ก่อนส่ง กรุณากรอกรายละเอียดที่พัก เลือกโครงการและข้อเสนอ',
    zh: '提交前，请填写房源详情，选择住宅项目及出租或出售方式。',
  },
  {
    key: 'property.onboard.error.missing',
    en: 'This application could not be found. Return to My listings to choose an available application.',
    ru: 'Эта заявка не найдена. Вернитесь в «Мои объявления» и выберите доступную заявку.',
    th: 'ไม่พบใบสมัครนี้ กลับไปที่ประกาศของฉันเพื่อเลือกใบสมัครที่เข้าถึงได้',
    zh: '未找到此申请。请返回“我的房源”选择可用的申请。',
  },
  {
    key: 'property.onboard.error.locked',
    en: 'Submitted applications cannot be edited. Contact the myUNO team to request a change.',
    ru: 'Отправленную заявку нельзя редактировать. Для изменений свяжитесь с командой myUNO.',
    th: 'แก้ไขใบสมัครที่ส่งแล้วไม่ได้ โปรดติดต่อทีม myUNO เพื่อขอเปลี่ยนแปลง',
    zh: '已提交的申请无法编辑。如需修改，请联系 myUNO 团队。',
  },
  { key: 'property.onboard.state.draft', en: 'Draft', ru: 'Черновик', th: 'ฉบับร่าง', zh: '草稿' },
  {
    key: 'property.onboard.state.unit_matched',
    en: 'Property identified',
    ru: 'Объект найден в системе',
    th: 'ระบุทรัพย์สินแล้ว',
    zh: '已识别房源',
  },
  {
    key: 'property.onboard.state.authority_pending',
    en: 'Authority verification pending',
    ru: 'Ожидается проверка полномочий',
    th: 'รอตรวจสอบสิทธิ์',
    zh: '等待权限验证',
  },
  {
    key: 'property.onboard.state.authority_verified',
    en: 'Authority verified',
    ru: 'Полномочия подтверждены',
    th: 'ยืนยันสิทธิ์แล้ว',
    zh: '权限已验证',
  },
  {
    key: 'property.onboard.state.commercial_configured',
    en: 'Offers configured',
    ru: 'Варианты аренды и продажи настроены',
    th: 'ตั้งค่าข้อเสนอแล้ว',
    zh: '已配置出租与出售方式',
  },
  {
    key: 'property.onboard.state.engagement_configured',
    en: 'Management arrangement configured',
    ru: 'Условия управления настроены',
    th: 'ตั้งค่าการจัดการแล้ว',
    zh: '已配置管理安排',
  },
  {
    key: 'property.onboard.state.readiness_pending',
    en: 'Readiness checks pending',
    ru: 'Ожидается проверка готовности',
    th: 'รอตรวจสอบความพร้อม',
    zh: '等待就绪检查',
  },
  {
    key: 'property.onboard.state.ready_for_activation',
    en: 'Ready for activation',
    ru: 'Готов к активации',
    th: 'พร้อมเปิดใช้งาน',
    zh: '可启用',
  },
  {
    key: 'property.onboard.state.active',
    en: 'Active',
    ru: 'Активен',
    th: 'เปิดใช้งานแล้ว',
    zh: '已启用',
  },
  {
    key: 'property.onboard.state.blocked',
    en: 'Outstanding checks prevent activation',
    ru: 'Есть препятствия для активации',
    th: 'ยังเปิดใช้งานไม่ได้เนื่องจากมีรายการค้าง',
    zh: '待完成的检查阻止启用',
  },
  {
    key: 'property.onboard.blocker.unit_not_found',
    en: 'Property record not found. Contact the myUNO team.',
    ru: 'Запись объекта не найдена. Свяжитесь с командой myUNO.',
    th: 'ไม่พบข้อมูลทรัพย์สิน โปรดติดต่อทีม myUNO',
    zh: '未找到房源记录，请联系 myUNO 团队。',
  },
  {
    key: 'property.onboard.blocker.authority_not_verified',
    en: 'Ownership or management authority needs verification.',
    ru: 'Нужно подтвердить право собственности или полномочия на управление.',
    th: 'ต้องยืนยันความเป็นเจ้าของหรือสิทธิ์จัดการ',
    zh: '需要核实所有权或管理权限。',
  },
  {
    key: 'property.onboard.blocker.permitted_use_not_verified',
    en: 'Permission for short stays needs verification.',
    ru: 'Нужно проверить, разрешена ли краткосрочная аренда.',
    th: 'ต้องตรวจสอบการอนุญาตให้เข้าพักระยะสั้น',
    zh: '需要核实短期住宿许可。',
  },
  {
    key: 'property.onboard.blocker.short_stay_rate_plan_missing',
    en: 'An active short-stay rate plan is required.',
    ru: 'Нужно настроить и активировать тариф для краткосрочной аренды.',
    th: 'ต้องมีแผนราคาการเข้าพักระยะสั้นที่เปิดใช้งาน',
    zh: '需要启用短期住宿价格方案。',
  },
  {
    key: 'property.onboard.blocker.public_media_missing',
    en: 'Public photos and a cover need to be prepared.',
    ru: 'Нужно подготовить фотографии для публикации и обложку.',
    th: 'ต้องเตรียมรูปสาธารณะและรูปหน้าปก',
    zh: '需要准备公开照片与封面。',
  },
  {
    key: 'property.onboard.blocker.management_mandate_missing',
    en: 'A management agreement is required.',
    ru: 'Нужен договор управления.',
    th: 'ต้องมีข้อตกลงการจัดการ',
    zh: '需要管理协议。',
  },
  {
    key: 'property.onboard.blocker.direct_managed_economics_missing',
    en: 'Management financial terms need to be agreed.',
    ru: 'Нужно согласовать финансовые условия управления.',
    th: 'ต้องตกลงเงื่อนไขทางการเงินของการจัดการ',
    zh: '需要商定管理财务条款。',
  },
  {
    key: 'property.onboard.blocker.management_organization_missing',
    en: 'The responsible management company must be specified.',
    ru: 'Нужно указать ответственную управляющую компанию.',
    th: 'ต้องระบุบริษัทจัดการที่รับผิดชอบ',
    zh: '需要指定负责的物业管理公司。',
  },
  {
    key: 'property.onboard.blocker.unknown',
    en: 'An additional check is required. Contact the myUNO team for details.',
    ru: 'Нужна дополнительная проверка. Подробности можно уточнить у команды myUNO.',
    th: 'ต้องมีการตรวจสอบเพิ่มเติม โปรดติดต่อทีม myUNO เพื่อทราบรายละเอียด',
    zh: '需要额外检查。请联系 myUNO 团队了解详情。',
  },
  {
    key: 'property.onboard.photos.public_hint',
    en: 'Uploaded photos are accessible by link before listing approval. Do not upload private documents.',
    ru: 'Загруженные фотографии доступны по ссылке ещё до одобрения объявления. Не загружайте личные документы.',
    th: 'รูปที่อัปโหลดสามารถเปิดดูผ่านลิงก์ได้ก่อนประกาศได้รับอนุมัติ อย่าอัปโหลดเอกสารส่วนตัว',
    zh: '上传的照片在房源获批前即可通过链接访问。请勿上传私人文件。',
  },
].map((entry) => ({
  ...entry,
  namespace: 'property',
  description: 'Property onboarding application copy',
  status: 'needs_review' as const,
}));

export const PROPERTY_ONBOARDING_LOCALE_DRAFTS = Object.fromEntries(PROPERTY_ONBOARDING_KEYS.map(({ key, en, ru, th, zh }) => [key, { en, ru, th, zh }]));
