/** Reservation Desk labels. */
export const RESERVATION_DESK_KEYS = [
  {key:'reservations.back',namespace:'reservations',description:'Back to operating space',en:'← Operating space',ru:'← Операционный контур',th:'← พื้นที่ปฏิบัติการ',status:'needs_review' as const},
  {key:'reservations.kicker',namespace:'reservations',description:'Reservation desk kicker',en:'RESERVATION DESK',ru:'СЛУЖБА БРОНИРОВАНИЙ',th:'โต๊ะจอง',status:'needs_review' as const},
  {key:'reservations.title',namespace:'reservations',description:'Reservation desk title',en:'Reservations',ru:'Бронирования',th:'การจอง',status:'needs_review' as const},
  {key:'reservations.subtitle',namespace:'reservations',description:'Reservation desk subtitle',en:'One desk for requests, manual reservations, groups, payments and stay actions.',ru:'Единое рабочее место для запросов, ручных бронирований, групп, оплат и операций по проживанию.',th:'ศูนย์เดียวสำหรับคำขอ การจองด้วยตนเอง กลุ่ม การชำระเงิน และการดำเนินงานเข้าพัก',status:'needs_review' as const},
  {key:'reservations.total',namespace:'reservations',description:'Reservation total metric',en:'Reservations',ru:'Бронирования',th:'การจอง',status:'needs_review' as const},
  {key:'reservations.arrivals',namespace:'reservations',description:'Arrivals today metric',en:'Arrivals today',ru:'Заезды сегодня',th:'เช็กอินวันนี้',status:'needs_review' as const},
  {key:'reservations.requests',namespace:'reservations',description:'Booking requests metric',en:'Requests',ru:'Запросы',th:'คำขอ',status:'needs_review' as const},
  {key:'reservations.balance',namespace:'reservations',description:'Balance due metric',en:'Balance due',ru:'К оплате',th:'ยอดค้างชำระ',status:'needs_review' as const},
  {key:'reservations.groups',namespace:'reservations',description:'Reservation groups title',en:'Reservation groups',ru:'Групповые бронирования',th:'กลุ่มการจอง',status:'needs_review' as const},
  {key:'reservations.open',namespace:'reservations',description:'Open reservation action',en:'Open stay →',ru:'Открыть проживание →',th:'เปิดการเข้าพัก →',status:'needs_review' as const},
  {key:'reservations.create',namespace:'reservations',description:'Create reservation heading',en:'Create reservation',ru:'Создать бронирование',th:'สร้างการจอง',status:'needs_review' as const},
  {key:'reservations.create_action',namespace:'reservations',description:'Create reservation button',en:'Create reservation',ru:'Создать бронирование',th:'สร้างการจอง',status:'needs_review' as const},
  {key:'reservations.creating',namespace:'reservations',description:'Creating state',en:'Creating…',ru:'Создание…',th:'กำลังสร้าง…',status:'needs_review' as const},
  {key:'reservations.create_failed',namespace:'reservations',description:'Reservation creation error',en:'Reservation creation failed',ru:'Не удалось создать бронирование',th:'สร้างการจองไม่สำเร็จ',status:'needs_review' as const},
  {key:'reservations.unit',namespace:'reservations',description:'Property selector',en:'Property',ru:'Объект',th:'อสังหาริมทรัพย์',status:'needs_review' as const},
  {key:'reservations.guest',namespace:'reservations',description:'Guest selector',en:'Guest',ru:'Гость',th:'ผู้เข้าพัก',status:'needs_review' as const},
  {key:'reservations.group',namespace:'reservations',description:'Group selector',en:'Group',ru:'Группа',th:'กลุ่ม',status:'needs_review' as const},
  {key:'reservations.no_group',namespace:'reservations',description:'No group option',en:'No group',ru:'Без группы',th:'ไม่มีกลุ่ม',status:'needs_review' as const},
  {key:'reservations.select',namespace:'reservations',description:'Select placeholder',en:'Select',ru:'Выберите',th:'เลือก',status:'needs_review' as const},
  {key:'reservations.start',namespace:'reservations',description:'Checkin field',en:'Check-in',ru:'Заезд',th:'เช็กอิน',status:'needs_review' as const},
  {key:'reservations.end',namespace:'reservations',description:'Checkout field',en:'Check-out',ru:'Выезд',th:'เช็กเอาต์',status:'needs_review' as const},
  {key:'reservations.adults',namespace:'reservations',description:'Adults field',en:'Adults',ru:'Взрослые',th:'ผู้ใหญ่',status:'needs_review' as const},
  {key:'reservations.children',namespace:'reservations',description:'Children field',en:'Children',ru:'Дети',th:'เด็ก',status:'needs_review' as const},
  {key:'reservations.pets',namespace:'reservations',description:'Pets field',en:'Pets',ru:'Питомцы',th:'สัตว์เลี้ยง',status:'needs_review' as const},
  {key:'reservations.note',namespace:'reservations',description:'Reservation notes field',en:'Notes',ru:'Примечания',th:'หมายเหตุ',status:'needs_review' as const},
  {key:'reservations.create_group',namespace:'reservations',description:'Create group button',en:'Create group',ru:'Создать группу',th:'สร้างกลุ่ม',status:'needs_review' as const},
  {key:'reservations.group_title',namespace:'reservations',description:'Group title placeholder',en:'Group title',ru:'Название группы',th:'ชื่อกลุ่ม',status:'needs_review' as const},
  {key:'reservations.group_failed',namespace:'reservations',description:'Group creation error',en:'Group creation failed',ru:'Не удалось создать группу',th:'สร้างกลุ่มไม่สำเร็จ',status:'needs_review' as const},
  {key:'reservations.all',namespace:'reservations',description:'All statuses filter',en:'All',ru:'Все',th:'ทั้งหมด',status:'needs_review' as const},
  {key:'reservations.paid',namespace:'reservations',description:'Paid amount label',en:'Paid',ru:'Оплачено',th:'ชำระแล้ว',status:'needs_review' as const},
  {key:'reservations.group_summary',namespace:'reservations',description:'Reservation group summary',en:'{count} reservations · ฿{amount}',ru:'Бронирований: {count} · ฿{amount}',th:'{count} การจอง · ฿{amount}',status:'needs_review' as const},
  {key:'reservations.categories',namespace:'reservations',description:'Category inventory group',en:'Categories',ru:'Категории',th:'หมวดหมู่',status:'needs_review' as const},
  {key:'reservations.exact_units',namespace:'reservations',description:'Exact unit inventory group',en:'Exact properties',ru:'Конкретные объекты',th:'ทรัพย์สินเฉพาะ',status:'needs_review' as const},
] as const;
