/**
 * Seed content keys and translations for the common.* namespace
 * This is called during database initialization
 */

import { PrismaClient } from '@prisma/client';
import { ensureContentKey, setTranslation } from './content.service';
import { Locale } from './types';

interface KeyDef {
  key: string;
  namespace: string;
  description: string;
  supportsRich?: boolean;
  ru: string;
  en: string;
  th: string;
}

const COMMON_KEYS: KeyDef[] = [
  // Actions
  {
    key: 'common.action.save',
    namespace: 'common',
    description: 'Button: save changes',
    ru: 'Сохранить',
    en: 'Save',
    th: 'บันทึก',
  },
  {
    key: 'common.action.cancel',
    namespace: 'common',
    description: 'Button: cancel action',
    ru: 'Отменить',
    en: 'Cancel',
    th: 'ยกเลิก',
  },
  {
    key: 'common.action.confirm',
    namespace: 'common',
    description: 'Button: confirm action',
    ru: 'Подтвердить',
    en: 'Confirm',
    th: 'ยืนยัน',
  },
  {
    key: 'common.action.back',
    namespace: 'common',
    description: 'Button: go back',
    ru: 'Назад',
    en: 'Back',
    th: 'ย้อนกลับ',
  },
  {
    key: 'common.action.continue',
    namespace: 'common',
    description: 'Button: continue',
    ru: 'Далее',
    en: 'Continue',
    th: 'ต่อไป',
  },
  {
    key: 'common.action.close',
    namespace: 'common',
    description: 'Button: close dialog',
    ru: 'Закрыть',
    en: 'Close',
    th: 'ปิด',
  },
  {
    key: 'common.action.edit',
    namespace: 'common',
    description: 'Button: edit item',
    ru: 'Редактировать',
    en: 'Edit',
    th: 'แก้ไข',
  },
  {
    key: 'common.action.delete',
    namespace: 'common',
    description: 'Button: delete item',
    ru: 'Удалить',
    en: 'Delete',
    th: 'ลบ',
  },
  {
    key: 'common.action.search',
    namespace: 'common',
    description: 'Button: search',
    ru: 'Поиск',
    en: 'Search',
    th: 'ค้นหา',
  },
  {
    key: 'common.action.filter',
    namespace: 'common',
    description: 'Button: open filters',
    ru: 'Фильтры',
    en: 'Filter',
    th: 'ตัวกรอง',
  },

  // Booking statuses
  {
    key: 'common.status.booking.pending_payment',
    namespace: 'common',
    description: 'Booking status: awaiting payment',
    ru: 'Ожидание оплаты',
    en: 'Awaiting Payment',
    th: 'รอการชำระเงิน',
  },
  {
    key: 'common.status.booking.confirmed',
    namespace: 'common',
    description: 'Booking status: confirmed',
    ru: 'Подтверждено',
    en: 'Confirmed',
    th: 'ยืนยันแล้ว',
  },
  {
    key: 'common.status.booking.requested',
    namespace: 'common',
    description: 'Booking status: request awaiting approval',
    ru: 'На рассмотрении',
    en: 'Requested',
    th: 'อยู่ระหว่างการพิจารณา',
  },
  {
    key: 'common.status.booking.declined',
    namespace: 'common',
    description: 'Booking status: declined',
    ru: 'Отклонено',
    en: 'Declined',
    th: 'ปฏิเสธแล้ว',
  },
  {
    key: 'common.status.booking.cancelled',
    namespace: 'common',
    description: 'Booking status: cancelled',
    ru: 'Отменено',
    en: 'Cancelled',
    th: 'ยกเลิกแล้ว',
  },

  // Engagement types
  {
    key: 'common.engagement.direct',
    namespace: 'common',
    description: 'Engagement type: directly managed by owner',
    ru: 'Прямое управление',
    en: 'Direct',
    th: 'การจัดการโดยตรง',
  },
  {
    key: 'common.engagement.via_mc',
    namespace: 'common',
    description: 'Engagement type: via management company',
    ru: 'Через УК',
    en: 'Management Company',
    th: 'ผ่านบริษัทจัดการ',
  },
  {
    key: 'common.engagement.owner_direct',
    namespace: 'common',
    description: 'Engagement type: owner-managed stays',
    ru: 'Владелец владеет',
    en: 'Owner-Direct',
    th: 'เจ้าของจัดการ',
  },

  // Unit statuses
  {
    key: 'common.status.unit.draft',
    namespace: 'common',
    description: 'Unit status: not yet live',
    ru: 'Черновик',
    en: 'Draft',
    th: 'ร่างฉบับ',
  },
  {
    key: 'common.status.unit.active',
    namespace: 'common',
    description: 'Unit status: live and bookable',
    ru: 'Активно',
    en: 'Active',
    th: 'ใช้งานอยู่',
  },
  {
    key: 'common.status.unit.inactive',
    namespace: 'common',
    description: 'Unit status: temporarily unavailable',
    ru: 'Неактивно',
    en: 'Inactive',
    th: 'ไม่ใช้งาน',
  },

  // Dates and durations
  {
    key: 'common.date.night',
    namespace: 'common',
    description: 'Singular: one night',
    ru: 'ночь',
    en: 'night',
    th: 'คืน',
  },
  {
    key: 'common.date.nights',
    namespace: 'common',
    description: 'Plural: multiple nights',
    ru: 'ночей',
    en: 'nights',
    th: 'คืน',
  },

  // Empty/Loading/Error states
  {
    key: 'common.state.empty.title',
    namespace: 'common',
    description: 'Empty state: no results title',
    ru: 'Ничего не найдено',
    en: 'No Results',
    th: 'ไม่พบผลลัพธ์',
  },
  {
    key: 'common.state.empty.description',
    namespace: 'common',
    description: 'Empty state: no results description',
    ru: 'Попробуйте изменить критерии поиска',
    en: 'Try adjusting your search criteria',
    th: 'ลองปรับเปลี่ยนเกณฑ์การค้นหา',
  },
  {
    key: 'common.state.loading',
    namespace: 'common',
    description: 'Loading state: generic loading message',
    ru: 'Загрузка...',
    en: 'Loading...',
    th: 'กำลังโหลด...',
  },
  {
    key: 'common.state.error.title',
    namespace: 'common',
    description: 'Error state: something went wrong title',
    ru: 'Ошибка',
    en: 'Error',
    th: 'ข้อผิดพลาด',
  },
  {
    key: 'common.state.error.description',
    namespace: 'common',
    description: 'Error state: please try again description',
    ru: 'Пожалуйста, попробуйте снова',
    en: 'Please try again',
    th: 'โปรดลองอีกครั้ง',
  },

  // Roles
  {
    key: 'common.role.owner',
    namespace: 'common',
    description: 'Role: property owner',
    ru: 'Владелец',
    en: 'Owner',
    th: 'เจ้าของ',
  },
  {
    key: 'common.role.guest',
    namespace: 'common',
    description: 'Role: guest/resident',
    ru: 'Гость',
    en: 'Guest',
    th: 'แขก',
  },
  {
    key: 'common.role.resident',
    namespace: 'common',
    description: 'Role: long-term resident',
    ru: 'Резидент',
    en: 'Resident',
    th: 'ผู้พักอาศัย',
  },
  {
    key: 'common.role.staff',
    namespace: 'common',
    description: 'Role: staff member',
    ru: 'Персонал',
    en: 'Staff',
    th: 'พนักงาน',
  },
  {
    key: 'common.role.provider',
    namespace: 'common',
    description: 'Role: service provider',
    ru: 'Поставщик услуг',
    en: 'Provider',
    th: 'ผู้ให้บริการ',
  },
  {
    key: 'common.role.admin',
    namespace: 'common',
    description: 'Role: administrator',
    ru: 'Администратор',
    en: 'Administrator',
    th: 'ผู้ดูแลระบบ',
  },

  // Notification keys
  {
    key: 'notify.stay_dates_modified.title',
    namespace: 'notify',
    description: 'Notification: stay dates modified',
    ru: 'Даты вашего проживания изменены',
    en: 'Your stay dates have been modified',
    th: 'วันที่พักของคุณถูกเปลี่ยนแปลง',
  },
  {
    key: 'notify.stay_dates_modified.body',
    namespace: 'notify',
    description: 'Notification: stay dates modified details',
    ru: 'Ваше бронирование было обновлено новыми датами. Проверьте детали в приложении.',
    en: 'Your booking has been updated with new dates. Check the details in the app.',
    th: 'การจองของคุณได้รับการอัปเดตด้วยวันที่ใหม่ โปรดตรวจสอบรายละเอียดในแอป',
  },

  // Thread system messages
  {
    key: 'thread.system.booking_confirmed',
    namespace: 'thread',
    description: 'System message: booking confirmed',
    ru: 'Бронирование подтверждено. Платеж получен.',
    en: 'Booking confirmed. Payment received.',
    th: 'การจองได้รับการยืนยัน ชำระเงินแล้ว',
  },

  // Ticket categories
  {
    key: 'catalog.ticket_category.maintenance',
    namespace: 'catalog',
    description: 'Ticket category: maintenance',
    ru: 'Техническое обслуживание',
    en: 'Maintenance',
    th: 'การบำรุงรักษา',
  },
  {
    key: 'catalog.ticket_category.housekeeping',
    namespace: 'catalog',
    description: 'Ticket category: housekeeping',
    ru: 'Уборка',
    en: 'Housekeeping',
    th: 'การทำความสะอาด',
  },
  {
    key: 'catalog.ticket_category.complaint',
    namespace: 'catalog',
    description: 'Ticket category: complaint',
    ru: 'Жалоба',
    en: 'Complaint',
    th: 'การร้องเรียน',
  },
  {
    key: 'catalog.ticket_category.billing_question',
    namespace: 'catalog',
    description: 'Ticket category: billing question',
    ru: 'Вопрос о счете',
    en: 'Billing Question',
    th: 'คำถามเกี่ยวกับการเรียกเก็บเงิน',
  },

  // Ticket status labels
  {
    key: 'ticket.status.open',
    namespace: 'ticket',
    description: 'Ticket status: open',
    ru: 'Открыто',
    en: 'Open',
    th: 'เปิด',
  },
  {
    key: 'ticket.status.acknowledged',
    namespace: 'ticket',
    description: 'Ticket status: acknowledged',
    ru: 'Подтверждено получение',
    en: 'Acknowledged',
    th: 'ยืนยันแล้ว',
  },
  {
    key: 'ticket.status.in_progress',
    namespace: 'ticket',
    description: 'Ticket status: in progress',
    ru: 'В процессе',
    en: 'In Progress',
    th: 'กำลังดำเนินการ',
  },
  {
    key: 'ticket.status.waiting_reporter',
    namespace: 'ticket',
    description: 'Ticket status: waiting for reporter',
    ru: 'Ожидание ответа',
    en: 'Waiting for Reporter',
    th: 'รอการตอบสนอง',
  },
  {
    key: 'ticket.status.resolved',
    namespace: 'ticket',
    description: 'Ticket status: resolved',
    ru: 'Решено',
    en: 'Resolved',
    th: 'แก้ไขแล้ว',
  },
  {
    key: 'ticket.status.closed',
    namespace: 'ticket',
    description: 'Ticket status: closed',
    ru: 'Закрыто',
    en: 'Closed',
    th: 'ปิด',
  },

  // Ticket priority labels
  {
    key: 'ticket.priority.low',
    namespace: 'ticket',
    description: 'Ticket priority: low',
    ru: 'Низкий',
    en: 'Low',
    th: 'ต่ำ',
  },
  {
    key: 'ticket.priority.normal',
    namespace: 'ticket',
    description: 'Ticket priority: normal',
    ru: 'Обычный',
    en: 'Normal',
    th: 'ปกติ',
  },
  {
    key: 'ticket.priority.high',
    namespace: 'ticket',
    description: 'Ticket priority: high',
    ru: 'Высокий',
    en: 'High',
    th: 'สูง',
  },
  {
    key: 'ticket.priority.urgent',
    namespace: 'ticket',
    description: 'Ticket priority: urgent',
    ru: 'Срочный',
    en: 'Urgent',
    th: 'เร่งด่วน',
  },

  // Ticket system messages
  {
    key: 'thread.system.ticket_created',
    namespace: 'thread',
    description: 'System message: ticket created',
    ru: 'Заявка создана.',
    en: 'Ticket created.',
    th: 'ได้สร้างตั๋ว',
  },
  {
    key: 'thread.system.sla_escalated',
    namespace: 'thread',
    description: 'System message: SLA escalated',
    ru: 'SLA истек. Требуется срочное внимание.',
    en: 'SLA escalated. Urgent attention required.',
    th: 'SLA หมดลง ต้องให้ความสำคัญเร่งด่วน',
  },

  // Announcement labels
  {
    key: 'announcement.audience.everyone',
    namespace: 'announcement',
    description: 'Audience: everyone',
    ru: 'Все',
    en: 'Everyone',
    th: 'ทุกคน',
  },
  {
    key: 'announcement.audience.owners',
    namespace: 'announcement',
    description: 'Audience: owners only',
    ru: 'Только владельцы',
    en: 'Owners Only',
    th: 'เจ้าของเท่านั้น',
  },
  {
    key: 'announcement.audience.residents',
    namespace: 'announcement',
    description: 'Audience: residents only',
    ru: 'Только резиденты',
    en: 'Residents Only',
    th: 'ผู้พักอาศัยเท่านั้น',
  },
  {
    key: 'announcement.audience.guests_in_stay',
    namespace: 'announcement',
    description: 'Audience: current guests only',
    ru: 'Только текущие гости',
    en: 'Current Guests Only',
    th: 'แขกปัจจุบันเท่านั้น',
  },
  {
    key: 'announcement.audience.staff',
    namespace: 'announcement',
    description: 'Audience: staff only',
    ru: 'Только персонал',
    en: 'Staff Only',
    th: 'พนักงานเท่านั้น',
  },

  // Announcement notification (N-32)
  {
    key: 'notify.announcement_published.title',
    namespace: 'notify',
    description: 'Notification: announcement published',
    ru: 'Новое объявление',
    en: 'New Announcement',
    th: 'ประกาศใหม่',
  },
  {
    key: 'notify.announcement_published.body',
    namespace: 'notify',
    description: 'Notification: announcement published body',
    ru: '{title}. Прочитайте полный текст в приложении.',
    en: '{title}. Read the full message in the app.',
    th: '{title}. อ่านข้อความเต็มในแอป',
  },
  // Provider notifications (N-18, N-19, N-20)
  {
    key: 'notify.provider_approved.title',
    namespace: 'notify',
    description: 'Notification: provider application approved',
    ru: 'Заявка одобрена',
    en: 'Application Approved',
    th: 'คำขอได้รับการอนุมัติ',
  },
  {
    key: 'notify.provider_approved.body',
    namespace: 'notify',
    description: 'Notification: provider application approved body',
    ru: 'Ваша заявка на {name} одобрена. Добро пожаловать в маркетплейс!',
    en: 'Your {name} application has been approved. Welcome to the marketplace!',
    th: 'ใบสมัครของ {name} ได้รับการอนุมัติ ยินดีต้อนรับสู่ตลาด!',
  },
  {
    key: 'notify.provider_rejected.title',
    namespace: 'notify',
    description: 'Notification: provider application rejected',
    ru: 'Заявка отклонена',
    en: 'Application Rejected',
    th: 'ปฏิเสธคำขอ',
  },
  {
    key: 'notify.provider_rejected.body',
    namespace: 'notify',
    description: 'Notification: provider application rejected body',
    ru: 'К сожалению, ваша заявка на {name} отклонена. Причина: {reason}',
    en: 'Unfortunately, your {name} application has been rejected. Reason: {reason}',
    th: 'ขออภัย ใบสมัครของ {name} ถูกปฏิเสธ เหตุผล: {reason}',
  },
  {
    key: 'notify.provider_application_reminder.title',
    namespace: 'notify',
    description: 'Notification: provider application reminder (incomplete draft)',
    ru: 'Напоминание: завершите заявку',
    en: 'Reminder: Complete Your Application',
    th: 'เตือนความจำ: กรุณาเสร็จสิ้นใบสมัครของคุณ',
  },
  {
    key: 'notify.provider_application_reminder.body',
    namespace: 'notify',
    description: 'Notification: provider application reminder body',
    ru: 'У вас есть незавершённая заявка. Вернитесь в приложение, чтобы завершить её.',
    en: 'You have an incomplete application. Please return to the app to complete it.',
    th: 'คุณมีใบสมัครที่ไม่สมบูรณ์ โปรดกลับไปที่แอปเพื่อกรอกให้สมบูรณ์',
  },
  // Provider status labels
  {
    key: 'provider.status.applied',
    namespace: 'provider',
    description: 'Provider status: application submitted',
    ru: 'Заявка получена',
    en: 'Application Received',
    th: 'ได้รับใบสมัคร',
  },
  {
    key: 'provider.status.vetting',
    namespace: 'provider',
    description: 'Provider status: under review',
    ru: 'На рассмотрении',
    en: 'Under Review',
    th: 'ระหว่างการตรวจสอบ',
  },
  {
    key: 'provider.status.active',
    namespace: 'provider',
    description: 'Provider status: vetted and active',
    ru: 'Активен',
    en: 'Active',
    th: 'ทำงานอยู่',
  },
  {
    key: 'provider.status.suspended',
    namespace: 'provider',
    description: 'Provider status: temporarily suspended',
    ru: 'Приостановлен',
    en: 'Suspended',
    th: 'หยุดชั่วคราว',
  },
  {
    key: 'provider.status.offboarded',
    namespace: 'provider',
    description: 'Provider status: offboarded or rejected',
    ru: 'Завершен',
    en: 'Offboarded',
    th: 'สิ้นสุด',
  },
  // Service status labels
  {
    key: 'service.status.draft',
    namespace: 'service',
    description: 'Service status: awaiting admin approval',
    ru: 'На рассмотрении',
    en: 'Draft',
    th: 'รอการพิจารณา',
  },
  {
    key: 'service.status.active',
    namespace: 'service',
    description: 'Service status: visible to end users',
    ru: 'Активен',
    en: 'Active',
    th: 'ใช้งานได้',
  },
  {
    key: 'service.status.paused',
    namespace: 'service',
    description: 'Service status: temporarily hidden or rejected',
    ru: 'Приостановлен',
    en: 'Paused',
    th: 'หยุดชั่วคราว',
  },
  // Service price model labels
  {
    key: 'service.priceModel.fixed',
    namespace: 'service',
    description: 'Price model: fixed price per service',
    ru: 'Фиксированная цена',
    en: 'Fixed Price',
    th: 'ราคาคงที่',
  },
  {
    key: 'service.priceModel.per_hour',
    namespace: 'service',
    description: 'Price model: hourly rate',
    ru: 'Почасовая тариф',
    en: 'Hourly Rate',
    th: 'อัตรารายชั่วโมง',
  },
  {
    key: 'service.priceModel.per_person',
    namespace: 'service',
    description: 'Price model: per person charge',
    ru: 'За одного человека',
    en: 'Per Person',
    th: 'ต่อคน',
  },
  {
    key: 'service.priceModel.quote',
    namespace: 'service',
    description: 'Price model: custom quote required',
    ru: 'По запросу',
    en: 'Quote',
    th: 'ตามใบเสนอราคา',
  },
  // Service fulfilment mode labels
  {
    key: 'service.fulfilmentMode.referred',
    namespace: 'service',
    description: 'Service fulfilment: provider delivers',
    ru: 'Поставщик выполняет',
    en: 'Provider Delivers',
    th: 'ผู้ให้บริการจัดหา',
  },
  {
    key: 'service.fulfilmentMode.operated',
    namespace: 'service',
    description: 'Service fulfilment: platform coordinates',
    ru: 'myUNO координирует',
    en: 'Platform Coordinates',
    th: 'myUNO ประสานงาน',
  },
  // Service order notifications (N-26, N-21, N-22, N-27)
  {
    key: 'order.new.title',
    namespace: 'order',
    description: 'Notification: new service order received (N-26)',
    ru: 'Новый заказ услуги',
    en: 'New Service Order',
    th: 'คำสั่งซื้อบริการใหม่',
  },
  {
    key: 'order.new.body',
    namespace: 'order',
    description: 'Notification body: new service order',
    ru: 'Вы получили новый заказ для {{service_title}}',
    en: 'You received a new order for {{service_title}}',
    th: 'คุณได้รับคำสั่งซื้อใหม่สำหรับ {{service_title}}',
  },
  {
    key: 'order.accepted.title',
    namespace: 'order',
    description: 'Notification: provider accepted service order (N-21)',
    ru: 'Заказ принят',
    en: 'Order Accepted',
    th: 'คำสั่งซื้อได้รับการยอมรับ',
  },
  {
    key: 'order.accepted.body',
    namespace: 'order',
    description: 'Notification body: provider accepted order',
    ru: 'Поставщик принял ваш заказ для {{service_title}}',
    en: 'Provider accepted your order for {{service_title}}',
    th: 'ผู้ให้บริการยอมรับคำสั่งซื้อของคุณสำหรับ {{service_title}}',
  },
  {
    key: 'order.declined.title',
    namespace: 'order',
    description: 'Notification: provider declined service order (N-22)',
    ru: 'Заказ отклонён',
    en: 'Order Declined',
    th: 'คำสั่งซื้อถูกปฏิเสธ',
  },
  {
    key: 'order.declined.body',
    namespace: 'order',
    description: 'Notification body: provider declined order',
    ru: 'Поставщик отклонил ваш заказ для {{service_title}}. Возврат полной суммы.',
    en: 'Provider declined your order for {{service_title}}. Full refund issued.',
    th: 'ผู้ให้บริการปฏิเสธคำสั่งซื้อของคุณสำหรับ {{service_title}} การคืนเงินแบบเต็ม',
  },
  {
    key: 'order.review_prompt.title',
    namespace: 'order',
    description: 'Notification: prompt to review service order (N-27)',
    ru: 'Оцените услугу',
    en: 'Rate Your Service',
    th: 'ให้คะแนนบริการของคุณ',
  },
  {
    key: 'order.review_prompt.body',
    namespace: 'order',
    description: 'Notification body: prompt to review',
    ru: 'Поделитесь своим мнением о {{service_title}}',
    en: 'Share your feedback on {{service_title}}',
    th: 'แชร์ความคิดเห็นของคุณเกี่ยวกับ {{service_title}}',
  },

  // TM30 Immigration filing (doc 07 F-OPS-2)
  {
    key: 'tm30.escalation.title',
    namespace: 'tm30',
    description: 'Notification: TM30 filing escalated (F-OPS-2)',
    ru: 'TM30 требует внимания',
    en: 'TM30 Filing Needs Attention',
    th: 'การยื่น TM30 ต้องการความสนใจ',
  },
  {
    key: 'tm30.escalation.body',
    namespace: 'tm30',
    description: 'Notification body: TM30 escalation',
    ru: 'Виза гостя {{guest_name}} не подана в течение 24 часов. Требуется срочное действие.',
    en: 'TM30 for {{guest_name}} not filed within 24h. Urgent action required.',
    th: 'TM30 สำหรับ {{guest_name}} ไม่ได้ยื่นภายใน 24 ชั่วโมง จำเป็นต้องดำเนินการเร่งด่วน',
  },

  // Pre-arrival verification (doc 07 F-GUEST-5)
  {
    key: 'notify.stay.prearrival_passports.title',
    namespace: 'notify',
    description: 'Notification: pre-arrival passport reminder (N-07)',
    ru: 'Пожалуйста, предоставьте данные паспорта',
    en: 'Please Provide Your Passport Information',
    th: 'กรุณาให้ข้อมูลหนังสือเดินทางของคุณ',
  },
  {
    key: 'notify.stay.prearrival_passports.body',
    namespace: 'notify',
    description: 'Notification: pre-arrival passport reminder details',
    ru: 'Чтобы завершить подготовку к приезду в {{unit_name}}, пожалуйста, предоставьте данные паспорта для каждого гостя. Крайний срок: {{deadline}}.',
    en: 'To complete your arrival preparation at {{unit_name}}, please provide passport details for each guest. Deadline: {{deadline}}.',
    th: 'เพื่อให้การเตรียมการถึง {{unit_name}} สมบูรณ์ โปรดให้ข้อมูลหนังสือเดินทางของแต่ละแขก ส่วนหนึ่ง: {{deadline}}',
  },
  {
    key: 'notify.stay.verification_failed.title',
    namespace: 'notify',
    description: 'Notification: verification deadline missed (N-08)',
    ru: 'Требуется срочно предоставить паспортные данные',
    en: 'Passport Information Required Urgently',
    th: 'ต้องการข้อมูลหนังสือเดินทางอย่างเร่งด่วน',
  },
  {
    key: 'notify.stay.verification_failed.body',
    namespace: 'notify',
    description: 'Notification: verification deadline missed details',
    ru: 'Гость {{guest_name}} в {{unit_name}} не предоставил паспортные данные к установленному сроку. Персонал может запросить данные при заселении.',
    en: 'Guest {{guest_name}} at {{unit_name}} did not provide passport information by the deadline. Staff can request details at check-in.',
    th: 'แขก {{guest_name}} ที่ {{unit_name}} ไม่ได้ให้ข้อมูลหนังสือเดินทางตามกำหนด พนักงานสามารถขอรายละเอียดได้ระหว่างเช็คอิน',
  },

  // Owner experience (doc 07 F-OWN-2..6)
  {
    key: 'owner.dashboard.title',
    namespace: 'owner',
    description: 'Owner dashboard page title',
    ru: 'Мой портал собственника',
    en: 'Owner Dashboard',
    th: 'แดชบอร์ดเจ้าของ',
  },
  {
    key: 'owner.dashboard.occupancy_this_month',
    namespace: 'owner',
    description: 'Occupancy statistic label',
    ru: 'Занято в этом месяце',
    en: 'Occupied This Month',
    th: 'ครอบครัวในเดือนนี้',
  },
  {
    key: 'owner.dashboard.revenue_this_month',
    namespace: 'owner',
    description: 'Revenue statistic label',
    ru: 'Доход в этом месяце',
    en: 'Revenue This Month',
    th: 'รายรับในเดือนนี้',
  },
  {
    key: 'owner.stay.book_action',
    namespace: 'owner',
    description: 'Action: book owner stay in own unit',
    ru: 'Остановиться в своём доме',
    en: 'Stay in My Unit',
    th: 'เข้าพักในหน่วยของฉัน',
  },
  {
    key: 'owner.stay.modal_title',
    namespace: 'owner',
    description: 'Modal title for booking owner stay',
    ru: 'Зарезервировать пребывание',
    en: 'Book Your Stay',
    th: 'จองการพักของคุณ',
  },
  {
    key: 'owner.stay.select_dates',
    namespace: 'owner',
    description: 'Instruction: select dates for owner stay',
    ru: 'Выберите даты пребывания',
    en: 'Select your stay dates',
    th: 'เลือกวันที่พักของคุณ',
  },
  {
    key: 'owner.stay.notice_requirement',
    namespace: 'owner',
    description: 'Info: minimum notice requirement for owner stay',
    ru: 'Требуется минимум {{hours}} часов предварительного уведомления',
    en: 'Requires minimum {{hours}} hours notice',
    th: 'ต้องแจ้งให้ทราบล่วงหน้าอย่างน้อย {{hours}} ชั่วโมง',
  },
  {
    key: 'owner.sell_interest.card_title',
    namespace: 'owner',
    description: 'Card prompt: thinking of selling property',
    ru: 'Думаете о продаже?',
    en: 'Thinking of Selling?',
    th: 'กำลังคิดที่จะขาย?',
  },
  {
    key: 'owner.sell_interest.card_description',
    namespace: 'owner',
    description: 'Card description: sell interest prompt',
    ru: 'Дайте нам знать о вашем интересе. Наша команда изучит возможность для вас.',
    en: 'Let us know your interest. Our team will explore opportunities for you.',
    th: 'แจ้งให้เราทราบถึงความสนใจของคุณ ทีมของเราจะสำรวจโอกาสสำหรับคุณ',
  },
  {
    key: 'owner.sell_interest.action',
    namespace: 'owner',
    description: 'Action: express interest in selling',
    ru: 'Я заинтересован',
    en: 'I\'m Interested',
    th: 'ฉันสนใจ',
  },
  {
    key: 'owner.portfolio.project_switcher',
    namespace: 'owner',
    description: 'Label: project switcher for portfolio',
    ru: 'Переключить проект',
    en: 'Switch Project',
    th: 'เปลี่ยนโครงการ',
  },

  // Master landing page (doc 08 §2, T-035)
  {
    key: 'landing.hero.kicker',
    namespace: 'landing',
    description: 'Landing page hero kicker',
    ru: 'Обслуживаемое проживание на Пхукете',
    en: 'Serviced living in Phuket',
    th: 'การอยู่อาศัยที่บริการในภูเก็ต',
  },
  {
    key: 'landing.hero.title',
    namespace: 'landing',
    description: 'Landing page hero title',
    ru: 'Ваше место',
    en: 'Your place.',
    th: 'สถานที่ของคุณ',
  },
  {
    key: 'landing.hero.subtitle',
    namespace: 'landing',
    description: 'Landing page hero subtitle',
    ru: 'Перестаньте управлять — начните жить. Один портал для всех потребностей.',
    en: 'Stop managing. Start living. One portal for all your needs.',
    th: 'หยุดการจัดการ เริ่มต้นชีวิต พอร์ทัลเดียวสำหรับความต้องการทั้งหมด',
  },
  {
    key: 'landing.hero.tagline',
    namespace: 'landing',
    description: 'Landing page hero tagline',
    ru: 'Ваше единое место',
    en: 'Your one place.',
    th: 'สถานที่เดียวของคุณ',
  },
  {
    key: 'landing.promise.stay',
    namespace: 'landing',
    description: 'Promise pillar: stay title',
    ru: 'Останься',
    en: 'Stay',
    th: 'อยู่',
  },
  {
    key: 'landing.promise.stay_body',
    namespace: 'landing',
    description: 'Promise pillar: stay description',
    ru: 'Найди дом, забронируй в один клик, оплатите наличными. Никаких комиссий за карты здесь.',
    en: 'Find home, book in one click, pay in cash. No card fees here.',
    th: 'ค้นหาบ้าน จองในการคลิกเดียว จ่ายเป็นเงินสด ไม่มีค่าธรรมเนียมบัตรที่นี่',
  },
  {
    key: 'landing.promise.live',
    namespace: 'landing',
    description: 'Promise pillar: live title',
    ru: 'Живи',
    en: 'Live',
    th: 'อยู่',
  },
  {
    key: 'landing.promise.live_body',
    namespace: 'landing',
    description: 'Promise pillar: live description',
    ru: 'Закажи услугу, раскажи соседям, реши вместе. Обслуживание становится легче.',
    en: 'Order a service, tell your neighbours, decide together. Living becomes simpler.',
    th: 'สั่งบริการ บอกเพื่อนบ้านของคุณ ตัดสินใจร่วมกัน การอยู่อาศัยจะง่ายขึ้น',
  },
  {
    key: 'landing.promise.own',
    namespace: 'landing',
    description: 'Promise pillar: own title',
    ru: 'Владей',
    en: 'Own',
    th: 'เป็นเจ้าของ',
  },
  {
    key: 'landing.promise.own_body',
    namespace: 'landing',
    description: 'Promise pillar: own description',
    ru: 'Получай доход. Видишь каждый гост, каждый платеж, каждую заявку. Управление — это факты.',
    en: 'Earn income. See every guest, every payment, every request. Management is fact-based.',
    th: 'ได้รับรายได้ เห็นแขกทุกคน การชำระเงินทุกครั้ง ทุกคำขอ การจัดการเป็นข้อเท็จจริง',
  },
  {
    key: 'landing.trust.title',
    namespace: 'landing',
    description: 'Trust section title',
    ru: 'Доверие, видимое наяву',
    en: 'Trust, made visible',
    th: 'ความเชื่อถือที่มองเห็นได้',
  },
  {
    key: 'landing.trust.verified',
    namespace: 'landing',
    description: 'Trust step: verified guests',
    ru: 'Гости проверены',
    en: 'Guests verified',
    th: 'แขกได้รับการยืนยัน',
  },
  {
    key: 'landing.trust.handled',
    namespace: 'landing',
    description: 'Trust step: compliance handled',
    ru: 'Соответствие — наш груз',
    en: 'Compliance handled',
    th: 'การปฏิบัติตามกฎระเบียบได้จัดการ',
  },
  {
    key: 'landing.trust.protected',
    namespace: 'landing',
    description: 'Trust step: data protected',
    ru: 'Данные защищены',
    en: 'Data protected',
    th: 'ข้อมูลได้รับการป้องกัน',
  },
  {
    key: 'landing.services.title',
    namespace: 'landing',
    description: 'Services section title',
    ru: 'Для каждого момента',
    en: 'Everything around the stay',
    th: 'ทุกอย่างรอบการเข้าพัก',
  },
  {
    key: 'landing.services.body',
    namespace: 'landing',
    description: 'Services section description',
    ru: 'Уборка, ремонт, доставка — все обслуживание утверждено и возглавляется.',
    en: 'Cleaning, repairs, deliveries — every service vetted and led.',
    th: 'ทำความสะอาด การซ่อมแซม การจัดส่ง — บริการทั้งหมดตรวจสอบและนำ',
  },

  // Audience pages (doc 08 §3, T-035)
  {
    key: 'audience.owners.title',
    namespace: 'audience',
    description: 'Owners audience page title',
    ru: 'Для собственников',
    en: 'For Owners',
    th: 'สำหรับเจ้าของ',
  },
  {
    key: 'audience.owners.subtitle',
    namespace: 'audience',
    description: 'Owners audience page subtitle',
    ru: 'Инвестируйте с уверенностью. Видьте результаты. Спите спокойно.',
    en: 'Invest with confidence. See results. Sleep soundly.',
    th: 'ลงทุนอย่างมั่นใจ เห็นผล นอนสนิท',
  },
  {
    key: 'audience.owners.cta',
    namespace: 'audience',
    description: 'Owners page CTA button',
    ru: 'Доверить свой дом',
    en: 'Entrust your unit',
    th: 'มอบหมายหน่วยของคุณ',
  },
  {
    key: 'audience.guests.title',
    namespace: 'audience',
    description: 'Guests audience page title',
    ru: 'Для гостей',
    en: 'For Guests',
    th: 'สำหรับแขก',
  },
  {
    key: 'audience.guests.subtitle',
    namespace: 'audience',
    description: 'Guests audience page subtitle',
    ru: 'Отели не нужны. Здесь — дом, безопасность, поддержка.',
    en: 'Hotels unnecessary. Here: home, safety, support.',
    th: 'โรงแรมไม่จำเป็น ที่นี่: บ้าน ความปลอดภัย การสนับสนุน',
  },
  {
    key: 'audience.guests.cta',
    namespace: 'audience',
    description: 'Guests page CTA button',
    ru: 'Найти жилье',
    en: 'Search stays',
    th: 'ค้นหาการพัก',
  },
  {
    key: 'audience.developers.title',
    namespace: 'audience',
    description: 'Developers audience page title',
    ru: 'Для разработчиков',
    en: 'For Developers',
    th: 'สำหรับนักพัฒนา',
  },
  {
    key: 'audience.developers.subtitle',
    namespace: 'audience',
    description: 'Developers audience page subtitle',
    ru: 'Откройте класс своего проекта. Управляемая платформа, интегрированное управление.',
    en: 'Uplift your project class. Managed platform, integrated ops.',
    th: 'ยกระดับชั้นโครงการของคุณ แพลตฟอร์มที่ได้รับการจัดการ การปฏิบัติการแบบรวม',
  },
  {
    key: 'audience.developers.cta',
    namespace: 'audience',
    description: 'Developers page CTA button',
    ru: 'Поговорить с нами',
    en: 'Talk to us',
    th: 'พูดกับเรา',
  },
  {
    key: 'audience.buyers.title',
    namespace: 'audience',
    description: 'Buyers audience page title',
    ru: 'Для инвесторов',
    en: 'For Buyers',
    th: 'สำหรับผู้ซื้อ',
  },
  {
    key: 'audience.buyers.subtitle',
    namespace: 'audience',
    description: 'Buyers audience page subtitle',
    ru: 'Покупка уже в пути? Наша команда помогает перейти на платформу.',
    en: 'Purchase already underway? Our team eases the handoff.',
    th: 'ซื้อแล้วไหม? ทีมของเราอำนวยความสะดวกในการส่งมอบ',
  },
  {
    key: 'audience.buyers.cta',
    namespace: 'audience',
    description: 'Buyers page CTA button',
    ru: 'Начать разговор',
    en: 'Start the conversation',
    th: 'เริ่มการสนทนา',
  },
  {
    key: 'audience.mc.title',
    namespace: 'audience',
    description: 'Management companies audience page title',
    ru: 'Для управляющих компаний',
    en: 'For Management Companies',
    th: 'สำหรับ บริษัทจัดการ',
  },
  {
    key: 'audience.mc.subtitle',
    namespace: 'audience',
    description: 'Management companies audience page subtitle',
    ru: 'Требуемые операции. Единая платформа. Больше доход.',
    en: 'Demanded ops. Single platform. More income.',
    th: 'ปฏิบัติการที่ต้องการ แพลตฟอร์มเดียว รายได้มากขึ้น',
  },
  {
    key: 'audience.mc.cta',
    namespace: 'audience',
    description: 'Management companies page CTA button',
    ru: 'Подробнее',
    en: 'Learn more',
    th: 'เรียนรู้เพิ่มเติม',
  },
  {
    key: 'audience.providers.title',
    namespace: 'audience',
    description: 'Providers audience page title',
    ru: 'Для поставщиков услуг',
    en: 'For Providers',
    th: 'สำหรับผู้ให้บริการ',
  },
  {
    key: 'audience.providers.subtitle',
    namespace: 'audience',
    description: 'Providers audience page subtitle',
    ru: 'Устойчивый поток заказов. Прямое общение. Честная оплата.',
    en: 'Steady order flow. Direct comms. Fair pay.',
    th: 'ที่อื่นเข้ามาต่อเนื่อง การสื่อสารโดยตรง การจ่ายเงินอย่างยุติธรรม',
  },
  {
    key: 'audience.providers.cta',
    namespace: 'audience',
    description: 'Providers page CTA button',
    ru: 'Подать заявку',
    en: 'Apply',
    th: 'สมัคร',
  },

  // Project landing page (doc 08 §4, T-035)
  {
    key: 'project_page.available_units',
    namespace: 'project_page',
    description: 'Available units label',
    ru: 'Доступные жилья',
    en: 'Available units',
    th: 'หน่วยที่ว่าง',
  },
  {
    key: 'project_page.amenities',
    namespace: 'project_page',
    description: 'Amenities section title',
    ru: 'Удобства',
    en: 'Amenities',
    th: 'สิ่งอำนวยความสะดวก',
  },
  {
    key: 'project_page.services_available',
    namespace: 'project_page',
    description: 'Services available section title',
    ru: 'Доступные услуги',
    en: 'Services available here',
    th: 'บริการที่มีให้ที่นี่',
  },
  {
    key: 'project_page.handbook',
    namespace: 'project_page',
    description: 'Handbook section title',
    ru: 'Справочник по дому',
    en: 'Property Handbook',
    th: 'คู่มือทรัพย์สิน',
  },
  {
    key: 'project_page.check_availability',
    namespace: 'project_page',
    description: 'Check availability CTA',
    ru: 'Проверить наличие',
    en: 'Check availability',
    th: 'ตรวจสอบความพร้อม',
  },

  // Trust pages (doc 08 §5, T-035)
  {
    key: 'trust.title',
    namespace: 'trust',
    description: 'Trust page title',
    ru: 'Как работает доверие',
    en: 'How trust works',
    th: 'วิธีการทำงานของความเชื่อถือ',
  },
  {
    key: 'trust.intro',
    namespace: 'trust',
    description: 'Trust page introduction',
    ru: 'Каждый гост отправляет паспортные данные. Каждый платеж записывается. Каждая жалоба отслеживается. Доверие основано на фактах.',
    en: 'Every guest submits passports. Every payment is recorded. Every complaint is tracked. Trust is fact-based.',
    th: 'แขกทุกคนส่งหนังสือเดินทาง การชำระเงินทุกครั้งบันทึกไว้ ข้อร้องเรียนทุกเรื่องติดตามได้ ความเชื่อถือขึ้นอยู่กับข้อเท็จจริง',
  },
  {
    key: 'trust.ombudsman.title',
    namespace: 'trust',
    description: 'Ombudsman page title (Q15 - founder provided)',
    ru: 'Омбудсмен',
    en: 'The Ombudsman',
    th: 'อัยการสอบสวน',
  },
  {
    key: 'trust.ombudsman.intro',
    namespace: 'trust',
    description: 'Ombudsman page intro (Q15 - founder provided)',
    ru: '[Требуется текст основателя]',
    en: '[Founder credential text required]',
    th: '[ต้องการข้อความสัญญาอนุญาตของผู้ก่อตั้ง]',
  },

  // Legal pages (doc 08 §5, T-035)
  {
    key: 'legal.entity.name',
    namespace: 'legal',
    description: 'Operating entity name',
    ru: 'Ignatev Estate Co., Ltd',
    en: 'Ignatev Estate Co., Ltd',
    th: 'Ignatev Estate Co., Ltd',
  },
  {
    key: 'legal.entity.dbd_registration',
    namespace: 'legal',
    description: 'DBD registration number',
    ru: '083-5-56602358-7',
    en: '083-5-56602358-7',
    th: '083-5-56602358-7',
  },
  {
    key: 'legal.entity.address',
    namespace: 'legal',
    description: 'Registered address',
    ru: 'Plaza Del Mar, No.1 Pasak-Koktanod Rd, office 115–116, Cherngtalay, Thalang, Phuket 83110',
    en: 'Plaza Del Mar, No.1 Pasak-Koktanod Rd, office 115–116, Cherngtalay, Thalang, Phuket 83110',
    th: 'Plaza Del Mar, No.1 Pasak-Koktanod Rd, office 115–116, Cherngtalay, Thalang, Phuket 83110',
  },
  {
    key: 'legal.entity.director',
    namespace: 'legal',
    description: 'Director name',
    ru: 'Pavel Ignatev',
    en: 'Pavel Ignatev',
    th: 'Pavel Ignatev',
  },
  {
    key: 'legal.entity.email',
    namespace: 'legal',
    description: 'Contact email',
    ru: 'pavel@ignatevestate.com',
    en: 'pavel@ignatevestate.com',
    th: 'pavel@ignatevestate.com',
  },
  {
    key: 'legal.entity.phone',
    namespace: 'legal',
    description: 'Contact phone',
    ru: '+66 92 240 7355',
    en: '+66 92 240 7355',
    th: '+66 92 240 7355',
  },
  {
    key: 'legal.terms.title',
    namespace: 'legal',
    description: 'Terms of service page title',
    ru: 'Условия обслуживания',
    en: 'Terms of Service',
    th: 'เงื่อนไขการใช้บริการ',
  },
  {
    key: 'legal.privacy.title',
    namespace: 'legal',
    description: 'Privacy policy page title',
    ru: 'Политика конфиденциальности',
    en: 'Privacy Policy',
    th: 'นโยบายความเป็นส่วนตัว',
  },
];

export async function seedContent(
  db: PrismaClient,
  systemIdentityId?: string
): Promise<void> {
  const identityId = systemIdentityId || 'system';

  for (const keyDef of COMMON_KEYS) {
    // Ensure content key exists
    await ensureContentKey(
      db,
      keyDef.key,
      keyDef.namespace,
      keyDef.description,
      keyDef.supportsRich || false
    );

    // Set translations for all locales
    const locales: Locale[] = ['ru', 'en', 'th'];
    for (const locale of locales) {
      const value = keyDef[locale];
      await setTranslation(
        db,
        keyDef.key,
        locale,
        value,
        'ok',
        identityId
      );
    }
  }
}
