/**
 * English fallbacks for the owner property wizard (content namespace
 * `property_onboard`, doc 05). Kept outside the 'use client' wizard so the
 * server page can pass them to getLabels.
 */
export const WIZARD_COPY = {
  'property_onboard.step.property': 'Your property',
  'property_onboard.step.residence': 'Residence',
  'property_onboard.step.details': 'Details',
  'property_onboard.step.photos': 'Photos',
  'property_onboard.step.offer': 'How to offer',
  'property_onboard.step.review': 'Review',
  'property_onboard.error.save_property': 'Could not save your property.',
  'property_onboard.notice.submitted': 'Application sent to the myUNO team for verification.',
  'property_onboard.notice.draft_saved': 'Draft saved. You can return to it later.',
  'property_onboard.error.save': 'Could not save.',
  'property_onboard.offer.short_stay': 'Short stays',
  'property_onboard.offer.monthly': 'Monthly rental',
  'property_onboard.offer.yearly': 'Long-term rental',
  'property_onboard.offer.sale': 'For sale',
  'property_onboard.back': '← My listings',
  'property_onboard.kicker': 'ADD A PROPERTY',
  'property_onboard.title': 'Tell us about your place',
  'property_onboard.progress': '{step} of {total}',
  'property_onboard.intro': 'Save your progress at any time. Nothing goes public until reviewed and approved by myUNO.',
  'property_onboard.continue_earlier': 'Continue an earlier application',
  'property_onboard.untitled': 'Untitled property',
  'property_onboard.status.draft': 'Draft',
  'property_onboard.status.submitted': 'Submitted',
  'property_onboard.status.converted': 'In activation',
  'property_onboard.converted_body': 'Your submission has become a canonical draft property. Our team is completing activation checks.',
  'property_onboard.onboarding_state': 'Onboarding state:',
  'property_onboard.remaining_blockers': 'Remaining blockers',
  'property_onboard.no_blockers': 'No derived onboarding blockers are currently recorded.',
  'property_onboard.listings_link': 'My listings and property settings',
  'property_onboard.submitted_body': 'Your property is submitted for review. Our team will verify your relationship to the property and applicable permissions before activation.',
  'property_onboard.kind.home': 'A home in a residence',
  'property_onboard.kind.home_hint': 'Apartment, condo, villa or house',
  'property_onboard.kind.resort': 'An entire property',
  'property_onboard.kind.resort_hint': 'Resort, hotel or villa estate',
  'property_onboard.kind.management': 'I represent a management company',
  'property_onboard.kind.management_hint': 'Submit properties on behalf of owners',
  'property_onboard.find_residence': 'Find an existing residence',
  'property_onboard.search_residence': 'Search by building or address',
  'property_onboard.not_listed_residence': 'My residence is not listed',
  'property_onboard.proposed_project': 'Name and address of the complex',
  'property_onboard.proposed_hint': 'A proposed residence is reviewed for duplicates before it becomes a project record.',
  'property_onboard.about_residence': 'Tell us about this residence',
  'property_onboard.project_type': 'Project type',
  'property_onboard.type.condominium': 'Condominium',
  'property_onboard.type.resort': 'Resort / hotel',
  'property_onboard.type.villa_estate': 'Villa estate',
  'property_onboard.type.standalone': 'Standalone property',
  'property_onboard.address': 'Address',
  'property_onboard.address_placeholder': 'Street, district, city',
  'property_onboard.area': 'Area',
  'property_onboard.select_area': 'Select area',
  'property_onboard.latitude': 'Latitude',
  'property_onboard.longitude': 'Longitude',
  'property_onboard.coords_hint': 'Find coordinates in your map app. The myUNO team verifies the location before creation.',
  'property_onboard.project_photos': 'Shared project photos',
  'property_onboard.error.upload': 'Upload failed',
  'property_onboard.project_photos_count': '{count} project photos · first photo is the proposed cover',
  'property_onboard.project_photo_alt': 'Shared complex photo {n}',
  'property_onboard.set_cover': 'Set cover',
  'property_onboard.remove': 'Remove',
  'property_onboard.find_home_hint': 'Find an existing home first. Select it to reuse the canonical Unit. Choose “not listed” only when no match exists.',
  'property_onboard.search_homes': 'Search existing homes',
  'property_onboard.search_homes_placeholder': 'Unit number, villa name or floor',
  'property_onboard.unit_summary': '{bedrooms} BR · {bathrooms} BA',
  'property_onboard.floor_n': 'Floor {floor}',
  'property_onboard.size_sqm': '{size} sqm',
  'property_onboard.not_listed_home': 'My property is not listed',
  'property_onboard.home_name': 'Home name or number',
  'property_onboard.home_name_placeholder': 'e.g. Building F, 705',
  'property_onboard.home_type': 'Home type',
  'property_onboard.unit.apartment': 'Apartment',
  'property_onboard.unit.villa': 'Villa',
  'property_onboard.unit.house': 'House',
  'property_onboard.max_guests': 'Maximum guests',
  'property_onboard.bedrooms': 'Bedrooms',
  'property_onboard.bathrooms': 'Bathrooms',
  'property_onboard.size': 'Area (sqm)',
  'property_onboard.floor': 'Floor',
  'property_onboard.describe': 'Describe your home',
  'property_onboard.describe_placeholder': 'What makes this home special?',
  'property_onboard.photos_intro': 'Upload photos of the actual home. Project-wide photos are managed separately by authorized project editors.',
  'property_onboard.error.photo_upload': 'Photo upload failed',
  'property_onboard.notice.photos_uploaded': 'Photos uploaded. Save the draft to attach them to the submission.',
  'property_onboard.photos_count': '{count} photos attached · up to 50 · 8 MB each. The first photo becomes the cover.',
  'property_onboard.home_photo_alt': 'Home photo {n}',
  'property_onboard.move_left': 'Move left',
  'property_onboard.offers_intro': 'Choose your rental offers. myUNO remains the guest booking and support contact. Property services are provided under the verified owner or management-company agreement.',
  'property_onboard.who_services': 'Who provides property services?',
  'property_onboard.model.owner_direct': 'I am the owner and provide property services',
  'property_onboard.model.via_management_company': 'I represent an authorized management company',
  'property_onboard.model.direct_managed': 'I want myUNO management',
  'property_onboard.company_name': 'Management company name',
  'property_onboard.company_placeholder': 'Company or manager name',
  'property_onboard.model_hint': 'This is a requested operating model only. It does not create management authority, team access or activate bookings.',
  'property_onboard.nightly': 'Proposed nightly price, THB',
  'property_onboard.min_nights': 'Minimum nights',
  'property_onboard.terms_hint': 'Proposed rental terms are reviewed before publication. After authority is verified, your listing settings let you maintain dated prices, unavailable dates and photos.',
  'property_onboard.contact': 'Preferred contact',
  'property_onboard.contact_placeholder': 'Phone or email',
  'property_onboard.review.property': 'Property:',
  'property_onboard.review.residence': 'Residence:',
  'property_onboard.review.offers': 'Offers:',
  'property_onboard.review.model': 'Operating model:',
  'property_onboard.not_supplied': 'Not supplied',
  'property_onboard.existing_unit': ' · existing canonical Unit',
  'property_onboard.not_selected': 'Not selected',
  'property_onboard.review_hint': 'Submitting is not publication, ownership verification, a management mandate or an authorization to accept bookings.',
  'property_onboard.nav.back': 'Back',
  'property_onboard.nav.save': 'Save draft',
  'property_onboard.nav.continue': 'Continue →',
  'property_onboard.nav.submit': 'Submit for review',
};
